<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Bayesian estimation and inference | Research Design and Statistics</title>
  <meta name="description" content="An introduction to research design and statistics" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Bayesian estimation and inference | Research Design and Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to research design and statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Bayesian estimation and inference | Research Design and Statistics" />
  
  <meta name="twitter:description" content="An introduction to research design and statistics" />
  

<meta name="author" content="Bradley J. Cosentino" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability-as-the-language-of-uncertainty.html"/>
<link rel="next" href="bayesian-workflow.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#work-in-progress"><i class="fa fa-check"></i>Work in progress</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html"><i class="fa fa-check"></i><b>1</b> Why Statistics? The Problem of Uncertainty</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#the-nature-of-science"><i class="fa fa-check"></i><b>1.1</b> The nature of science</a></li>
<li class="chapter" data-level="1.2" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#goals-of-scientific-research"><i class="fa fa-check"></i><b>1.2</b> Goals of scientific research</a></li>
<li class="chapter" data-level="1.3" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#three-general-goals-of-scientific-research"><i class="fa fa-check"></i><b>1.3</b> Three general goals of scientific research</a></li>
<li class="chapter" data-level="1.4" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#research-design-and-statistical-analysis-depend-on-your-goal"><i class="fa fa-check"></i><b>1.4</b> Research design and statistical analysis depend on your goal</a></li>
<li class="chapter" data-level="1.5" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#you-cant-escape-uncertainty-in-science"><i class="fa fa-check"></i><b>1.5</b> You can’t escape uncertainty in science</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html"><i class="fa fa-check"></i><b>2</b> Scientific workflow: Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-questions"><i class="fa fa-check"></i><b>2.1</b> Research questions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#clarify-your-primary-goal-description-prediction-or-explanation"><i class="fa fa-check"></i><b>2.1.1</b> Clarify your primary goal: description, prediction, or explanation?</a></li>
<li class="chapter" data-level="2.1.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#identify-the-scope-of-inference-the-who-what-when-and-where-of-your-study."><i class="fa fa-check"></i><b>2.1.2</b> Identify the scope of inference: The who, what, when, and where of your study.</a></li>
<li class="chapter" data-level="2.1.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-interesting"><i class="fa fa-check"></i><b>2.1.3</b> Make it interesting</a></li>
<li class="chapter" data-level="2.1.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-answerable-with-data"><i class="fa fa-check"></i><b>2.1.4</b> Make it answerable with data</a></li>
<li class="chapter" data-level="2.1.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#ground-it-in-theory"><i class="fa fa-check"></i><b>2.1.5</b> Ground it in theory</a></li>
<li class="chapter" data-level="2.1.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-sure-its-feasible"><i class="fa fa-check"></i><b>2.1.6</b> Make sure it’s feasible</a></li>
<li class="chapter" data-level="2.1.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#avoid-analyzing-the-data-before-stating-your-question"><i class="fa fa-check"></i><b>2.1.7</b> Avoid analyzing the data before stating your question</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#connecting-ideas-to-data"><i class="fa fa-check"></i><b>2.2</b> Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#theory"><i class="fa fa-check"></i><b>2.2.1</b> Theory</a></li>
<li class="chapter" data-level="2.2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-question"><i class="fa fa-check"></i><b>2.2.2</b> Research question</a></li>
<li class="chapter" data-level="2.2.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#generative-model"><i class="fa fa-check"></i><b>2.2.3</b> Generative model</a></li>
<li class="chapter" data-level="2.2.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#study-design"><i class="fa fa-check"></i><b>2.2.4</b> Study design</a></li>
<li class="chapter" data-level="2.2.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimand"><i class="fa fa-check"></i><b>2.2.5</b> Estimand</a></li>
<li class="chapter" data-level="2.2.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#target-population"><i class="fa fa-check"></i><b>2.2.6</b> Target population</a></li>
<li class="chapter" data-level="2.2.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#sample-data"><i class="fa fa-check"></i><b>2.2.7</b> Sample data</a></li>
<li class="chapter" data-level="2.2.8" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#statistical-model"><i class="fa fa-check"></i><b>2.2.8</b> Statistical model</a></li>
<li class="chapter" data-level="2.2.9" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimate"><i class="fa fa-check"></i><b>2.2.9</b> Estimate</a></li>
<li class="chapter" data-level="2.2.10" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#summary"><i class="fa fa-check"></i><b>2.2.10</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to Data and R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#an-introduction-to-data"><i class="fa fa-check"></i><b>3.1</b> An introduction to data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variables-and-observations"><i class="fa fa-check"></i><b>3.1.1</b> Variables and observations</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#types-of-variables"><i class="fa fa-check"></i><b>3.1.2</b> Types of variables</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#relationships-between-variables"><i class="fa fa-check"></i><b>3.1.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variable-naming-conventions-and-metadata"><i class="fa fa-check"></i><b>3.1.4</b> Variable naming conventions and metadata</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#introduction-to-r"><i class="fa fa-check"></i><b>3.2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>3.2.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#the-rstudio-interface"><i class="fa fa-check"></i><b>3.2.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#basic-data-manipulation-in-r"><i class="fa fa-check"></i><b>3.2.3</b> Basic data manipulation in R</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#scripting"><i class="fa fa-check"></i><b>3.2.4</b> Scripting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>4</b> Describing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="describing-data.html"><a href="describing-data.html#defining-the-population"><i class="fa fa-check"></i><b>4.1</b> Defining the population</a></li>
<li class="chapter" data-level="4.2" data-path="describing-data.html"><a href="describing-data.html#loading-data-into-r"><i class="fa fa-check"></i><b>4.2</b> Loading data into R</a></li>
<li class="chapter" data-level="4.3" data-path="describing-data.html"><a href="describing-data.html#inspecting-the-dataset"><i class="fa fa-check"></i><b>4.3</b> Inspecting the dataset</a></li>
<li class="chapter" data-level="4.4" data-path="describing-data.html"><a href="describing-data.html#describing-single-variables"><i class="fa fa-check"></i><b>4.4</b> Describing single variables</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="describing-data.html"><a href="describing-data.html#qualitative-variables"><i class="fa fa-check"></i><b>4.4.1</b> Qualitative variables</a></li>
<li class="chapter" data-level="4.4.2" data-path="describing-data.html"><a href="describing-data.html#quantitative-variables"><i class="fa fa-check"></i><b>4.4.2</b> Quantitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="describing-data.html"><a href="describing-data.html#describing-relationships-between-variables"><i class="fa fa-check"></i><b>4.5</b> Describing relationships between variables</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-variables"><i class="fa fa-check"></i><b>4.5.1</b> Associations between quantitative variables</a></li>
<li class="chapter" data-level="4.5.2" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-and-qualitative-variables"><i class="fa fa-check"></i><b>4.5.2</b> Associations between quantitative and qualitative variables</a></li>
<li class="chapter" data-level="4.5.3" data-path="describing-data.html"><a href="describing-data.html#associations-between-qualitative-variables"><i class="fa fa-check"></i><b>4.5.3</b> Associations between qualitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="describing-data.html"><a href="describing-data.html#next-steps"><i class="fa fa-check"></i><b>4.6</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html"><i class="fa fa-check"></i><b>5</b> Uncertainty from sampling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sampling-requires-estimation"><i class="fa fa-check"></i><b>5.1</b> Sampling requires estimation</a></li>
<li class="chapter" data-level="5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#parameters-estimates-estimands"><i class="fa fa-check"></i><b>5.2</b> Parameters, estimates, estimands</a></li>
<li class="chapter" data-level="5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sources-of-uncertainty-from-sampling"><i class="fa fa-check"></i><b>5.3</b> Sources of uncertainty from sampling</a></li>
<li class="chapter" data-level="5.4" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy-and-precision"><i class="fa fa-check"></i><b>5.4</b> Accuracy and precision</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy"><i class="fa fa-check"></i><b>5.4.1</b> Accuracy</a></li>
<li class="chapter" data-level="5.4.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#precision"><i class="fa fa-check"></i><b>5.4.2</b> Precision</a></li>
<li class="chapter" data-level="5.4.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#considering-accuracy-and-precision-together"><i class="fa fa-check"></i><b>5.4.3</b> Considering accuracy and precision together</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#maximizing-accuracy-and-precision-of-estimates"><i class="fa fa-check"></i><b>5.5</b> Maximizing accuracy and precision of estimates</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#random-sampling"><i class="fa fa-check"></i><b>5.5.1</b> Random sampling</a></li>
<li class="chapter" data-level="5.5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#replication"><i class="fa fa-check"></i><b>5.5.2</b> Replication</a></li>
<li class="chapter" data-level="5.5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#take-home-points"><i class="fa fa-check"></i><b>5.5.3</b> Take-home points</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html"><i class="fa fa-check"></i><b>6</b> Probability as the Language of Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#defining-probability"><i class="fa fa-check"></i><b>6.1</b> Defining probability</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#frequentist-definition"><i class="fa fa-check"></i><b>6.1.1</b> Frequentist definition</a></li>
<li class="chapter" data-level="6.1.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#bayesian-definition"><i class="fa fa-check"></i><b>6.1.2</b> Bayesian definition</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#probability-rules"><i class="fa fa-check"></i><b>6.2</b> Probability rules</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#individual-events"><i class="fa fa-check"></i><b>6.2.1</b> Individual events</a></li>
<li class="chapter" data-level="6.2.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#joint-events"><i class="fa fa-check"></i><b>6.2.2</b> Joint events</a></li>
<li class="chapter" data-level="6.2.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#general-addition-rule"><i class="fa fa-check"></i><b>6.2.3</b> General addition rule</a></li>
<li class="chapter" data-level="6.2.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#quantifying-marginal-probabilities"><i class="fa fa-check"></i><b>6.2.4</b> Quantifying marginal probabilities</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions"><i class="fa fa-check"></i><b>6.3</b> Sampling from probability distributions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-populations-is-probabalistic"><i class="fa fa-check"></i><b>6.3.1</b> Sampling from populations is probabalistic</a></li>
<li class="chapter" data-level="6.3.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#discrete-random-variables"><i class="fa fa-check"></i><b>6.3.2</b> Discrete random variables</a></li>
<li class="chapter" data-level="6.3.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#continuous-random-variables"><i class="fa fa-check"></i><b>6.3.3</b> Continuous random variables</a></li>
<li class="chapter" data-level="6.3.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions-1"><i class="fa fa-check"></i><b>6.3.4</b> Sampling from probability distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html"><i class="fa fa-check"></i><b>7</b> Bayesian estimation and inference</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#scientific-workflow-for-the-problem"><i class="fa fa-check"></i><b>7.1</b> Scientific workflow for the problem</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#theory-and-the-research-question"><i class="fa fa-check"></i><b>7.1.1</b> Theory and the research question</a></li>
<li class="chapter" data-level="7.1.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#generative-model-and-estimand"><i class="fa fa-check"></i><b>7.1.2</b> Generative model and estimand</a></li>
<li class="chapter" data-level="7.1.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-and-estimate"><i class="fa fa-check"></i><b>7.1.3</b> Statistical model and estimate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#bayes-theorem"><i class="fa fa-check"></i><b>7.2</b> Bayes Theorem</a></li>
<li class="chapter" data-level="7.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#applying-bayes-theorem-to-statistical-analysis"><i class="fa fa-check"></i><b>7.3</b> Applying Bayes Theorem to statistical analysis</a></li>
<li class="chapter" data-level="7.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#steps-of-estimation-with-bayesian-inference"><i class="fa fa-check"></i><b>7.4</b> Steps of estimation with Bayesian inference</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specify-the-prior-distribution"><i class="fa fa-check"></i><b>7.4.1</b> Specify the prior distribution</a></li>
<li class="chapter" data-level="7.4.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-likelihood-of-the-data"><i class="fa fa-check"></i><b>7.4.2</b> Quantify the likelihood of the data</a></li>
<li class="chapter" data-level="7.4.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-total-probability-of-the-data-marginal-likelihood"><i class="fa fa-check"></i><b>7.4.3</b> Quantify the total probability of the data (marginal likelihood)</a></li>
<li class="chapter" data-level="7.4.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-posterior-distribution"><i class="fa fa-check"></i><b>7.4.4</b> Quantify the posterior distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#summarizing-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5</b> Summarizing the posterior distribution</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#sampling-from-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5.1</b> Sampling from the posterior distribution</a></li>
<li class="chapter" data-level="7.5.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#central-tendency-and-variance"><i class="fa fa-check"></i><b>7.5.2</b> Central tendency and variance</a></li>
<li class="chapter" data-level="7.5.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#intervals"><i class="fa fa-check"></i><b>7.5.3</b> Intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-priors"><i class="fa fa-check"></i><b>7.6</b> Specifying priors</a></li>
<li class="chapter" data-level="7.7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#decision-making"><i class="fa fa-check"></i><b>7.7</b> Decision making</a></li>
<li class="chapter" data-level="7.8" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-and-fitting-statistical-models-with-bayes"><i class="fa fa-check"></i><b>7.8</b> Specifying and fitting statistical models with Bayes</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-specification"><i class="fa fa-check"></i><b>7.8.1</b> Statistical model specification</a></li>
<li class="chapter" data-level="7.8.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#fitting-models-with-brms"><i class="fa fa-check"></i><b>7.8.2</b> Fitting models with <em>brms</em></a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i><b>7.9</b> Estimation for a continuous random variable</a></li>
<li class="chapter" data-level="7.10" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#next-steps-1"><i class="fa fa-check"></i><b>7.10</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html"><i class="fa fa-check"></i><b>8</b> Bayesian Workflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#prior-distribution-choices"><i class="fa fa-check"></i><b>8.1</b> Prior distribution choices</a></li>
<li class="chapter" data-level="8.2" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#prior-predictive-checks"><i class="fa fa-check"></i><b>8.2</b> Prior predictive checks</a></li>
<li class="chapter" data-level="8.3" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#posterior-predictive-checks"><i class="fa fa-check"></i><b>8.3</b> Posterior predictive checks</a></li>
<li class="chapter" data-level="8.4" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#next-steps-2"><i class="fa fa-check"></i><b>8.4</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-linear-model.html"><a href="the-linear-model.html"><i class="fa fa-check"></i><b>9</b> The linear model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-linear-model.html"><a href="the-linear-model.html#statistical-models"><i class="fa fa-check"></i><b>9.1</b> Statistical models</a></li>
<li class="chapter" data-level="9.2" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-model"><i class="fa fa-check"></i><b>9.2</b> Linear model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="the-linear-model.html"><a href="the-linear-model.html#basic-structure-of-the-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> Basic structure of the linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="the-linear-model.html"><a href="the-linear-model.html#fitting-the-linear-model-in-brms"><i class="fa fa-check"></i><b>9.2.2</b> Fitting the linear model in brms</a></li>
<li class="chapter" data-level="9.2.3" data-path="the-linear-model.html"><a href="the-linear-model.html#how-a-frequentist-might-do-it"><i class="fa fa-check"></i><b>9.2.3</b> How a frequentist might do it</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-models-with-categorical-predictors"><i class="fa fa-check"></i><b>9.3</b> Linear models with categorical predictors</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="the-linear-model.html"><a href="the-linear-model.html#binary-explanatory-variables"><i class="fa fa-check"></i><b>9.3.1</b> Binary explanatory variables</a></li>
<li class="chapter" data-level="9.3.2" data-path="the-linear-model.html"><a href="the-linear-model.html#categorical-predictors-with-more-than-two-categories"><i class="fa fa-check"></i><b>9.3.2</b> Categorical predictors with more than two categories</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html"><i class="fa fa-check"></i><b>10</b> Graphical Causal Models</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>10.1</b> Directed acyclic graphs (DAGs)</a></li>
<li class="chapter" data-level="10.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#three-causal-structures-in-dags"><i class="fa fa-check"></i><b>10.2</b> Three causal structures in DAGs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-fork-confounders"><i class="fa fa-check"></i><b>10.2.1</b> The fork: confounders</a></li>
<li class="chapter" data-level="10.2.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-pipe-mediators"><i class="fa fa-check"></i><b>10.2.2</b> The pipe: mediators</a></li>
<li class="chapter" data-level="10.2.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-inverted-fork-colliders"><i class="fa fa-check"></i><b>10.2.3</b> The inverted fork: colliders</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#closing-backdoor-paths"><i class="fa fa-check"></i><b>10.3</b> Closing backdoor paths</a></li>
<li class="chapter" data-level="10.4" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#like-all-models-dags-require-assumptions"><i class="fa fa-check"></i><b>10.4</b> Like all models, DAGs require assumptions</a></li>
<li class="chapter" data-level="10.5" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#types-of-study-designs"><i class="fa fa-check"></i><b>10.5</b> Types of Study Designs</a></li>
<li class="chapter" data-level="10.6" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#experimental-studies"><i class="fa fa-check"></i><b>10.6</b> Experimental studies</a></li>
<li class="chapter" data-level="10.7" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#observational-studies"><i class="fa fa-check"></i><b>10.7</b> Observational studies</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#pros-and-cons-of-prospective-vs.-retrospective-studies-planned"><i class="fa fa-check"></i><b>10.7.1</b> Pros and cons of prospective vs. retrospective studies (planned)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html"><i class="fa fa-check"></i><b>11</b> Causal inference with linear models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#linear-models-with-multiple-predictor-variables"><i class="fa fa-check"></i><b>11.1</b> Linear models with multiple predictor variables</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#generic-linear-model-with-two-predictors"><i class="fa fa-check"></i><b>11.1.1</b> Generic linear model with two predictors</a></li>
<li class="chapter" data-level="11.1.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#multiple-regression-model-for-the-ice-cream-and-drownings-example"><i class="fa fa-check"></i><b>11.1.2</b> Multiple regression model for the ice cream and drownings example</a></li>
<li class="chapter" data-level="11.1.3" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prior-predictive-check"><i class="fa fa-check"></i><b>11.1.3</b> Prior predictive check</a></li>
<li class="chapter" data-level="11.1.4" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#fitting-the-multiple-regression-model"><i class="fa fa-check"></i><b>11.1.4</b> Fitting the multiple regression model</a></li>
<li class="chapter" data-level="11.1.5" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prediction-plots-for-multiple-regression-models"><i class="fa fa-check"></i><b>11.1.5</b> Prediction plots for multiple regression models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#dag-informed-predictors-categorical-variables-what-multiple-regression-is-doing-with-predictor-residual-plot"><i class="fa fa-check"></i><b>11.2</b> DAG-informed predictors, categorical variables, what multiple regression is doing with predictor residual plot</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="interaction-effects.html"><a href="interaction-effects.html"><i class="fa fa-check"></i><b>12</b> Interaction effects</a></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized linear models</a></li>
<li class="chapter" data-level="14" data-path="multilevel-models.html"><a href="multilevel-models.html"><i class="fa fa-check"></i><b>14</b> Multilevel models</a></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html"><i class="fa fa-check"></i><b>A</b> Estimation with frequentist inference</a>
<ul>
<li class="chapter" data-level="A.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#frequentist-estimates-are-point-estimates"><i class="fa fa-check"></i><b>A.1</b> Frequentist estimates are point estimates</a></li>
<li class="chapter" data-level="A.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions"><i class="fa fa-check"></i><b>A.2</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-are-centered-on-the-true-parameter-value"><i class="fa fa-check"></i><b>A.2.1</b> Sampling distributions are centered on the true parameter value</a></li>
<li class="chapter" data-level="A.2.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-allow-us-to-estimate-precision"><i class="fa fa-check"></i><b>A.2.2</b> Sampling distributions allow us to estimate precision</a></li>
<li class="chapter" data-level="A.2.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sample-size-affects-the-shape-of-sampling-distributions"><i class="fa fa-check"></i><b>A.2.3</b> Sample size affects the shape of sampling distributions</a></li>
<li class="chapter" data-level="A.2.4" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#summary-points-on-sampling-distributions"><i class="fa fa-check"></i><b>A.2.4</b> Summary points on sampling distributions</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#quantifying-uncertainty-standard-error-and-confidence-intervals"><i class="fa fa-check"></i><b>A.3</b> Quantifying uncertainty: standard error and confidence intervals</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#standard-error"><i class="fa fa-check"></i><b>A.3.1</b> Standard error</a></li>
<li class="chapter" data-level="A.3.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#confidence-intervals"><i class="fa fa-check"></i><b>A.3.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="A.3.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#the-standard-normal-approximation-does-not-work-well-under-low-sample-size"><i class="fa fa-check"></i><b>A.3.3</b> The standard normal approximation does not work well under low sample size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html"><i class="fa fa-check"></i><b>B</b> Decision-making with frequentist estimates</a>
<ul>
<li class="chapter" data-level="B.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#framework-of-classical-hypothesis-testing"><i class="fa fa-check"></i><b>B.1</b> Framework of classical hypothesis testing</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#state-null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>B.1.1</b> State null and alternative hypotheses</a></li>
<li class="chapter" data-level="B.1.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#assume-the-null-hypothesis-is-true"><i class="fa fa-check"></i><b>B.1.2</b> Assume the null hypothesis is true</a></li>
<li class="chapter" data-level="B.1.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#quantify-the-likelihood-of-the-data-under-the-null-hypothesis-p-values"><i class="fa fa-check"></i><b>B.1.3</b> Quantify the likelihood of the data under the null hypothesis: P-values</a></li>
<li class="chapter" data-level="B.1.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-a-decision-based-on-the-p-value-and-significance-value"><i class="fa fa-check"></i><b>B.1.4</b> Making a decision based on the P-value and significance value</a></li>
<li class="chapter" data-level="B.1.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#decision-errors-happen"><i class="fa fa-check"></i><b>B.1.5</b> Decision errors happen</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-decisions-with-confidence-intervals"><i class="fa fa-check"></i><b>B.2</b> Making decisions with confidence intervals</a></li>
<li class="chapter" data-level="B.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#issues-with-the-null-hypothesis-framework"><i class="fa fa-check"></i><b>B.3</b> Issues with the null hypothesis framework</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#significance-testing-reinforces-binary-thinking"><i class="fa fa-check"></i><b>B.3.1</b> Significance testing reinforces binary thinking</a></li>
<li class="chapter" data-level="B.3.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-testing-reinforces-gamification-in-science"><i class="fa fa-check"></i><b>B.3.2</b> Statistical testing reinforces gamification in science</a></li>
<li class="chapter" data-level="B.3.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-significance-is-not-the-same-thing-as-practical-significance"><i class="fa fa-check"></i><b>B.3.3</b> Statistical significance is not the same thing as practical significance</a></li>
<li class="chapter" data-level="B.3.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#type-i-errors-become-more-likely-with-multiple-tests"><i class="fa fa-check"></i><b>B.3.4</b> Type I errors become more likely with multiple tests</a></li>
<li class="chapter" data-level="B.3.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-is-almost-certainly-wrong"><i class="fa fa-check"></i><b>B.3.5</b> The null hypothesis is almost certainly wrong</a></li>
<li class="chapter" data-level="B.3.6" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-focuses-on-data-you-did-not-observe"><i class="fa fa-check"></i><b>B.3.6</b> The null hypothesis focuses on data you did not observe</a></li>
<li class="chapter" data-level="B.3.7" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#a-single-null-and-alternative-hypothesis-is-too-constraining"><i class="fa fa-check"></i><b>B.3.7</b> A single null and alternative hypothesis is too constraining</a></li>
<li class="chapter" data-level="B.3.8" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-p-value-is-not-the-probability-we-want"><i class="fa fa-check"></i><b>B.3.8</b> The P-value is not the probability we want</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Research Design and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bayesian-estimation-and-inference" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Bayesian estimation and inference<a href="bayesian-estimation-and-inference.html#bayesian-estimation-and-inference" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>With some basic probability rules under our belt, we turn our attention
to the fundamental problem posed in the last chapter. Recall our goal
was to estimate the prevalence of a disease in a community of 10,000.
We’re particularly interested in knowing if the prevalence is greater
than 10%, because that’s the threshold for triggering public health
interventions. The population is too big to test everyone, and so a
sample of 15 people were selected for testing, one of which tested
positive, producing a frequentist estimate of _{infected} =
0.067. How good is this estimate, and how likely is it that the
prevalence of the disease is truly less than 10%? This question implies
that even though only 6.7% of the people I sampled were infected, it’s
still possible that more than 10% of the population is infected. And
this of course is the fundamental problem of statistics: when I sample
populations, the quantities I want to know are estimated and uncertain.
In this chapter, we look directly at how we can use samples to estimate
a quantity <em>and</em> represent our uncertainty about that quantity with the
language of probability.</p>
<div id="scientific-workflow-for-the-problem" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Scientific workflow for the problem<a href="bayesian-estimation-and-inference.html#scientific-workflow-for-the-problem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In Chapter 2 I introduced a general workflow outlining how we will
tackle scientific research questions, specifically how we will use the
data we collect to provide insight into the questions we propose. Let’s
remind ourselves of the steps of that workflow.</p>
<div id="theory-and-the-research-question" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Theory and the research question<a href="bayesian-estimation-and-inference.html#theory-and-the-research-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our research question is “What proportion of people in the community are
infected with a virus?” Although this question is descriptive in nature,
there’s certainly theory from the fields of infectious disease and
epidemiology that informs our understanding of how viral infection
occurs, how it’s transmitted among people, and the approaches we can use
to reliably test for infection. That theory is especially important for
informing our causal assumptions about how the data are generated.</p>
</div>
<div id="generative-model-and-estimand" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Generative model and estimand<a href="bayesian-estimation-and-inference.html#generative-model-and-estimand" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A generative model describe how the data we observe are produced given
our study design, and the estimand is the quantity or quantities we want
to know. Having a simple descriptive research question, we can identify
the estimand as the proportion of people infected with the virus. We’ve
randomly sampled 15 people to test for the infection, which we would
like to use to estimate the proportion infected. The generative model
describes how the test results for samples of 15 people are produced. In
other words, what are we assuming about the data generation process?</p>
<p>At this point we begin with a simple generative model, which I describe
here as three assumptions:</p>
<ul>
<li><p>We assume that we sample individuals randomly from the population
and that the probability of each individual being infected is
identical to the proportion of people infected in the population.
This is likely a good assumption if the sampling is truly random. It
wouldn’t be true if we sampled people who differed in some way from
unsampled people in terms of disease risk. For example, if we relied
on volunteers for testing, perhaps individuals who are vaccinated -
being health consciousness - are more likely to participate in
screening than individuals who are not vaccinated. But for now we
assume truly random sampling.</p></li>
<li><p>We assume the test results are perfectly accurate. In other words,
when someone is infected with the virus, we assume the probability
they will test positive is 1:
<span class="math inline">\(P(\text{positive result} | \text{infected} = 1)\)</span>. Similarly, when
someone is not infected with the virus, we assume the probability
that they will test negative is 1:
<span class="math inline">\(P(\text{negative result} | \text{not infected} = 1)\)</span>.</p></li>
<li><p>We assume the test results for each individual are <em>independent</em>.
That means the test result of one person sampled are causally
unrelated to a test result of another person sampled.</p></li>
</ul>
<div id="simulating-synthetic-data-with-a-generative-model" class="section level4 hasAnchor" number="7.1.2.1">
<h4><span class="header-section-number">7.1.2.1</span> Simulating synthetic data with a generative model<a href="bayesian-estimation-and-inference.html#simulating-synthetic-data-with-a-generative-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The neat thing about generative model is that we can use them to
generate synthetic data. The process of generating synthetic data is
called <strong>simulation</strong>. In this section I want to show you two ways you
could simulate data from our generative model on test results for a
viral infection.</p>
<p>First, the <code>sample</code> function provides a simple mechanism that can be
used to generate sample data based on particular assumptions. With this
function we can define the possible outcomes of the data (<code>pos</code> =
positive test, <code>neg</code> = negative test), the number of people we sample
for testing (<code>N</code>), and the probability of observing each outcome. In the
code below, we define <code>p</code> as the proportion of people infected, and
therefore according to our generative model, this is the probability of
seeing a positive test. If the test is not positive, it must be negative
(<code>neg</code>). We can generate data under any values of the parameters in the
model, and here I’ve assumed a sample of 15 people from a population
where 8% are infected:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="bayesian-estimation-and-inference.html#cb191-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb191-2"><a href="bayesian-estimation-and-inference.html#cb191-2" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">15</span>    <span class="co">#assumed sample size</span></span>
<span id="cb191-3"><a href="bayesian-estimation-and-inference.html#cb191-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.08</span>  <span class="co">#assumed proportion of population infected</span></span>
<span id="cb191-4"><a href="bayesian-estimation-and-inference.html#cb191-4" tabindex="-1"></a><span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>), <span class="at">size =</span> N, <span class="at">prob =</span> <span class="fu">c</span>(p, <span class="dv">1</span><span class="sc">-</span>p), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot;
## [13] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;</code></pre>
<p>We see that R returns a single set of 15 test results according to the
model, two being positive and thirteen being negative. So in this one
synthetic dataset, the proportion infected is 2/13 = 13.3%, which is
different from the true (assumed) proportion infected of 8%. This
difference is due to sampling error. We could simulate datasets like
this over and over to get a sense for the variation in the outcome due
to sampling error. Here I use the <code>replicate</code> function to simulate 1000
datasets with <code>N</code> = 15 and <code>p</code> = 0.08:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="bayesian-estimation-and-inference.html#cb193-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb193-2"><a href="bayesian-estimation-and-inference.html#cb193-2" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">15</span>    <span class="co">#assumed sample size</span></span>
<span id="cb193-3"><a href="bayesian-estimation-and-inference.html#cb193-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.08</span>  <span class="co">#assumed proportion of population infected</span></span>
<span id="cb193-4"><a href="bayesian-estimation-and-inference.html#cb193-4" tabindex="-1"></a>sims <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">1000</span>, </span>
<span id="cb193-5"><a href="bayesian-estimation-and-inference.html#cb193-5" tabindex="-1"></a>                  <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;pos&quot;</span>, <span class="st">&quot;neg&quot;</span>), <span class="at">size =</span> N, </span>
<span id="cb193-6"><a href="bayesian-estimation-and-inference.html#cb193-6" tabindex="-1"></a>                         <span class="at">prob =</span> <span class="fu">c</span>(p, <span class="dv">1</span><span class="sc">-</span>p), <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb193-7"><a href="bayesian-estimation-and-inference.html#cb193-7" tabindex="-1"></a>sims[,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#print the first 10 samples of 15</span></span></code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
##  [1,] &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [2,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [3,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [4,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot;
##  [5,] &quot;pos&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [6,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;pos&quot; &quot;neg&quot;
##  [7,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [8,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
##  [9,] &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot;
## [10,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
## [11,] &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
## [12,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
## [13,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot;
## [14,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;
## [15,] &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot;</code></pre>
<p>I’ve printed the first 10 simulated datasets, with columns representing
the simulation and rows repersenting the 15 outcomes in each simulation.
We can see the first simulation has two positives, the second has one
positive, the third has 0 positives, and so on. Let’s compute the
frequency distribution of the number of positives across all 1000
simulated datasets:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="bayesian-estimation-and-inference.html#cb195-1" tabindex="-1"></a>positives <span class="ot">&lt;-</span> <span class="fu">colSums</span>(sims <span class="sc">==</span> <span class="st">&quot;pos&quot;</span>)</span>
<span id="cb195-2"><a href="bayesian-estimation-and-inference.html#cb195-2" tabindex="-1"></a><span class="fu">table</span>(positives) <span class="co">#frequency table</span></span></code></pre></div>
<pre><code>## positives
##   0   1   2   3   4   6 
## 314 368 214  89  13   2</code></pre>
<p>We see the most common outcomes are 0, 1, or 2 positives out of 15 when
the true proportion infected is 0.08, with the probability of an
increasing number of positives declining sharply as shown in the graph
above. This makes sense given that we assumed the proportion infected in
the population was only 8%. The figure below shows the distribution of
outcomes across 1000 synthetic datasets when we assume a much larger
prevalence of 30%. When the prevalence is 30%, it’s most likely to see
three to six positives out of 15, more than what we expect when the
prevalence is only 8%, but still quite variable due to sampling error.</p>
<p>A second way we can simulate data - and this will be the approach we use
throughout the book - is to use probability distributions. This is one
of the reasons we spent an entire chapter working with probability rules
and distributions. Recall in the last chapter that we described the
number of positives <em>X</em> out of out of <em>n</em> trials as a random variable
following a binomial distribution. The binomial distribution makes the
same assumptions that we articulated in our generative model, namely a
constant probability of infection (implying random sampling and a
perfectly accurate test) and independent observations. Indeed, we used
the binomial distributiont o compute the probability of observing any
number of positive tests out of 15, in that case when we assumed a
prevalence of 5%. The graph below shows the binomial distribution of
positive test results out of 15 when the prevalence is 8%:</p>
<p><img src="ch07_estimation_files/figure-html/c07_chunk07-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>We can also use the binomial distribution to <em>simulate</em> data. This can
be done with the <code>rbinom</code> function. Here I use the <code>rbinom</code> function to
simulate a single sample (<code>n = 1</code>) of 15 individuals <code>size = 15</code> where
the probabability of success (infection) is 0.08:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="bayesian-estimation-and-inference.html#cb197-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb197-2"><a href="bayesian-estimation-and-inference.html#cb197-2" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> <span class="fl">0.08</span>)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>The <code>rbinom</code> function returns the total number of “successes” (<em>X</em>),
which we define as positive test results, out of the 15. Just like the
<code>sample</code> function, we can simulate many datasets. The code below
produces 10 datasets of size 15:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="bayesian-estimation-and-inference.html#cb199-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb199-2"><a href="bayesian-estimation-and-inference.html#cb199-2" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> <span class="fl">0.08</span>)</span></code></pre></div>
<pre><code>##  [1] 1 2 1 2 3 0 1 3 1 1</code></pre>
<p>We could of course do this 1000 times just like we did with the <code>sample</code>
function and compute the frequency distribution of the number of
positive results out of 15:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="bayesian-estimation-and-inference.html#cb201-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb201-2"><a href="bayesian-estimation-and-inference.html#cb201-2" tabindex="-1"></a>sims <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> <span class="fl">0.08</span>)</span>
<span id="cb201-3"><a href="bayesian-estimation-and-inference.html#cb201-3" tabindex="-1"></a><span class="fu">table</span>(sims)</span></code></pre></div>
<pre><code>## sims
##   0   1   2   3   4   5   6 
## 286 376 228  84  24   1   1</code></pre>
<p>We see a very similar distribution of positive results in comparison to
the <code>sample</code> function, which makes sense because the assumptions we made
in the <code>sample</code> function were the assumptions of the binomial
distribution. One of the nice things about using the probability
distribution directly, however, is that it gives us the <em>exact</em>
probability of each possible outcome given our assumptions.</p>
<p>The last thing I want to show you is that a generative model can give
you insight into the quality of the data you can expect from your
sampling design, specifically accuracy and precision. For example,
assume the true prevalence is 8%, but we’re considering how many tests
we should invest in to estimate the proportion infected. We can use the
binomial distribution - our generative model - to look at how the
sampling distribution changes with sample size. For example, suppose we
want to evaluate the implications of sampling 15, 50, or 150 people. The
figure below shows the probability of observing a particular proportion
of positive test results based on each sample size:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="bayesian-estimation-and-inference.html#cb203-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4</span>)</span>
<span id="cb203-2"><a href="bayesian-estimation-and-inference.html#cb203-2" tabindex="-1"></a></span>
<span id="cb203-3"><a href="bayesian-estimation-and-inference.html#cb203-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fl">0.08</span></span>
<span id="cb203-4"><a href="bayesian-estimation-and-inference.html#cb203-4" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">50</span>, <span class="dv">150</span>)</span>
<span id="cb203-5"><a href="bayesian-estimation-and-inference.html#cb203-5" tabindex="-1"></a></span>
<span id="cb203-6"><a href="bayesian-estimation-and-inference.html#cb203-6" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(ns, <span class="cf">function</span>(n){</span>
<span id="cb203-7"><a href="bayesian-estimation-and-inference.html#cb203-7" tabindex="-1"></a>  k <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span>n</span>
<span id="cb203-8"><a href="bayesian-estimation-and-inference.html#cb203-8" tabindex="-1"></a>  phat <span class="ot">&lt;-</span> k <span class="sc">/</span> n</span>
<span id="cb203-9"><a href="bayesian-estimation-and-inference.html#cb203-9" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb203-10"><a href="bayesian-estimation-and-inference.html#cb203-10" tabindex="-1"></a>    <span class="at">n    =</span> <span class="fu">factor</span>(n, <span class="at">levels =</span> ns),</span>
<span id="cb203-11"><a href="bayesian-estimation-and-inference.html#cb203-11" tabindex="-1"></a>    <span class="at">phat =</span> phat,</span>
<span id="cb203-12"><a href="bayesian-estimation-and-inference.html#cb203-12" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">dbinom</span>(k, <span class="at">size =</span> n, <span class="at">prob =</span> p),</span>
<span id="cb203-13"><a href="bayesian-estimation-and-inference.html#cb203-13" tabindex="-1"></a>    <span class="at">xmin =</span> <span class="fu">pmax</span>(<span class="dv">0</span>, phat <span class="sc">-</span> <span class="fl">0.5</span><span class="sc">/</span>n),</span>
<span id="cb203-14"><a href="bayesian-estimation-and-inference.html#cb203-14" tabindex="-1"></a>    <span class="at">xmax =</span> <span class="fu">pmin</span>(<span class="dv">1</span>, phat <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">/</span>n)</span>
<span id="cb203-15"><a href="bayesian-estimation-and-inference.html#cb203-15" tabindex="-1"></a>  )</span>
<span id="cb203-16"><a href="bayesian-estimation-and-inference.html#cb203-16" tabindex="-1"></a>}))</span>
<span id="cb203-17"><a href="bayesian-estimation-and-inference.html#cb203-17" tabindex="-1"></a></span>
<span id="cb203-18"><a href="bayesian-estimation-and-inference.html#cb203-18" tabindex="-1"></a><span class="fu">ggplot</span>(d) <span class="sc">+</span></span>
<span id="cb203-19"><a href="bayesian-estimation-and-inference.html#cb203-19" tabindex="-1"></a>  <span class="fu">geom_rect</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> xmin, <span class="at">xmax =</span> xmax, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> prob),</span>
<span id="cb203-20"><a href="bayesian-estimation-and-inference.html#cb203-20" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb203-21"><a href="bayesian-estimation-and-inference.html#cb203-21" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> n, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span></span>
<span id="cb203-22"><a href="bayesian-estimation-and-inference.html#cb203-22" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb203-23"><a href="bayesian-estimation-and-inference.html#cb203-23" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb203-24"><a href="bayesian-estimation-and-inference.html#cb203-24" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb203-25"><a href="bayesian-estimation-and-inference.html#cb203-25" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Observed proportion positive (p-hat = k/n)&quot;</span>,</span>
<span id="cb203-26"><a href="bayesian-estimation-and-inference.html#cb203-26" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Probability&quot;</span></span>
<span id="cb203-27"><a href="bayesian-estimation-and-inference.html#cb203-27" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb203-28"><a href="bayesian-estimation-and-inference.html#cb203-28" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="ch07_estimation_files/figure-html/c07_chunk11-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>You can see that as the number of individuals samples increases, the
width of the sampling distribution decreases, meaning you can expect
more precise estimates with larger sample sizes. Note that in each
scenario, you can get an estimated prevalence of &gt;10% even though the
true prevalence is 5%, but the likelhood of that results decreases as
sample size increases. Also note that sample size has no effect on
accuracy, as each of the distributions is centered on the true
prevalence that we assumed: 8%.</p>
</div>
</div>
<div id="statistical-model-and-estimate" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Statistical model and estimate<a href="bayesian-estimation-and-inference.html#statistical-model-and-estimate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Whereas the generative model expresses our causal assumptions about how
the data are estimated and can be used produce simulated datasets, the
statistical model is what we use to <em>estimate</em> what we want to know in
the target population. The statistical model needs to take the 15 test
results we actually observe and use them to estimate the proportion
infected in the population of 10,000. Remember we observed one person
out of 15 tested positive, so you might be tempted to say that the
estimate of the prevalence is simply
<span class="math inline">\(\hat{p}_{infected} = \frac{1}{15}= 0.067\)</span>. And if you were strictly
using a frequentist definition of probability, you would be correct.
Frequentist estimates are <strong>point estimates</strong>, a single best estimate
for the quantity we’re interested in. One problem with frequentist point
estimates is that we can’t talk about them probabalitically. In other
words, we can’t answer the question “What is the probability that the
true prevalence of the infection in the population is 6.7%”. Nor can we
talk about the probability of the prevalence taking on any other values.
Remember that our main goal is to determine if the prevalence of the
infection is above 10%, becuase that’s when interventions are triggered.
In other words, we want to know “What is the probability that the
infection prevalence is &gt;10%?”. Frequentist point estimates can’t
answer that question, but fortunately there is a solution, and that
solution is to use a Bayesian interpretation of probabiglity. So in the
remainder of this chapter, I will introduce you to Bayesian probability,
and then show you how we can use Bayes to estimate quantities with
statistical models.</p>
</div>
</div>
<div id="bayes-theorem" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Bayes Theorem<a href="bayesian-estimation-and-inference.html#bayes-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Step away from disease prevalence for a moment and consider medical
screening tests. Medical screening tests are used to identify health
issues in people before symptoms are present. In the 1980s the American
Cancer Society started recommending annual or semi-annual mammograms for
women beginning in middle age to look for breast cancer. In contrast to
our toy example that assumes a perfect test for a viral infection, most
medical testing is imperfect. There is some chance an individual will
test negative when they truly have a disease (<strong>false negative</strong>), and
there is some chance that an individual will test positive when they
don’t have a disease (<strong>false positive</strong>).</p>
<p>Table @ref(tab:c07_t1) shows the joint and marginal probabilities for
mammogram screening tests (<a href="https://pubs.rsna.org/doi/10.1148/radiol.2016161174">Lehman et al.
2016</a>). The joint
probabilities are shown for test results (positive and negative) and
disease status (does or does not have breast cancer). For example, we
can see that 0.87% of individuals have breast cancer and test positive.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:c07_t1)Joint and marginal probabilities for mammogram screening tests
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease Status
</th>
<th style="text-align:right;">
Positive Test
</th>
<th style="text-align:right;">
Negative Test
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Breast Cancer
</td>
<td style="text-align:right;">
0.0087
</td>
<td style="text-align:right;">
0.0013
</td>
<td style="text-align:right;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
No Breast Cancer
</td>
<td style="text-align:right;">
0.1089
</td>
<td style="text-align:right;">
0.8811
</td>
<td style="text-align:right;">
0.99
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
0.1176
</td>
<td style="text-align:right;">
0.8824
</td>
<td style="text-align:right;">
1.00
</td>
</tr>
</tbody>
</table>
<p>How well does the test perform? From the joint probabilities in Table
@ref(tab:c07_t1), we can quantify the probability of test outcomes
conditional on disease status. For example, what is the probability the
test will be positive when a person has the disease? This probability is
known as the <strong>sensitivity</strong> of a test in medical research. We know from
the rule of conditional probability that the sensitivity can be
quantified as</p>
<p><span class="math display">\[
P(\text{Positive}|\text{Cancer}) = \frac{P(\text{Positive and Cancer})}{P(\text{Cancer})}
\]</span></p>
<p>We can see in Table @ref(tab:c07_t1) that the joint probability of
testing positive and having breast cancer is 0.0087, and the marginal
probability of breast cancer is 0.01. Thus, the sensitivity of the test
is</p>
<p><span class="math display">\[
P(\text{Positive}|\text{Cancer}) = \frac{0.0087}{0.01}=0.87
\]</span></p>
<p>In other words, when someone has breast cancer, they have a 0.87
probability of testing positive in a screening mammogram. This means
they have a 0.13 probability of testing negative, so 0.13 is the false
negative rate for the test.</p>
<p>How well does the test return a negative result when an individual
doesn’t have breast cancer, an outcome referred to as <strong>specificity</strong> in
medical research. Again, we can specify the conditional probability of
interest as:</p>
<p><span class="math display">\[
P(\text{Negative}|\text{No Cancer}) = \frac{P(\text{ Negative and No Cancer})}{P(\text{No Cancer})} = \frac{0.8811}{0.99}=0.89
\]</span></p>
<p>We see the specificity is 0.89, meaning the probability of a false
positive is 0.11.</p>
<p>Now as you might surmise, medical doctors are faced with a conundrum
when interpreting the results of these kind of screening tests. Clearly
we can see from the estimation of sensitivity and specificity that the
screening test is imperfect. Sometimes it returns a positive for people
who don’t have breast cancer, and sometimes it returns a negative for
people who do have breast cancer. Doctors are well aware of this. Before
approving medical tests for general use, regulatory agencies evaluate
the performance of tests as measured by sensitivity and specificity
(along with potential side effects), so these values are known by
practitioners. The question we need to grapple with is how doctors
should interpret the resutls of an imperfect screening test. What does a
test result imply about the probability of actually having the disease?</p>
<p>When a routine mammography is performed on an individual, what
information is known about that person with respect to the likelihood of
having breast cancer? For screening tests on individuals without a
family history of breast cancer, there is very little information to go
on. In such cases, the probability of the individual having breast
cancer might be estimated best by the prevalence of breast cancer among
individuals who are screened. As we can see in Table @ref(tab:c07_t1),
that’s the marginal probability of breast cancer which is 1%. In a
Bayesian analysis, this marginal probability of breast cancer is the
<strong>prior probability</strong>, namely the probability of the event of interest
(having breast cancer) before we collect new data.</p>
<p>How does the probability of having breast cancer change when we learn
new information, specifically the result of the mammography? Suppose a
person has a positive test. What is the probability this person has
breast cancer, given that they have a positive mammogrpahy? Some people
would be tempted to say the probabilty is 87%, but that isn’t right. The
probability 87% represented the probability of testing positive <em>given</em>
a person has breast cancer. What we want is the reverse conditionality.
What is the probability of having breast cancer, <em>given</em> the positive
test result?</p>
<p>This is where Bayesian thinking becomes valuable. Thomas Bayes
discovered that a conditional probability could be quantified (in part)
from the <em>reverse</em> conditional probability. Consider the conditional
probability of interest, which we can frame using our standard rule to
quantify conditional probability:</p>
<p><span class="math display">\[
P(\text{Cancer}|\text{Positive Test}) = \frac{P(\text{Cancer and Positive Test})}{P(\text{Positive Test})}
\]</span></p>
<p>Notice that the numerator is a joint probability. We know from the
general multiplication rule that the joint probability of A and B is
<span class="math inline">\(P(A|B)*P(B)\)</span>, which can be equivalently expressed as <span class="math inline">\(P(B|A)*P(A)\)</span>.
Bayes showed this rearrangement and expressed the conditional
probability in the following way, which is known as <strong>Bayes Theorem</strong>:</p>
<p><span class="math display">\[
P(\text{A}|\text{B}) = \frac{P(\text{B|A})*P(\text{A})}{P(\text{B})}
\]</span></p>
<p>Applying Bayes Theorem to the breast cancer example, the probability of
breast cancer given a positive test becomes:</p>
<p><span class="math display">\[
P(\text{Cancer}|\text{Positive Test}) = \frac{P(\text{Positive Test|Cancer})*P(\text{Cancer})}{P(\text{Positive Test})}
\]</span></p>
<p>All we have done here is re-expressed the joint probability of breast
cancer and positive test result as the sensitivity of the test
(probability of true positive) and the prevalence of the disease. This
is an important insight because those probabilities are generally more
intuitive than joint probabilities (the probability of randomly
selecting an individual who jointly has breast cancer and tests
positive).</p>
<p>Given this conceptual background on Bayes Theorem, let’s now compute the
probability that the medical wants to know, namely the probability of
having breast cancer given a positive test result:</p>
<p><span class="math display">\[
P(\text{Cancer}|\text{Positive Test}) = \frac{P(\text{Positive Test|Cancer})*P(\text{Cancer})}{P(\text{Positive Test})}=\frac{0.87*0.01}{0.1176}=0.074
\]</span></p>
<p>To most people this is a surprising result! In the case of a standard
screening test for breast cancer, the probability of actually having
breast cancer given a positive test is only 7.4%. Let’s be clear about
the logic logic of our approach. First, before we had any new
information from the mammogram, we stated the <em>prior probability</em> of an
individual having breast cancer is 1%. That’s simply the prevalence of
the disease among those who are being screened for breast cancer.
Bayesian inference takes that prior knowledge and updates it with new
information, namely the result of the test. Given the new information of
a positive test, the updated probability of breast cancer increases to
7.4%. This updated probability, conditional on the new data, is called
the <strong>posterior probability</strong>. This is the essence of Bayesian
inference: start with your prior knowledge expressed as a prior
probability, and update it based on new data.</p>
<p>Why is the probability of breast cancer conditional on a positive test
so low? Bayes Theorem makes this clear. Although the sensitivity and
specificity of mammograms are quite high, the mammogram is not a perfect
test. Some of the positive tests are true positives, and some are false
positives. What Bayes Theorem shows us is that we have to take into
consideration the facts that 1) the prevalence of breast cancer is
relatively low at 1%, and 2) only a portion of the positive test results
are true positives. The numerator of Bayes Theorem gives us the
proportion of individuals with breast cancer and positive tests, and
then we divide by the total probability of positive tests to arrive at
the proportion of positive tests that are true cases of breast cancer.
More intuitively, Bayes Theorem tells us that because the prevalence of
breast cancer is low and the mammogram produces false positives, the
vast majority of the positive test results are actually coming from
people who don’t have breast cancer.</p>
<p>This particular application of Bayes Theorem demonstrates how a low base
rate - or prevalence - of a disease significantly influences the
conditional probability of having the disease based on a test result.
Even when sensitivity is high, low prevalence of the disease means that
positive tests from screening programs are mostly false positives. This
is known in the medical literature as the <strong>base rate fallacy</strong>, in
which practitioners mistakenly believe high sensitivity implies high
likelihood of a disease for a positive test.</p>
<p>A critical assumption in the example to this point is that we don’t know
anything about the person being tested with respect to their likelihood
of having the disease. That’s why the prevalence of the disease was used
as the prior knowledge, which implies that individuals were being tested
at random. Had the test been motivated by particular symptoms, we would
want to revise the prior probability to reflect that knowledge.</p>
<p>For example, imagine a patient has symptoms that raises the suspicion of
breast cancer to 50%. We can easily update our computation based on this
information. If the probability of breast cancer for this individual
(prior to testing) is 50%, then the probability of not having breast
cancer is also 50%, and the total probability of a positive test is</p>
<p><span class="math display">\[
\begin{aligned}P(\text{Positive}) &amp;= P(\text{Positive}\mid \text{Cancer})\,P(\text{Cancer})+ P(\text{Positive}\mid \text{No Cancer})\,P(\text{No Cancer}) \\P(\text{Positive}) &amp;= 0.87(0.5) + 0.11(0.5) = 0.435 + 0.055 = 0.49\end{aligned}
\]</span></p>
<p>Now we update our computation of the conditional probability of having
the disease based on a positive test:</p>
<p><span class="math display">\[
P(\text{Cancer}|\text{Positive Test}) = \frac{P(\text{Positive Test|Cancer})*P(\text{Cancer})}{P(\text{Positive Test})}=\frac{0.87*0.50}{0.49}=0.89
\]</span></p>
<p>We see, unsurprisingly, that when symptoms raised our suspicion of
breast cancer to a coin flip, the probability of breast cancer given a
positive test is now 89%. This dramatic change illustrates how prior
knowledge - expressed quantitatively as the prior probability - can have
a dramatic impact on how we interpret the results of new evidence.</p>
<p>Broadly speaking, the example above highlights how Bayesian inference
incorporates prior knowledge <em>and</em> new data to estimate quantities of
interest. Whether you are a doctor interpreting test results or a
scientist testing a hypothesis, Bayes Theorem allows us to specify our
initial assumptions based on prior knowledge and update our beliefs with
new empirical evidence.</p>
</div>
<div id="applying-bayes-theorem-to-statistical-analysis" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Applying Bayes Theorem to statistical analysis<a href="bayesian-estimation-and-inference.html#applying-bayes-theorem-to-statistical-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the context of statistical analysis, we can think about Bayesian
inference as allowing us to estimate quantities that represent a
scientific hypothesis by combining our prior knowledge about the
hypothesis with new data from a study:</p>
<p><span class="math display">\[
P(\text{Hypothesis}|\text{Data}) = \frac{P(\text{Data|Hypothesis})*P(\text{Hypothesis})}{P(\text{Data})}
\]</span></p>
<p>There are four key parts of Bayes Theorem being represented here:</p>
<ul>
<li><strong>Prior probability</strong>, <span class="math inline">\(P(Hypothesis)\)</span>: Quantitative statement of
your degree of belief about the hypothesis prior to collecting new
data.</li>
<li><strong>Likelihood</strong>, <span class="math inline">\(P(Data|Hypothesis)\)</span>: Probability of new data you
observe given that a hypothesis is true.</li>
<li><strong>Total probability of the data</strong>, <span class="math inline">\(P(Data)\)</span>: The overall
probability of the data integrated across all possible hypotheses.
This is quantified using the total law of probability, where P(Data)
represents a weighted average of the data, weighing the probability
the data in accordance to the prior probability of each possible
hypothesis. This is sometimes called the <strong>marginal likelihood</strong> (as
it is a marginal probability integrated across hypotheses) or the
<strong>average probability of the data</strong> (as it is a weighted average).
Sometimes it is simply called the <strong>evidence</strong>. We won’t dwell on
this component too much, as it more or less provides a mathematical
purpose for us of standardizing the posterior probability such that
it integrates to one.</li>
<li><strong>Posterior probability</strong>, <span class="math inline">\(P(Hypothesis | Data)\)</span>: This is our
updated probability of the hypothesis given the new data.</li>
</ul>
<p>This is fundamentally different than frequentist inference, where the
P-value for a single null hypothesis represents the probability of data
(or more extreme values) given the null hypothesis is true. We use that
information as part of hte likelihood, but critically, we combine the
likelihood with our prior (<span class="math inline">\(P(Hypothesis\)</span>)) to compute the conditional
probability that we are actually interested in, namely the posterior
probability of the hypothesis given the data.</p>
<p>Remember the whole point of science is to evaluate ideas with empirical
data. We’ve defined the estimand as the (unknown) quantity that we want
to estimate in the target population. It’s the quantity that will
provide insight into the research question. So rather than referring to
a verbal “Hypothesis” in Bayes theorem, instead we make it entirely
quantitative by representing different hypotheses as different values of
the <em>estimand</em>, which we denote <span class="math inline">\(\theta\)</span>. Making this substitution,
Bayes theorem can be stated as</p>
<p><span class="math display">\[
P(\theta|\text{Data}) = \frac{P(\text{Data}|\theta)*P(\theta)}{P(\text{Data})}
\]</span></p>
<p>For example, if we want to compare the difference in the mean number
of fish between polluted and unpolluted areas in a lake, then <span class="math inline">\(\theta\)</span>
could represent the difference between the means in polluted and
unpolluted areas, which could take on any real value. Bayes theorem
provides a method for leverating our prior knowledge and new data to
compute the probaiblity that the difference in the means takes on <em>any</em>
of those values. In other words, we can compute the posterior
probability that the difference in means takes on any value, such that
teh posterior probability is an entire distribution of parameter values.
In Bayesian inference we can use the posterior probability distribtion
to reason probabilistically about hypotheses comparing the probability
of parameter values that represent different hypotheses. For example, if
the estimand is the the difference in mean fish between polluted and
unpolluted areas computed as <span class="math inline">\(\mu_{unpolluted} - \mu_{polluted}\)</span>, we can
compare the probability that the difference is positive - values that
represent fish abundance being greater in unpolluted areas - to the
probability that the difference is negative - values that represent fish
abundance being greater in polluted areas.</p>
</div>
<div id="steps-of-estimation-with-bayesian-inference" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Steps of estimation with Bayesian inference<a href="bayesian-estimation-and-inference.html#steps-of-estimation-with-bayesian-inference" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the remainder of this chapter we will apply Bayesian inference to
estimate the prevalence of a viral infection when we randomly sample N =
15 people for testing. Before we take a look at each step of Bayesian
estimation, it is worth emphasizing that the estimates produced by
Bayesian inference are entire distributions. This is in stark contrast
to frequentist estimation, which produces a point estimate of the
parameter of interest. For example, recall that we found 1 positive
tests out of N = 15 randomly sampled individuals. The frequentist
estimate of the proportion infected is simply</p>
<p><span class="math display">\[
\hat{p}_{infected}=\frac{1}{15}=0.067
\]</span>We know that a proportion can take on any value continuously
distributed between (and inclusive of) 0 and 1, but frequentist
estimation effectively arrives at a single value. The output of a
Bayesian analysis is the posterior distribution, which is a probability
distribution for estimand. The posterior probability distribution <em>is</em>
the estimate in Bayesian inference, and because of this fact, we can
evaluate the probability of any value the parameter might take on. And
that’s exactly what we need! Remember how public health interventions
will be implemented if the prevalence of the disease is greater than
10%. Bayesian inference will let us compute the probability that the
prevalence is &gt;10%. Let’s take a look at the steps of Bayesian
estimation:</p>
<div id="specify-the-prior-distribution" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Specify the prior distribution<a href="bayesian-estimation-and-inference.html#specify-the-prior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first thing to do in a Bayesian analysis is to specify the prior
distribution for the parameters being estimated. In our example, we have
only a single parameter: the proportion of people infected. The goal
here is to represent our prior knowledge about the parameter values by
probability distributions. This can be a complicated task, and in this
book I will present only a surface level treatment of specifying prior
distributions. For now, we will start with the simplest possible prior
distribution, the <strong>uninformative prior</strong>.</p>
<p>Uninformative priors represent a situation where you no prior knowledge
about the parameters of interest. For parameters like proportions that
have a bounded range (between 0 and 1), the most common way of
specifying an uninformative prior is with the <strong>uniform distribution</strong>.
The uniform distribution simply says that the probability density of all
values X between values <em>a</em> and <em>b</em> are identical
(<span class="math inline">\(X\sim \text{Uniform}(a, b)\)</span>. Because we are working with a proportion,
we would say the prior probability of the proportion infected follows a
uniform distribution between 0 and 1:</p>
<p><span class="math display">\[
p_{infected}\sim \text{Uniform}(0, 1)
\]</span></p>
<p>In R we can compute the uniform distribution with the <code>dunif</code> function.
Before we do so, however, we need to select a set of parameter values at
which we will compute the prior distribution, and ultimately the
posterior distribution. The problem of course is that there’s an
infinite number of possible parameter values, even in cases like ours
where the parameter is bounded between a minimum and maximum. Because of
this, we proceed with an approximation of the prior and posterior
distributions by selecting a set of values that covers the plausible
range of the posterior distribution. This method is called <strong>grid
approximation</strong>. In this example, I will create a grid of possible
values for the proportion infected from 0 to 1 by every 0.01 units and
call it <code>p.grid</code>.</p>
<p>The resolution of the grid trades off completeness of the probability
distribution with computational efficiency. In other words, if the grid
is sparse (e.g., every 0.1 units), the computation is equite efficient,
but the resulting probability distributions will not be approximated
precisely. If the grid is too dense (e.g., every 0.0000001 units), the
probability distributions will be very precise but might take a long
time to compute. By specifying a resolution of 0.01 units, I’m trying to
balance precision with computational efficiency.</p>
<p>Once the grid of possible values of the parameter is created, the
<code>dunif</code> function is used to compute the prior probability distribution,
<code>p.prior</code>.</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f1-1.png" alt="Uniform prior distribution of the proportion infected." width="672" />
<p class="caption">
(#fig:c07_f1)Uniform prior distribution of the proportion infected.
</p>
</div>
<p>We see in Figure @ref(fig:c07_f1) that the prior probability
distribution for the prevalence is completely flat. Indeed, the uniform
prior is often called a <strong>flat prior</strong>. Because the the probability
density is identical at all values of the proportion infected, this
prior does a good job of representing our complete lack of prior
knowledge.</p>
</div>
<div id="quantify-the-likelihood-of-the-data" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Quantify the likelihood of the data<a href="bayesian-estimation-and-inference.html#quantify-the-likelihood-of-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once the prior distribution is specified, we can go ahead and compute
the likelihood, which is the probability of the data for each possible
value of the parameter. Recall that we observed 1 positive out of 15
tests. The likelihood is simply the probability of this specific
observation under different values of prevalence. Earlier we talked
about how we can compute these probabilities with the binomial
distribution, which makes the same assumptions as our generative model.
For example, what’s the probability of 1 out of 15 positive tests when
the prevalence of the infection is 0?</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="bayesian-estimation-and-inference.html#cb204-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>We see the probability of 1 out of 15 positives is 0 when the true
prevalence is 0. That makes sense! If the disease does not occur at all,
then no one should be infected. But that’s just one possible value of
the prevalence. Let’s take a look at the next possible value in the
grid, where the prevalence is 0.01:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="bayesian-estimation-and-inference.html#cb206-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> <span class="fl">0.01</span>)</span></code></pre></div>
<pre><code>## [1] 0.1303119</code></pre>
<p>So when the infection prevalence is 1%, there’s a 13% chance of
observing 1 out of 15 positives. Ultimately we need to go ahead and
compute these likelihoods for every value of prevalence in the grid. We
can do this by specifying our grid of values, <code>p.grid</code> as the <code>prob</code>
argument in the <code>dbinom</code> function, saving the output as <code>lik</code> in our
dataframe <code>d</code>.</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f2-1.png" alt="Likelihood distribution showing the probability of the observed data (1 out of 15 positive tests) conditional on each value of the prevalence of infection." width="672" />
<p class="caption">
(#fig:c07_f2)Likelihood distribution showing the probability of the observed data (1 out of 15 positive tests) conditional on each value of the prevalence of infection.
</p>
</div>
<p>Figure @ref(fig:c07_f2) shows the likelihood distribution. Each point in
the graph shows the likelihood of the observed data for each value of
proportion infected in the grid. We can clearly see that the observed
data are most likely when the proportion infected is around 0-25%. But
keep in mind that the likelihood is not the distribution we ultimately
want. These are the probabilities of the observed data conditional on
each value of the prevalence. What we really want is the posterior
probability of the prevalence conditional on the data. But before we can
compute that, we just need one more step.</p>
</div>
<div id="quantify-the-total-probability-of-the-data-marginal-likelihood" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Quantify the total probability of the data (marginal likelihood)<a href="bayesian-estimation-and-inference.html#quantify-the-total-probability-of-the-data-marginal-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The last step before computing the posterior distribution is to quantify
the marginal likelihood, which the total probability of the data. Using
the total law of probability, we need to take the product of the
likelihood (the probability of the observed data conditional on each
value of the prevalence) and the prior probability of each value of the
parameter, then sum those values up.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="bayesian-estimation-and-inference.html#cb208-1" tabindex="-1"></a>d<span class="sc">$</span>marg.lik <span class="ot">&lt;-</span> d<span class="sc">$</span>lik<span class="sc">*</span>d<span class="sc">$</span>prior</span></code></pre></div>
<p>Again, the marginal likelihood isn’t very interesting on its own. We
compute it so that we can standardize the posterior distribution, making
it integrate to 1.</p>
</div>
<div id="quantify-the-posterior-distribution" class="section level3 hasAnchor" number="7.4.4">
<h3><span class="header-section-number">7.4.4</span> Quantify the posterior distribution<a href="bayesian-estimation-and-inference.html#quantify-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally we are ready to compute the posterior probability distribution,
namely the probability of each possible value of the prevalence given
the data we observed. All we need to do here is apply Bayes Theorem:</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f3-1.png" alt="Posterior probability distribution for the infection prevalence conditional on the observed data (1 out of 15 positives)." width="672" />
<p class="caption">
(#fig:c07_f3)Posterior probability distribution for the infection prevalence conditional on the observed data (1 out of 15 positives).
</p>
</div>
<p>There we have it. Figure @ref(fig:c07_f3) shows the posterior
distribution of the infection prevalence. From the posterior
distribution we clearly see that some values of the proportion infected
are more likely than other. We will formally examine how we can describe
the posterior distribution in more detail shortly, but for now, consider
just to summaries. For example, what is the most plausible value for the
infection prevalence? We can extract the maximum value from the
posterior:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="bayesian-estimation-and-inference.html#cb209-1" tabindex="-1"></a><span class="co">#extract the max value of the posterior</span></span>
<span id="cb209-2"><a href="bayesian-estimation-and-inference.html#cb209-2" tabindex="-1"></a>d[<span class="fu">which.max</span>(d<span class="sc">$</span>posterior), ]</span></code></pre></div>
<pre><code>##   p.grid prior       lik  marg.lik  posterior
## 8   0.07     1 0.3801461 0.3801461 0.06094516</code></pre>
<p>The value of the parameter with the maximum posterior probability is
called the <strong>maximum a posteriori (MAP) value</strong>, and it is one of the
simplest values used to describe the posterior distribution with a
single point value. In this case, we see the MAP for the prevalence is
7% (<code>p.grid</code>). That happens to be the point estimate for the frequentist
estimate (rounded from 0.067 because of the finite nature of our grid),
but the symmetry here is only because we used a completely uninformative
prior. Indeed, in simple problems of estimation, the frequentist point
estimate and Bayesian MAP are often the same when using an uninformative
prior. But as we will soon see, there is rarely a reason to use a
completely uninformative prior.</p>
<p>Moreover, even when we use an uninformative prior, we can do so much
more with the Bayesian analysis compared to frequentist estimation.
Recall that our primary interest in estimating the prevalence of the
disease was to determine if the prevalence is greater than 10%, because
that’s the threshold where public health interventions would be
triggered. We saw with frequentist inference that we can’t easily
specify a null hypothesis that encompasses multiple values of the
parameter. But with Bayesian inference, we can quantify exactly what we
want. Let’s go ahead and compute the probability that the prevalence of
the infection is greater than 10%:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="bayesian-estimation-and-inference.html#cb211-1" tabindex="-1"></a><span class="fu">sum</span>(d<span class="sc">$</span>posterior[d<span class="sc">$</span>p.grid <span class="sc">&gt;</span> <span class="fl">0.1</span>])</span></code></pre></div>
<pre><code>## [1] 0.4885063</code></pre>
<p>Here we see that there’s a 48.9% chance that the prevalence is greater
than 10%. That of course means there’s a 51.1% chance that the
prevalence is 10% or less. In other words, based in our prior knowledge
and the new data we collected (the 15 test results), the it’s basically
a 50/50 coin flip on whether the prevalence is above the threshold for
triggering interventions. That is exactly the kind of information public
health officials would want to consider as part of their decision
making.</p>
<div id="using-a-more-informative-prior" class="section level4 hasAnchor" number="7.4.4.1">
<h4><span class="header-section-number">7.4.4.1</span> Using a more informative prior<a href="bayesian-estimation-and-inference.html#using-a-more-informative-prior" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now let’s approach the same estimation problem but with a more
informative prior. Suppose you had very good reason to believe that the
prevalence of the infection was no greater than 15%. For example,
perhaps you know the infection was very recently introduced to the area
from someone who recently returned from travel in another area where the
disease is common. Or perhaps you know from others areas that the
prevalence has never been observed to be above 15%. And suppose you also
know of at least one case in the population, such that the prevalence
can’t be 0.</p>
<p>We can go ahead and specify the prior as
<span class="math inline">\(p_{infected}\sim \text{Uniform}(0.001, 0.15)\)</span>, which says that all
values of the prevalence from 0.001 to 0.15 are equally likely, and that
all values outside of that range are impossible. Let’s create the grid
and visualize the prior:</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f4-1.png" alt="Uniform prior distribution of the proportion infected ruling out values above 15% prevalence." width="672" />
<p class="caption">
(#fig:c07_f4)Uniform prior distribution of the proportion infected ruling out values above 15% prevalence.
</p>
</div>
<p>Figure @ref(fig:c07_f4) shows the expected prior distribution, with
uniform probability from 0 to 0.15 and all other values being plausible.
Now we can combine this prior with the data and compute the posterior
distribution:</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f5-1.png" alt="Revised posterior probability distribution for the infection prevalence conditional on the observed data when using a uniform prior from 0 to 15%." width="672" />
<p class="caption">
(#fig:c07_f5)Revised posterior probability distribution for the infection prevalence conditional on the observed data when using a uniform prior from 0 to 15%.
</p>
</div>
<p>We see here a slight difference in the posterior distribution.
Graphically the most likely value still appears to be 0.07, but let’s
re-quantify the probabilty that the prevalence is greater than 10%:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="bayesian-estimation-and-inference.html#cb213-1" tabindex="-1"></a><span class="fu">sum</span>(d<span class="sc">$</span>posterior[d<span class="sc">$</span>p.grid <span class="sc">&gt;</span> <span class="fl">0.1</span>])</span></code></pre></div>
<pre><code>## [1] 0.302917</code></pre>
<p>Not surprisingly the posterior probability of the prevalence being
greater than 10% is now a bit lower at 30%, much lower than when we used
an uninformative prior. Thus, the shape of the prior probability
distribution - representing our prior knowledge of the system - can play
a very important role in shaping the estimate as expressed by the
posterior distribution.</p>
</div>
</div>
</div>
<div id="summarizing-the-posterior-distribution" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Summarizing the posterior distribution<a href="bayesian-estimation-and-inference.html#summarizing-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How should we summarize the posterior distributions? We have already
seen two approaches, specifically the MAP and an interval of probability
mass (<span class="math inline">\(p&gt;0.1\)</span>)). Because posterior distributions are simply probability
distributions, we can describe them with any of the tools we’ve used to
describe probability distributions. We can describe the central tendency
of the posterior by quantifying the mean, median, or mode (which is the
MAP), and we can describe variation by metrics that quantify the width
of the posterior distribution. The central tendency will give us a look
at the most likely values of the parameter given the data, whereas
variation will give us a sense of uncertainty. Wider posterior
distributions imply more uncertainty about the parameter value.</p>
<div id="sampling-from-the-posterior-distribution" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Sampling from the posterior distribution<a href="bayesian-estimation-and-inference.html#sampling-from-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>How do we quantify descriptive metrics of the posterior distribution,
such as the mean? Given the simplicity of the research problem in this
chapter, we could quantify the mean directly from the posterior by
weighing each value <em>i</em> of the prevalence from the grid by its posterior
probability (i.e, <span class="math inline">\(\sum p_{i}P(p_{i})\)</span>. But posterior distributions will
rarely be this simple, and so we need a more general approach.</p>
<p>The more general approach we’ll use to summarize posterior distributions
in the rest of the book is to take many samples from the posterior
distribution. For example, let’s take 1000 samples of the prevalence
values from the posterior distribution. For each draw from the
posterior, we will specify that the probability of a particular value of
the prevalence being selected is equal to its posterior probability.
This is much like drawing marbles from an urn. Imagine the marbles have
values of the prevalence printed on them. Some are 0.01, some 0.02,
0.03, etc. Based on the posterior distribution we’ve estimated, there
will be more marbles with 0.07 (which is the MAP) than 0.05, or 0.12, so
it’s more likely to select a marble with 0.07 than other values on each
particular draw.</p>
<p>Let’s use the <code>sample</code> function to draw 1000 values, and then plot a
histogram of the results:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="bayesian-estimation-and-inference.html#cb215-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb215-2"><a href="bayesian-estimation-and-inference.html#cb215-2" tabindex="-1"></a></span>
<span id="cb215-3"><a href="bayesian-estimation-and-inference.html#cb215-3" tabindex="-1"></a><span class="co">#extract 1000 samples from the posterior distribution</span></span>
<span id="cb215-4"><a href="bayesian-estimation-and-inference.html#cb215-4" tabindex="-1"></a>p.samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(d<span class="sc">$</span>p.grid, <span class="at">prob=</span>d<span class="sc">$</span>posterior, <span class="at">size=</span><span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb215-5"><a href="bayesian-estimation-and-inference.html#cb215-5" tabindex="-1"></a>p.samples <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(p.samples)</span>
<span id="cb215-6"><a href="bayesian-estimation-and-inference.html#cb215-6" tabindex="-1"></a></span>
<span id="cb215-7"><a href="bayesian-estimation-and-inference.html#cb215-7" tabindex="-1"></a><span class="fu">ggplot</span>(p.samples, <span class="fu">aes</span>(<span class="at">x =</span> p.samples)) <span class="sc">+</span></span>
<span id="cb215-8"><a href="bayesian-estimation-and-inference.html#cb215-8" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.01</span>, </span>
<span id="cb215-9"><a href="bayesian-estimation-and-inference.html#cb215-9" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb215-10"><a href="bayesian-estimation-and-inference.html#cb215-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb215-11"><a href="bayesian-estimation-and-inference.html#cb215-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb215-12"><a href="bayesian-estimation-and-inference.html#cb215-12" tabindex="-1"></a>                     <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . <span class="sc">*</span> <span class="fu">nrow</span>(p.samples) <span class="sc">*</span> <span class="fl">0.01</span>, <span class="at">name =</span> <span class="st">&quot;Frequency&quot;</span>)) <span class="sc">+</span></span>
<span id="cb215-13"><a href="bayesian-estimation-and-inference.html#cb215-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Infection prevalence&quot;</span>) <span class="sc">+</span></span>
<span id="cb215-14"><a href="bayesian-estimation-and-inference.html#cb215-14" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f6-1.png" alt="Histogram and overlaid probability density for 1000 sampled values of prevlaence from the posterior distribution." width="672" />
<p class="caption">
(#fig:c07_f6)Histogram and overlaid probability density for 1000 sampled values of prevlaence from the posterior distribution.
</p>
</div>
<p>We can see the most likely values of the prevalence among the sampled
values are 0.05-0.10, and no values below 0.01 or above 0.15 were
selected. This makes sense based on the posterior distribution, which
peaked at 0.07 and had very low probability at 0 and above 0.15. Now
that we have these samples, we can use them to easily quantify numeric
values summarizing the posterior distribution.</p>
</div>
<div id="central-tendency-and-variance" class="section level3 hasAnchor" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> Central tendency and variance<a href="bayesian-estimation-and-inference.html#central-tendency-and-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s start by computing the posterior mean and median:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="bayesian-estimation-and-inference.html#cb216-1" tabindex="-1"></a>p.samples <span class="ot">&lt;-</span> p.samples<span class="sc">$</span>p.samples</span>
<span id="cb216-2"><a href="bayesian-estimation-and-inference.html#cb216-2" tabindex="-1"></a></span>
<span id="cb216-3"><a href="bayesian-estimation-and-inference.html#cb216-3" tabindex="-1"></a><span class="fu">mean</span>(p.samples)</span></code></pre></div>
<pre><code>## [1] 0.08157</code></pre>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="bayesian-estimation-and-inference.html#cb218-1" tabindex="-1"></a><span class="fu">median</span>(p.samples)</span></code></pre></div>
<pre><code>## [1] 0.08</code></pre>
<p>The posterior mean is 8.2%, whereas the posterior median is 8%. These
aren’t too different, which isn’t surprising given that the bell shape
of the posterior distribution in this case.</p>
<p>In addition to metrics of central tendency, we can also quantify metrics
of spread, which sheds light on uncertainty. The most typical metric of
spread for the posterior distribution is the standard deviation:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="bayesian-estimation-and-inference.html#cb220-1" tabindex="-1"></a><span class="fu">sd</span>(p.samples)</span></code></pre></div>
<pre><code>## [1] 0.03877549</code></pre>
<p>The standard deviation of the posterior distribution reflects
uncertainty about the parameter in light of the prior and the data.
Bigger values of the standard deviation mean more spread in the
probability distribution across possible values of the estimand, which
means more uncertainty. Conversely, smaller values of the standard
deviation imply less uncertainty.</p>
</div>
<div id="intervals" class="section level3 hasAnchor" number="7.5.3">
<h3><span class="header-section-number">7.5.3</span> Intervals<a href="bayesian-estimation-and-inference.html#intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Although single values like the posterior mean or median can be helpful
(and are often reported in the literature), it can be helpful and more
informative identify an interval of plausible values for the the
parameter. Indeed, we’ve already seen one interval from the posterior,
specifically the probability that the prevalence is greater than 10%. We
can easily compute this from the posterior samples too:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="bayesian-estimation-and-inference.html#cb222-1" tabindex="-1"></a><span class="fu">mean</span>(p.samples <span class="sc">&gt;</span> <span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>## [1] 0.306</code></pre>
<p>Here we are simply asking which values of <code>p.samples</code> are greater than
0.1, which R specifies logically as TRUE or FALSE, and then we return
the proportion by applying the <code>mean</code> function (because R treats <code>TRUE</code>
as 1 and <code>FALSE</code> as 0), which R are greater th summing up the number of
samples that are greater than 0.1 .Here we get a a value very close to
what we saw before.</p>
<p>We can also quantify intervals that describe the probability of the
parameter value falling between two points. In Bayesian estimation these
intervals are often called <strong>credible intervals.</strong> Let’s quantify a 90%
credible interval. This is straightforward by using the <code>quantile</code>
function. For a 90% credible interval, the lower boundary would be the
value of prevalence for which 5% of the probability mass falls below the
value, and the upper boundary is the value for which 5% of the
probability mass lies above the value.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="bayesian-estimation-and-inference.html#cb224-1" tabindex="-1"></a><span class="fu">quantile</span>(p.samples, <span class="fu">c</span>(<span class="fl">0.05</span> , <span class="fl">0.95</span>))</span></code></pre></div>
<pre><code>##   5%  95% 
## 0.02 0.15</code></pre>
<p>The interpretation here is that there’s a 90% probability that the true
prevalence is between 2% and 15%. How about a 98% credible interval?</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="bayesian-estimation-and-inference.html#cb226-1" tabindex="-1"></a><span class="fu">quantile</span>(p.samples, <span class="fu">c</span>(<span class="fl">0.01</span> , <span class="fl">0.99</span>))</span></code></pre></div>
<pre><code>##   1%  99% 
## 0.01 0.15</code></pre>
<p>We conclude there is a 98% probability that the true prevalence is
between 1 and 15%. Note that as you increase the degree of credibility
in an interval, the interval becomes wider. Converseely, when you
decrease the degree of credibility, that interval narrows. That should
make sense intuitively. At its extreme, a 100% credibility interval must
include all the possible values of the estimand.</p>
</div>
</div>
<div id="specifying-priors" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Specifying priors<a href="bayesian-estimation-and-inference.html#specifying-priors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Arguably the most difficult part of Bayesian analysis is selecting the
priors. We have seen that the choice of prior distribution influences
the posterior estimate. In our example the difference was only slight,
but this will not always be the case. For example, suppose we had
specified a uniform prior for the prevalence between 50% and 100%. That
prior says any values below 50% are impossible, and so even though the
data indicate values around 8% are most likely, those values would not
be plausible in the posterior distribution.</p>
<p>In this book we will almost never use completely uninformative priors,
precisely because we rarely conduct a study with no prior knowledge. At
the same time, we will almost never use strongly informative priors that
could ultimately stack the deck against the data we observe. More often
than not, we’ll use priors that are <em>weakly informative</em>, or what we’ll
call <em>regularizing priors</em>. These priors will generally not stack the
deck in one particular direction when testing a hypothesis about a
particular effect. For example, if we were testing whether a vaccine
reduces the prevalence of an infection, we generally wouldn’t use a
prior that makes it more likely that the vaccine reduces the prevalence
than having no effect at all. Instead, we will generally use priors that
rule out values that we are confident are quite implausible.</p>
<p>For example, suppose the disease we’re working with to generate a
vaccine is known to evolve rapidly. The particular strains change from
year to year, and so we wouldn’t expect a vaccine to be 100% effective.
In this case, we could specify a prior distribution that makes it very
unlikely (or potentially impossible) that the effectiveness is 100%.</p>
<p>Consider another example. Suppose you are estimating the average height
of people in your community. We have a lot of prior knowledge about
human height. You know there are many 10-foot adults walking around, for
example. We can specify a prior for the mean that is centered around
typical values of mean height in other communities (perhaps in the 4-6
ft range) and that makes values outside of that range very unlikely.</p>
<p>How do we specify priors? We use probability distributions. We’ve
already seen this for the infection prevalence example. We specified
uniform prior distributions for prevalence. But we aren’t limited to a
uniform prior. We could have specified a prior distribution that makes
some value of the proportion more likely than others. One possibility is
the normal distribution, which is particularly useful for parameters
that can be positive or negative. In the height example, we might
specify a normal prior distribution for the mean height with a mean of
68 inches and a standard deviation of 2 inches. This would effectively
say that our prior knowledge leads us to believe that the mean height is
most likely (indeed, about 95% likely) between 64 and 72 inches. We’ll
use normal priors in following chapters.</p>
<p>For proportions, which is our focus in this chapter, a particularly
valuable probability distribution is the <strong>beta distribution</strong>, which is
a continuous probability distribution constrained to values between 0
and 1. In fact the values 0 and 1 are excluded in the beta distribution,
so this is a really handy distribution when we want to exclude the two
extremes of a proportion that we know are unreasonable.</p>
<p>The beta distribution has two parameters, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>, that
control the shape of the distribution. In statistical notation we
indicate a random variable X follows a beta distribution as</p>
<p><span class="math display">\[
X \sim Beta(\alpha, \beta)
\]</span></p>
<p>The beta probability density for different values of the proportion can
be quantified with the <code>dbeta</code> function. Figure @ref(fig:c07_f7) shows
three examples of how the shape of the beta distribution changes with
<span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>. The shape parameters don’t control the
distribution in a simple way, and so it is advisable to play around with
the values before settling on a particularity prior distribution. There
<a href="https://mathlets.org/mathlets/beta-distribution/">are useful
applications</a> on the
web that allow you to visualize the beta distribution while changing the
shape parameters with a slider.</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f7-1.png" alt="Example beta distributions with varying parameters alpha and beta." width="672" />
<p class="caption">
(#fig:c07_f7)Example beta distributions with varying parameters alpha and beta.
</p>
</div>
<p>Let’s apply a beta prior to the infection prevalence example. Let’s
assume we are very confident the infection prevalence is most likely
1-10% but and very unlikely to be above 20%. We’ll specify the following
beta distribution for the prevalence: <span class="math inline">\(p_{infected} \sim Beta(2.5, 30)\)</span>.
Let’s first visualize this particular beta distribution to confirm it’s
doing what we want:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="bayesian-estimation-and-inference.html#cb228-1" tabindex="-1"></a><span class="co">#create a grid of values at which to evaluate the parameter</span></span>
<span id="cb228-2"><a href="bayesian-estimation-and-inference.html#cb228-2" tabindex="-1"></a>p.grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb228-3"><a href="bayesian-estimation-and-inference.html#cb228-3" tabindex="-1"></a></span>
<span id="cb228-4"><a href="bayesian-estimation-and-inference.html#cb228-4" tabindex="-1"></a><span class="co">#compute the beta priorfrom 0 to 0.2</span></span>
<span id="cb228-5"><a href="bayesian-estimation-and-inference.html#cb228-5" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(<span class="at">x =</span> p.grid, <span class="at">shape1=</span><span class="fl">2.5</span>, <span class="at">shape2 =</span><span class="dv">30</span>)</span>
<span id="cb228-6"><a href="bayesian-estimation-and-inference.html#cb228-6" tabindex="-1"></a></span>
<span id="cb228-7"><a href="bayesian-estimation-and-inference.html#cb228-7" tabindex="-1"></a><span class="co">#combine to df</span></span>
<span id="cb228-8"><a href="bayesian-estimation-and-inference.html#cb228-8" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(p.grid, prior)</span>
<span id="cb228-9"><a href="bayesian-estimation-and-inference.html#cb228-9" tabindex="-1"></a></span>
<span id="cb228-10"><a href="bayesian-estimation-and-inference.html#cb228-10" tabindex="-1"></a><span class="co"># Plot the beta prior distribution</span></span>
<span id="cb228-11"><a href="bayesian-estimation-and-inference.html#cb228-11" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> p.grid, <span class="at">y =</span> prior)) <span class="sc">+</span></span>
<span id="cb228-12"><a href="bayesian-estimation-and-inference.html#cb228-12" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb228-13"><a href="bayesian-estimation-and-inference.html#cb228-13" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb228-14"><a href="bayesian-estimation-and-inference.html#cb228-14" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(d<span class="sc">$</span>prior)) <span class="sc">+</span></span>
<span id="cb228-15"><a href="bayesian-estimation-and-inference.html#cb228-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion infected&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability density&quot;</span>) <span class="sc">+</span></span>
<span id="cb228-16"><a href="bayesian-estimation-and-inference.html#cb228-16" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f8-1.png" alt="Prior distribution of prevalence specified as a beta distribution with alpha = 2.5 and beta = 30" width="672" />
<p class="caption">
(#fig:c07_f8)Prior distribution of prevalence specified as a beta distribution with alpha = 2.5 and beta = 30
</p>
</div>
<p>Looks good! We can see this prior distribution says that the most likely
value of prevalence is 5%, and that 0% and values above 25% are
basically implausible. Now we continue by computing the likelihood,
marginal likelihood, and posterior distribution:</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_f9-1.png" alt="Posterior distribution of the infection prevalence when using a beta prior distribution." width="672" />
<p class="caption">
(#fig:c07_f9)Posterior distribution of the infection prevalence when using a beta prior distribution.
</p>
</div>
<p>For comparison, let’s compute the MAP and the probability that the
prevalence is greater than 10% based on this posterior</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="bayesian-estimation-and-inference.html#cb229-1" tabindex="-1"></a><span class="co">#extract the max value of the posterior</span></span>
<span id="cb229-2"><a href="bayesian-estimation-and-inference.html#cb229-2" tabindex="-1"></a>d[<span class="fu">which.max</span>(d<span class="sc">$</span>posterior), ]</span></code></pre></div>
<pre><code>##   p.grid    prior       lik marg.lik posterior
## 7   0.06 9.630747 0.3784709 31.55932 0.1154954</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="bayesian-estimation-and-inference.html#cb231-1" tabindex="-1"></a><span class="co">#p(greater than 10%)</span></span>
<span id="cb231-2"><a href="bayesian-estimation-and-inference.html#cb231-2" tabindex="-1"></a><span class="fu">sum</span>(d<span class="sc">$</span>posterior[d<span class="sc">$</span>p.grid <span class="sc">&gt;</span> <span class="fl">0.1</span>])</span></code></pre></div>
<pre><code>## [1] 0.1860338</code></pre>
<p>Here we see the most plausible value of prevalence is 6%, and the
probability that the prevalence is greater than 10% is now only 19%.
This reflects our prior information that the infection is in the
community (not 0%) but is most likely around 5% and not greater than
25%, combined with the new data which has a maximum likelihood value at
7%. Thus, the posterior distribution is slightly shifted to higher
values than our prior. This is the essence of Bayesian analysis. You
come into the analysis with prior knowledge, and you update that prior
knowledge with new data, and express your updated view as a posterior
distribution. The key is to have a good rationale for how you express
the prior distribution. If it were plausible that the prevalence is
above 25%, the prior we just used would not be a good choice!</p>
</div>
<div id="decision-making" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Decision making<a href="bayesian-estimation-and-inference.html#decision-making" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How do we make decisions about hypotheses? In Bayesian inference, the
estimate is the entire posterior distribution representing the
probability that the estimand takes on any particular value. As we just
saw, this allows you to quantify the direct probabilities that are of
interest based on the research question. For example, if you are testing
the hpyothesis that pollution reduces fish abundance, you might estimate
the effect by quantifying the posterior distribution for the difference
in abundance between polluted and unpolluted areas. Suppose the estimate
is the difference in mean abundance, specified as the mean unpolluted
abundance minus the mean polluted abundance. You can use the posterior
distribution to directly quantify the probability that the difference in
means is a positive value. You might conclude something like, “there was
a 91% probability that the mean abundance was greater in unpolluted than
polluted areas”.</p>
<p>The bottom line is that decision making with Bayesian inference is less
about “yes” or “no” and more about evaluating hypotheses - as
represented by values of the estimand - with probability, which directly
represents our uncertainty. Some might find the absence of firm, binary
decisions to be inconvenient, but one should remember that in science
there is no certainty. There is only uncertainty, and we should quantify
it. Bayesian inference allows us to quantify uncertainty about
hypotheses, represented as parameter values, directly.</p>
</div>
<div id="specifying-and-fitting-statistical-models-with-bayes" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> Specifying and fitting statistical models with Bayes<a href="bayesian-estimation-and-inference.html#specifying-and-fitting-statistical-models-with-bayes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For the remainder of this book, we will approach Bayesian data analysis
by first specifying the statistical notation for our model, and then by
fitting the model with R. Let’s take a look at those two components.</p>
<div id="statistical-model-specification" class="section level3 hasAnchor" number="7.8.1">
<h3><span class="header-section-number">7.8.1</span> Statistical model specification<a href="bayesian-estimation-and-inference.html#statistical-model-specification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once we have a generative model, a study design, and estimands clearly
defined, we can define a statistical model for the data and use it to
estimate the estimands. As we just saw, Bayesian estimation of
parameters in statistical models requires three components: 1) the
likelihood, 2) the prior(s), and 3) the marginal likelihood. The
marginal likelihood is a numerical necessity to standardize the
posterior distribution, and it is computed based on the likelihood and
prior, so when defining statistical models for Bayesian estimation, we
focus our efforts on defining the likelihood and prior. Fitting a
statistical model requires specifying the model mathematically, and we
will use a particular notation to do so.</p>
<p>Consider our infection prevalence example. Using the more informative
prior, we can define the statistical model in this way:</p>
<p><span class="math display">\[
I \sim Binomial(N, p) \\
p \sim Beta(2.5, 30)
\]</span></p>
<p>What do these lines represent? The first line is the likelihood and
communicates our assumptions about how the observed data are produced
based on the generative model. It says the observed number of infections
(<span class="math inline">\(I\)</span>) follow a binomial distribution with <em>N</em> tests and a constant
probability of being infected, <em>p</em>. The probability of being infected,
<em>p</em>, is the estimand - the parameter of interest - and what we need to
estimate with the observed data, <em>I</em> and <em>N</em>. The tilde (~) specifies that the observed number of infections is a <strong>stochastic</strong> outcome, which just means that the observed number of infections is probabilistic rather than determined with certainty. Indeed, as we’ve defined the model, <span class="math inline">\(I\)</span> is a random variable described by a binomial distribution.</p>
<p>The second line defines the prior distribution, which is just our
mathematical way of describing our prior knowledge about the parameter.
It says we assume the probability of infection follows a beta
distribution with shape parameters <span class="math inline">\(\alpha = 2.5\)</span> and <span class="math inline">\(\beta = 30\)</span>. When
we looked at this beta distribution, we saw that it reflects our prior
belief that the prevalence is most likely around 5% and very unlikely to
be 0% or &gt;20%.</p>
<p>Every statistical model we define for Bayesian estimation requires these
two components, the likelihood and prior distribution. The likelihood
includes observed variables (the data) and unobserved parameters (the
quantities we need to estimate) and described how the observed data are
generated. In contrast the prior distributions describe our prior
knowledge for each unobserved parameter.</p>
<p>Some statistical models are quite simple. Indeed, or model of infection
prevalence has only a single parameter, and it happens to be the
estimand. Other models will have multiple parameters, not all of which
are necessarily of direct interest. Every unknown parameter requires a
prior distribution, whether you are interested in the parameter or now.
So when we fit more complicated models with multiple parameters, you’ll
want to make sure that there’s a prior distribution specified for each
parameter. We’ll see an example like that shortly.</p>
</div>
<div id="fitting-models-with-brms" class="section level3 hasAnchor" number="7.8.2">
<h3><span class="header-section-number">7.8.2</span> Fitting models with <em>brms</em><a href="bayesian-estimation-and-inference.html#fitting-models-with-brms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Moving forward we will use the <em>brms</em> package in R to fit models with
Bayesian inference. Although we could continue to fit some models with
grid approximation as we have this chapter, grid approximation becomes
very cumbersome and computationally intensive when fitting complex
models with multiple parameters.</p>
<p>There are different types of methods to fit approximations of posterior
distributions, and a method called <strong>Markov chain Monte Carlo (MCMC)</strong>
is by far the most common, and the method that <em>brms</em> uses. We will not
get into technical details on how MCMC works, but at a high level, MCMC
is similar to the sampling approach you’ve seen with grid approximation.
However, instead of evaluating pre-specified values for parameters on a
grid, MCMC uses an mathematical algorithm to explore possible values for
the parameters (i.e., the <em>parameter space</em>) and hone in on the most
likely values for the parameters.</p>
<p>MCMC works by generating a single sample of parameter values at a time,
where each new sample depends on the previous samples (a Markov
process). A sequence of samples is called a <strong>chain</strong>. You can think of
a chain like a random walk. The chain explores parameter space, and each
sample depends on the parameter space explored in the previous sample,
but over a long enough run of samples, the parameter space at the end of
the chain can be very different from the start. Ultimately the goal is
to run chains long enough such that the parameter space converges to a
consistent area where the true posterior distribution is found. So when
we fit models in <em>brms</em> with MCMC, we will need to use specific metrics
to evaluate whether the chains converged. When the model converges, we
will use the samples generated to describe the posterior distribution,
much like we did when we sampled from our grid approximation of the
posterior.</p>
<p>So how do we fit our model of infection prevalence with MCMC in <em>brms</em>?
Let’s take a look:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="bayesian-estimation-and-inference.html#cb233-1" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb233-2"><a href="bayesian-estimation-and-inference.html#cb233-2" tabindex="-1"></a></span>
<span id="cb233-3"><a href="bayesian-estimation-and-inference.html#cb233-3" tabindex="-1"></a><span class="co">#organize data</span></span>
<span id="cb233-4"><a href="bayesian-estimation-and-inference.html#cb233-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb233-5"><a href="bayesian-estimation-and-inference.html#cb233-5" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb233-6"><a href="bayesian-estimation-and-inference.html#cb233-6" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">x =</span> x, <span class="at">n =</span> n)</span>
<span id="cb233-7"><a href="bayesian-estimation-and-inference.html#cb233-7" tabindex="-1"></a></span>
<span id="cb233-8"><a href="bayesian-estimation-and-inference.html#cb233-8" tabindex="-1"></a><span class="co">#specify model formula</span></span>
<span id="cb233-9"><a href="bayesian-estimation-and-inference.html#cb233-9" tabindex="-1"></a>m.formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(x <span class="sc">|</span> <span class="fu">trials</span>(n) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb233-10"><a href="bayesian-estimation-and-inference.html#cb233-10" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">&quot;identity&quot;</span>))</span>
<span id="cb233-11"><a href="bayesian-estimation-and-inference.html#cb233-11" tabindex="-1"></a></span>
<span id="cb233-12"><a href="bayesian-estimation-and-inference.html#cb233-12" tabindex="-1"></a><span class="co">#specify priors</span></span>
<span id="cb233-13"><a href="bayesian-estimation-and-inference.html#cb233-13" tabindex="-1"></a>m.prior <span class="ot">&lt;-</span> <span class="fu">prior</span>(<span class="fu">beta</span>(<span class="fl">2.5</span>, <span class="dv">30</span>), <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>, <span class="at">lb=</span><span class="dv">0</span>, <span class="at">ub=</span><span class="dv">1</span>)</span>
<span id="cb233-14"><a href="bayesian-estimation-and-inference.html#cb233-14" tabindex="-1"></a>              </span>
<span id="cb233-15"><a href="bayesian-estimation-and-inference.html#cb233-15" tabindex="-1"></a><span class="co">#simulate the priors</span></span>
<span id="cb233-16"><a href="bayesian-estimation-and-inference.html#cb233-16" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d,</span>
<span id="cb233-17"><a href="bayesian-estimation-and-inference.html#cb233-17" tabindex="-1"></a>         <span class="at">formula =</span> m.formula,</span>
<span id="cb233-18"><a href="bayesian-estimation-and-inference.html#cb233-18" tabindex="-1"></a>         <span class="at">prior =</span> m.prior,</span>
<span id="cb233-19"><a href="bayesian-estimation-and-inference.html#cb233-19" tabindex="-1"></a>         <span class="at">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb233-20"><a href="bayesian-estimation-and-inference.html#cb233-20" tabindex="-1"></a></span>
<span id="cb233-21"><a href="bayesian-estimation-and-inference.html#cb233-21" tabindex="-1"></a><span class="fu">print</span>(m)</span></code></pre></div>
<pre><code>##  Family: binomial 
##   Links: mu = identity 
## Formula: x | trials(n) ~ 1 
##    Data: d (Number of observations: 1) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept     0.07      0.04     0.02     0.17 1.00     1098     1281
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>The main steps here are to organize the data (usually in a list or data
frame), specify the model formula, specify the priors, and then fit the
models. The model formula is defined with the <code>bf</code> formula, and it
specifies the systematic part of the model, namely how the data and
parameters are related to each other. In this case we define <code>x</code>
successes out of <code>n</code> trials as a function of (<code>~</code>) the parameter.
Specifying <code>1</code> for the parameter simply means the data are a function of
a single parameter that will be referred to as the <code>Intercept</code>. In this
particular example, the <code>Intercept</code> will represent the proportion
infected. The second part of the formula specifies the <code>family</code>, which
is probability distribution for the response variable. In this case the
family is the binomial distribution. Each probability distribution as a
<code>link</code> function. Specifying <code>identity</code> link for a binomial distribution
makes the ’Intercept` represent a probability.</p>
<p>The <code>prior</code> function defines the a prior for a particular parameter.
Because there is only a single parameter, we have only a single
parameter to define. The <code>prior</code> function requires a particular
probability distribution to describe the prior, in this case a beta
distribution with its two parameters. We then specify the <code>class</code>, which
is the type of parameter for which we are defining a prior. As
mentioned, the parameter in this case is denoted the <code>Intercept</code>. W</p>
<p>Finally the <code>brm</code> function wraps everything together (the <code>data</code>,
<code>formula</code> and <code>prior</code> previously defined) and fits the model. When a
model is being fit, it defaults to providing messages of its progress,
but here I used the <code>refresh</code> argument to suppress those messages. Once
the model is fit, we print the output <code>m</code>. The output prints a key
descriptors about the model that was fit. The only new part here is the
“Draws”, which reports that four chains were fit, each with a total of
2000 iterations, 1000 of which were a “warmup”. The iterations during
the warmup phase are discarded and not considered to describe the
posterior distribution. We use a warmup phase when starting a chain
because the paramater values are expected to vary widely. The 1000
samples following the warmup phase are retained to describe the
posterior distribution. Because we have four chains each with 1000
samples retained, the total number of samples to describe the posterior
distribution is 4000. Sometimes it’s useful to retain a subset of these
final draws, in which case we can apply a <code>thin</code> value greater than one.
Generally we should only need to do that when computer space is limited,
and for the models in this book, that won’t be an issue.</p>
<p>Below the basic model description is a section called “Regression
Coefficients”, which is the main output of the mdoel. The <code>Intercept</code>
line here represents the probability of infection. The <code>Estimate</code> is the
mean of the posteiror distribution (in this case 7%), and the
<code>Est.Error</code> is the standard deviation of the posterior (in this case
4%). We are also provided a 95% credible interval, which is 2-16%. The
other three values are statistics used to evaluate whether the model
converged to an appropriate parameter space. More on those in the next
chapter.</p>
<p>In addition to the standard model output, we can extract the posterior
samples with the <code>as_draws_df</code> function, which we will save as <code>m.post</code>.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="bayesian-estimation-and-inference.html#cb235-1" tabindex="-1"></a><span class="co">#posterior samples</span></span>
<span id="cb235-2"><a href="bayesian-estimation-and-inference.html#cb235-2" tabindex="-1"></a>m.post <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as_draws_df</span>(m))</span>
<span id="cb235-3"><a href="bayesian-estimation-and-inference.html#cb235-3" tabindex="-1"></a><span class="fu">head</span>(m.post)</span></code></pre></div>
<pre><code>##   b_Intercept  Intercept   lprior      lp__ .chain .iteration .draw
## 1  0.03800522 0.03800522 2.250775 -2.162432      1          1     1
## 2  0.03278834 0.03278834 2.186140 -2.441243      1          2     2
## 3  0.02463775 0.02463775 2.000807 -3.072289      1          3     3
## 4  0.04761258 0.04761258 2.297758 -1.815258      1          4     4
## 5  0.04761258 0.04761258 2.297758 -1.815258      1          5     5
## 6  0.04655451 0.04655451 2.296249 -1.845059      1          6     6</code></pre>
<p>The only column we need to focus on now is <code>b_Intercept</code>, which
represents each of the 4000 samples of the proportion infected from the
posterior distribution. We could use this to illustrate the posterior
distribution and quantify any of the descriptors of the posterior we
discussed earlier in the chapter:</p>
<div class="figure" style="text-align: center">
<img src="ch07_estimation_files/figure-html/c07_chunk36-1.png" alt="Posterior distribution of the infection prevalence estimated with brms." width="672" />
<p class="caption">
(#fig:c07_chunk36)Posterior distribution of the infection prevalence estimated with brms.
</p>
</div>
<pre><code>## [1] 0.07432989</code></pre>
<pre><code>## [1] 0.2245</code></pre>
<p>Don’t worry if this all seems confusing. It’s a lot of information, but
we will get lots of practice defining statistical models, fitting them
with data in brms, and interpreting the outputs. I will orient you to
the key parts as we move forward.</p>
</div>
</div>
<div id="estimation-for-a-continuous-random-variable" class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> Estimation for a continuous random variable<a href="bayesian-estimation-and-inference.html#estimation-for-a-continuous-random-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The test result data for our infection prevalence example was a discrete random variable, which we modeled with a binomial probability distribution. In this section we I will show you how we can do Bayesian estimation with continuous random variables too. Like infection prevalence, the research question we’ll focus on is descriptive: What is the average resting heart rate for adults in the U.S.?The data we’ll
use are included in an R packages called <em>NHANES</em>, which stands for the
U.S. National Health and Nutrition Examination study. NHANES is a survey
of a variety of health parameters for people in the U.S. Let’s start by
loading the data:</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="bayesian-estimation-and-inference.html#cb239-1" tabindex="-1"></a><span class="co">#install.packages(&quot;NHANES&quot;) #install the package if necessary</span></span>
<span id="cb239-2"><a href="bayesian-estimation-and-inference.html#cb239-2" tabindex="-1"></a><span class="fu">library</span>(NHANES) <span class="co">#load the package</span></span>
<span id="cb239-3"><a href="bayesian-estimation-and-inference.html#cb239-3" tabindex="-1"></a><span class="fu">data</span>(NHANES) <span class="co">#load the dataframe NHANES</span></span>
<span id="cb239-4"><a href="bayesian-estimation-and-inference.html#cb239-4" tabindex="-1"></a>d <span class="ot">&lt;-</span> NHANES <span class="co">#simplify the name of the data frame</span></span></code></pre></div>
<p>Running the code above produces a data frame called <code>d</code>. I encourage you to look at the structure of the full dataframe (<code>str(d)</code>), which includes dozens of variables, but for now let’s turn our attention to a summary of two variabiles of interest: <code>Age</code> (years) and <code>Pulse</code> (resting heart rate in beats per minute, bpm).</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="bayesian-estimation-and-inference.html#cb240-1" tabindex="-1"></a><span class="fu">summary</span>(d[, <span class="fu">c</span>(<span class="st">&quot;Age&quot;</span>,<span class="st">&quot;Pulse&quot;</span>)])</span></code></pre></div>
<pre><code>##       Age            Pulse       
##  Min.   : 0.00   Min.   : 40.00  
##  1st Qu.:17.00   1st Qu.: 64.00  
##  Median :36.00   Median : 72.00  
##  Mean   :36.74   Mean   : 73.56  
##  3rd Qu.:54.00   3rd Qu.: 82.00  
##  Max.   :80.00   Max.   :136.00  
##                  NA&#39;s   :1437</code></pre>
<p>You can see based on the summary distribution of each variable that the
sample includes individuals of any age. For our research question, we
will focus on estimating the average resting heart rate of <em>adults</em> in
the U.S. We can subset the data to remove individuals under 18 years
old, leaving observations for 7216 adults (excluding missing observations):</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="bayesian-estimation-and-inference.html#cb242-1" tabindex="-1"></a>d <span class="ot">&lt;-</span> d[d<span class="sc">$</span>Age <span class="sc">&gt;=</span><span class="dv">18</span>, ]</span>
<span id="cb242-2"><a href="bayesian-estimation-and-inference.html#cb242-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(d<span class="sc">$</span>Pulse)) <span class="co">#sample size</span></span></code></pre></div>
<pre><code>## [1] 7216</code></pre>
<p>Now let’s turn our attention now to estimating the resting heart rate in this sample. Heart rate is a continuous random variable, and our estimand is the mean heart rate. As we know from the last chapter, one probability distribution that uses the mean to describe central tendency is the normal distribution, and here we can use it as our generative model. By using the normal distribution, we assume heart rates are observed at random with variation around a population mean (<span class="math inline">\(\mu\)</span>) and with among-individual variation described by a standard deviation (<span class="math inline">\(\sigma\)</span>). We also assume that heart rate is measured without error.</p>
<p>Unlike the binomial distribution - which has just a single parameter - the normal distribution has two parameters - mean and standard deviation. Because we are assuming heart rates come from a normal distribution, we have to include both the mean and the standard deviation in our statistical model. Indeed, when we assume a variable is drawn from a particular probability distribution, we have to estimate (or assume values for) all the parameters for that probability distribution whether we want them or not. That’s why it’s useful to differentiate between types of parameters, the estimands being the parameters that we are most interested in.</p>
<p>Here’s the statistical model we will use:</p>
<p><span class="math display">\[
\begin{array}{l}
r_i \sim \mathrm{Normal}(\mu, \sigma) \\
\mu \sim \mathrm{Normal}(75, 10) \\
\sigma \sim \mathrm{Uniform}(0, 20)
\end{array}
\]</span></p>
<p>Let’s walk through each line of the model. First we have <span class="math inline">\(r_i \sim \mathrm{Normal}(\mu, \sigma)\)</span>. Here we are defining the observed values of heart rate <em>r</em> for each individual <em>i</em> as a random variable following a normal distribution with parameters mean = <span class="math inline">\(\mu\)</span> and standard deviation = <span class="math inline">\(\sigma\)</span>. Remember the tilde symbol (~) defines a relationship as stochastic, meaning the observed values <span class="math inline">\(r_i\)</span> are probabilistic. The normal distribution with its parameters defines the probability of drawing particular values of heart rate. We don’t know what those parameter values are, so we will have to estimate them. In the context of Bayesian estimation, this line represents the likelihood.</p>
<p>The second and third lines are prior distributions, representing our prior knowledge about the mean and standard deviation of heart rates. What does each prior distribution say? The first prior is for the mean heart rate: <span class="math inline">\(\mu \sim \mathrm{Normal}(75, 10)\)</span>. Remember prior distributions are probability distributions, in this case describing the probability of the <em>mean</em> taking on different values, prior to seeing the data. We’re using a normal probability distribution to characterize our prior knowledge, specifically a normal distribution with a mean of 75 and standard deviation of 10. This can be confusing, because our likelihood assumes the individual heart rates are described by a normal distribution, and now we have a normal distribution describing our prior knowledge for a parameter. Effectively we’re using a normal probability distribution to describe our beliefs about a parameter - the mean - for another normal probability distribution, the individual heart rates.</p>
<p>What does the prior for the mean heart rate say? First, it says that the most plausible value for the average heart rate is 75 bpm. Remember that the normal distribution is bell-shaped, so although 75 bpm is the most plausible value, the mean could be more or less than that. How much? How much more or less? That’s where the standard deviation comes into play. The standard deviation describes variation around the mean. Our normal prior for the mean heart rate specifies a standard deviation of 10 bpm. Here we can apply the empirical rule to get a sense for the plausibility of different values of the mean heart rate based on this normal prior. The empirical rule says about two thirds of the observations of a normal distribution are within one standard deviation of the mean, and 95% of the observations are within two standard deviations of the mean. Thus if the normal distribution is defined with a mean of 75 and standard deviation of 10, it’s effectively saying I think there’s a two-thirds chance that the mean resting pulse rate is 65-85 bpm, and there’s a 95% chance that it’s 55-95 bpm. Values outside those bounds collectively have only a 5% probability. Of course, we could also use R to plot the distribution:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="bayesian-estimation-and-inference.html#cb244-1" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">75</span></span>
<span id="cb244-2"><a href="bayesian-estimation-and-inference.html#cb244-2" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb244-3"><a href="bayesian-estimation-and-inference.html#cb244-3" tabindex="-1"></a></span>
<span id="cb244-4"><a href="bayesian-estimation-and-inference.html#cb244-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(mu <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>sigma, mu <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span>sigma, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb244-5"><a href="bayesian-estimation-and-inference.html#cb244-5" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">dens =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma))</span>
<span id="cb244-6"><a href="bayesian-estimation-and-inference.html#cb244-6" tabindex="-1"></a></span>
<span id="cb244-7"><a href="bayesian-estimation-and-inference.html#cb244-7" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> dens)) <span class="sc">+</span></span>
<span id="cb244-8"><a href="bayesian-estimation-and-inference.html#cb244-8" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb244-9"><a href="bayesian-estimation-and-inference.html#cb244-9" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb244-10"><a href="bayesian-estimation-and-inference.html#cb244-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean resting heart rate (bpm)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb244-11"><a href="bayesian-estimation-and-inference.html#cb244-11" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Prior distribution for the mean resting heart rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb244-12"><a href="bayesian-estimation-and-inference.html#cb244-12" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="ch07_estimation_files/figure-html/c07_chunk40-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>How did I know to use those particular values for the normal prior (mean = 75, standard deviation = 10). This is where domain knowledge is helpful. Based on prior knowledge from the medical literature and my own experience on track and cross country teams where we often measured our heart rates, I have a general sense about the most plausible values for average heart rate. I don’t know it for sure, but I think it’s around 75 bpm. It could be more or less, but I think it’s <em>very</em> unlikely that hte <em>typical</em> heart rate is less than 50 bpm or over 100 bpm. I also don’t think it’s equally plausible that the mean heart rate is anywhere between 50 and 100 bpm. I think it’s most likely around 75, with decreasing probability moving away from 75. The normal distribution captures that prior knowledge nicely (albeit imperfectly, as every model is imperfect).</p>
<p>What about the standard deviation? Admittedly, I feel like I know less about the variation among people in their heart rates than I do about the average heart rate. I wish I could just ignore the standard deviation, but because it’s a parameter in my statistical model, it needs a prior. The prior I chose for the standard deviation is a uniform distribution between 0 bpm and 20 bpm. Let’s take a look at that distribution:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="bayesian-estimation-and-inference.html#cb245-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb245-2"><a href="bayesian-estimation-and-inference.html#cb245-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb245-3"><a href="bayesian-estimation-and-inference.html#cb245-3" tabindex="-1"></a></span>
<span id="cb245-4"><a href="bayesian-estimation-and-inference.html#cb245-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">20</span>, <span class="at">length.out =</span> <span class="dv">2000</span>)</span>
<span id="cb245-5"><a href="bayesian-estimation-and-inference.html#cb245-5" tabindex="-1"></a>dens <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(x <span class="sc">&lt;</span> a <span class="sc">|</span> x <span class="sc">&gt;</span> b, <span class="dv">0</span>, <span class="fu">dunif</span>(x, <span class="at">min =</span> a, <span class="at">max =</span> b))</span>
<span id="cb245-6"><a href="bayesian-estimation-and-inference.html#cb245-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">dens =</span> dens)</span>
<span id="cb245-7"><a href="bayesian-estimation-and-inference.html#cb245-7" tabindex="-1"></a></span>
<span id="cb245-8"><a href="bayesian-estimation-and-inference.html#cb245-8" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> dens)) <span class="sc">+</span></span>
<span id="cb245-9"><a href="bayesian-estimation-and-inference.html#cb245-9" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb245-10"><a href="bayesian-estimation-and-inference.html#cb245-10" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">direction =</span> <span class="st">&quot;hv&quot;</span>) <span class="sc">+</span></span>
<span id="cb245-11"><a href="bayesian-estimation-and-inference.html#cb245-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parameter value&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>, <span class="at">title =</span> </span>
<span id="cb245-12"><a href="bayesian-estimation-and-inference.html#cb245-12" tabindex="-1"></a>         <span class="st">&quot;Prior distribution for the standard deviation of heart rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb245-13"><a href="bayesian-estimation-and-inference.html#cb245-13" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb245-14"><a href="bayesian-estimation-and-inference.html#cb245-14" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">17</span>))</span></code></pre></div>
<p><img src="ch07_estimation_files/figure-html/c07_chunk41-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>The uniform distribution is simple. A <span class="math inline">\(\mathrm{Uniform}(0, 20)\)</span> prior for the standard deviation says that, before seeing the data, we consider any value of the standard deviation between 0 and 20 bpm to be equally plausible. The lower bound of 0 makes good sense because standard deviations cannot be negative (there can’t be negative variation). The upper bound of 15 bpm is also conservative. If the true standard deviation was 20 bpm, it would imply that95% of all the heart rates to be within 40 bpm of the mean, and that’s a large range. Uniform distributions work well as prior distributions when the parameter of interest is only positive and when we only know enough to define hard limits on possible values. Yet the uniform distribution isn’t completely uninformative. Indeed, it makes a rather strong assumption that values anywhere in the range of 0 and 20 are equally plausible, and other values are impossible.</p>
<p>With our statistical model in defined, let’s proceed with estimation in <code>brms</code>:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="bayesian-estimation-and-inference.html#cb246-1" tabindex="-1"></a><span class="co">#model formula: heart rate is normally distributed</span></span>
<span id="cb246-2"><a href="bayesian-estimation-and-inference.html#cb246-2" tabindex="-1"></a>m1.formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(Pulse <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="fu">gaussian</span>())</span>
<span id="cb246-3"><a href="bayesian-estimation-and-inference.html#cb246-3" tabindex="-1"></a></span>
<span id="cb246-4"><a href="bayesian-estimation-and-inference.html#cb246-4" tabindex="-1"></a><span class="co"># Priors:</span></span>
<span id="cb246-5"><a href="bayesian-estimation-and-inference.html#cb246-5" tabindex="-1"></a><span class="co">#   Intercept (mu) ~ Normal(75, 10)</span></span>
<span id="cb246-6"><a href="bayesian-estimation-and-inference.html#cb246-6" tabindex="-1"></a><span class="co">#   sigma ~ Uniform(0, 20)</span></span>
<span id="cb246-7"><a href="bayesian-estimation-and-inference.html#cb246-7" tabindex="-1"></a>m1.prior <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb246-8"><a href="bayesian-estimation-and-inference.html#cb246-8" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">75</span>, <span class="dv">10</span>), <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb246-9"><a href="bayesian-estimation-and-inference.html#cb246-9" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">uniform</span>(<span class="dv">0</span>, <span class="dv">20</span>), <span class="at">class =</span> <span class="st">&quot;sigma&quot;</span>, <span class="at">lb =</span> <span class="dv">0</span>, <span class="at">ub =</span> <span class="dv">20</span>)</span>
<span id="cb246-10"><a href="bayesian-estimation-and-inference.html#cb246-10" tabindex="-1"></a>)</span>
<span id="cb246-11"><a href="bayesian-estimation-and-inference.html#cb246-11" tabindex="-1"></a></span>
<span id="cb246-12"><a href="bayesian-estimation-and-inference.html#cb246-12" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb246-13"><a href="bayesian-estimation-and-inference.html#cb246-13" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb246-14"><a href="bayesian-estimation-and-inference.html#cb246-14" tabindex="-1"></a>  <span class="at">data =</span> d,</span>
<span id="cb246-15"><a href="bayesian-estimation-and-inference.html#cb246-15" tabindex="-1"></a>  <span class="at">formula =</span> m1.formula,</span>
<span id="cb246-16"><a href="bayesian-estimation-and-inference.html#cb246-16" tabindex="-1"></a>  <span class="at">prior =</span> m1.prior,</span>
<span id="cb246-17"><a href="bayesian-estimation-and-inference.html#cb246-17" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">123</span>,</span>
<span id="cb246-18"><a href="bayesian-estimation-and-inference.html#cb246-18" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb246-19"><a href="bayesian-estimation-and-inference.html#cb246-19" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb246-20"><a href="bayesian-estimation-and-inference.html#cb246-20" tabindex="-1"></a>)</span>
<span id="cb246-21"><a href="bayesian-estimation-and-inference.html#cb246-21" tabindex="-1"></a></span>
<span id="cb246-22"><a href="bayesian-estimation-and-inference.html#cb246-22" tabindex="-1"></a><span class="fu">print</span>(m1)</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity 
## Formula: Pulse ~ 1 
##    Data: d (Number of observations: 7216) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept    72.57      0.14    72.29    72.85 1.00     3326     2552
## 
## Further Distributional Parameters:
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma    11.96      0.10    11.77    12.16 1.00     3624     2726
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>Let’s walk through this. We’ve defined the likelihood with the <code>bf</code> function, where the formula <code>Pulse ~ 1</code> tells <code>brms</code> that we want to fit a model with only an intercept, which is just a fancy way of saying we want the mean of the normal distribution that we specified with <code>family = gaussian</code> (recall “Gaussian” is another name for the normal distribution). We then define our priors. In <code>brms</code>, each parameter getting a prior needs a distribution for the prior. You can see we specify <code>normal(75, 10)</code> for the mean and <code>uniform(0, 20)</code> for the standard deviation in this case. The <code>class</code> argument is required to indicate the type of variable, here being an <code>Intercept</code> for the mean and <code>sigma</code> for the standard deviation.</p>
<p>After fitting the model, we print the model output (<code>print(m1)</code>) to see same basic numerical summaries of the posterior distributions for the parameters we estimated. Our estimate for the mean heart rate is listed under “Regression Coefficients” as the “Intercept”. Remember that our estimate is an entire probability distribution, and <code>brms</code> defaults to showing you the mean of the posterior as the “Estimate”. Thus we see that them ean of the posterior distribution for resting heart rate is 72.57 bpm. The “Est.Error” represents the standard deviation of the posterior distribution, and we also see limits of a 95% credible interval (CI). Based on the analysis, we can say there’s a 95% probability that the mean resting heart rate is between 72.29 bpm and 72.85 bpm.</p>
<p>In addition to the mean heart rate, we also get a posterior distribution for the standard deviation, here denoted “sigma” under “Further Distributional Parameters”. There we see the posterior mean is 11.96 bpm, and there’s a 95% probability that the standard deviation is between 11.77 and 12.16 bpm. Note that the credible intervals for the mean and standard deviation of resting heart rates are both quite narrow, indicating that we’ve estimated these parameters with a high degree of precision.</p>
<p>It’s worth noting here that although <code>brms</code> shows 95% credible intervals by default, there’s nothing special about the 95% level. Indeed, a confidence level of 94% or 96% would probably tell the same story about uncertainty. The use of 95% is largely historical and related to the use of particular thresholds of “statistical significance” with frequentist approaches to estimation. But there’s no reason to obsess about using a 95% credible interval. One just needs to be aware that credible intervals will widen as you increase the probability level, and they’ll decrease as you narrow the probability level. And it’s straightforward to ask <code>brms</code> to show credible intervals at different probaiblity levels using the <code>prob</code> argument in the <code>summary</code> function. Here you can see a summary of the posterior distribution with a 92% credible interval:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="bayesian-estimation-and-inference.html#cb248-1" tabindex="-1"></a><span class="fu">summary</span>(m1, <span class="at">prob=</span><span class="fl">0.92</span>)</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity 
## Formula: Pulse ~ 1 
##    Data: d (Number of observations: 7216) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Regression Coefficients:
##           Estimate Est.Error l-92% CI u-92% CI Rhat Bulk_ESS Tail_ESS
## Intercept    72.57      0.14    72.33    72.83 1.00     3326     2552
## 
## Further Distributional Parameters:
##       Estimate Est.Error l-92% CI u-92% CI Rhat Bulk_ESS Tail_ESS
## sigma    11.96      0.10    11.79    12.14 1.00     3624     2726
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>Just like we did with our model of infection prevalence, we can use the samples of the posterior distribution to characterize it however we’d like. We could, for example, make a plot of the full posterior distributions for both the mean and standard deviation:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="bayesian-estimation-and-inference.html#cb250-1" tabindex="-1"></a><span class="co">#posterior samples</span></span>
<span id="cb250-2"><a href="bayesian-estimation-and-inference.html#cb250-2" tabindex="-1"></a>m1.post <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as_draws_df</span>(m1))</span>
<span id="cb250-3"><a href="bayesian-estimation-and-inference.html#cb250-3" tabindex="-1"></a><span class="fu">head</span>(m1.post)</span></code></pre></div>
<pre><code>##   b_Intercept    sigma Intercept    lprior      lp__ .chain .iteration .draw
## 1    72.67079 12.05158  72.67079 -6.244382 -28148.87      1          1     1
## 2    72.37915 12.02905  72.37915 -6.251600 -28149.36      1          2     2
## 3    72.90687 11.99027  72.90687 -6.239162 -28151.05      1          3     3
## 4    72.76516 12.07201  72.76516 -6.242229 -28149.77      1          4     4
## 5    72.69316 12.07822  72.69316 -6.243863 -28149.28      1          5     5
## 6    72.44472 11.98501  72.44472 -6.249903 -28148.62      1          6     6</code></pre>
<p>We could use these samples to plot the full posterior distribution for both parameters.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="bayesian-estimation-and-inference.html#cb252-1" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#allows us to combine plots in one output</span></span>
<span id="cb252-2"><a href="bayesian-estimation-and-inference.html#cb252-2" tabindex="-1"></a></span>
<span id="cb252-3"><a href="bayesian-estimation-and-inference.html#cb252-3" tabindex="-1"></a>p_mu <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(m1.post, <span class="fu">aes</span>(<span class="at">x =</span> b_Intercept)) <span class="sc">+</span></span>
<span id="cb252-4"><a href="bayesian-estimation-and-inference.html#cb252-4" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb252-5"><a href="bayesian-estimation-and-inference.html#cb252-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu<span class="sc">~</span><span class="st">&quot;(Mean heart rate&quot;</span>),</span>
<span id="cb252-6"><a href="bayesian-estimation-and-inference.html#cb252-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb252-7"><a href="bayesian-estimation-and-inference.html#cb252-7" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Posterior for the mean&quot;</span>) <span class="sc">+</span></span>
<span id="cb252-8"><a href="bayesian-estimation-and-inference.html#cb252-8" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb252-9"><a href="bayesian-estimation-and-inference.html#cb252-9" tabindex="-1"></a></span>
<span id="cb252-10"><a href="bayesian-estimation-and-inference.html#cb252-10" tabindex="-1"></a>p_sigma <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(m1.post, <span class="fu">aes</span>(<span class="at">x =</span> sigma)) <span class="sc">+</span></span>
<span id="cb252-11"><a href="bayesian-estimation-and-inference.html#cb252-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb252-12"><a href="bayesian-estimation-and-inference.html#cb252-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(sigma<span class="sc">~</span><span class="st">&quot;(SD of heart rate)&quot;</span>),</span>
<span id="cb252-13"><a href="bayesian-estimation-and-inference.html#cb252-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb252-14"><a href="bayesian-estimation-and-inference.html#cb252-14" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Posterior for the standard deviation&quot;</span>) <span class="sc">+</span></span>
<span id="cb252-15"><a href="bayesian-estimation-and-inference.html#cb252-15" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb252-16"><a href="bayesian-estimation-and-inference.html#cb252-16" tabindex="-1"></a></span>
<span id="cb252-17"><a href="bayesian-estimation-and-inference.html#cb252-17" tabindex="-1"></a>p_mu <span class="sc">+</span> p_sigma</span></code></pre></div>
<p><img src="ch07_estimation_files/figure-html/c07_chunk45-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>We could also compute other summary statistics that are automatically reported by <code>brms</code> in the summary:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="bayesian-estimation-and-inference.html#cb253-1" tabindex="-1"></a><span class="co">#posterior median </span></span>
<span id="cb253-2"><a href="bayesian-estimation-and-inference.html#cb253-2" tabindex="-1"></a><span class="fu">median</span>(m1.post<span class="sc">$</span>b_Intercept)</span></code></pre></div>
<pre><code>## [1] 72.57247</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="bayesian-estimation-and-inference.html#cb255-1" tabindex="-1"></a><span class="co">#interquartile range</span></span>
<span id="cb255-2"><a href="bayesian-estimation-and-inference.html#cb255-2" tabindex="-1"></a><span class="fu">IQR</span>(m1.post<span class="sc">$</span>b_Intercept)</span></code></pre></div>
<pre><code>## [1] 0.1952223</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="bayesian-estimation-and-inference.html#cb257-1" tabindex="-1"></a><span class="co">#probability that the mean height is &gt;75 bpm</span></span>
<span id="cb257-2"><a href="bayesian-estimation-and-inference.html#cb257-2" tabindex="-1"></a><span class="fu">mean</span>(m1.post<span class="sc">$</span>b_Intercept<span class="sc">&gt;</span><span class="dv">75</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="bayesian-estimation-and-inference.html#cb259-1" tabindex="-1"></a><span class="co">#80% credible interval</span></span>
<span id="cb259-2"><a href="bayesian-estimation-and-inference.html#cb259-2" tabindex="-1"></a><span class="fu">quantile</span>(m1.post<span class="sc">$</span>b_Intercept, <span class="at">probs=</span>(<span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>)))</span></code></pre></div>
<pre><code>##      10%      90% 
## 72.38971 72.75560</code></pre>
<p>The posterior distributions estimated from our model are about the population mean and standard deviation. But what if we were interested in what the model implied about the <em>individual</em> heart rates? For example, how likely is it, based on our model, that an individual has tachycardia, defined as a resting heart rate over 100 bpm? We can interrogate questions like this by combining the information from our posterior distributions on the mean and standard deviation. As we can see in the header of the posterior samples above (<code>head(m1.post)</code>), every sample of the posterior ditribution includes a value of the mean (<code>b_Intercept</code>) and standard deviation (<code>sigma</code>) of resting heart rates. These values vary from sample to sample, collectively describing the uncertainty about the parametrs. We can leverage that variation to derive a posterior distribution for the individual heart rates implied by the mean and standard deviation. One simple way to do this is by simulation, drawing a random value of an individual’s heart rate from the normal distribution implied by each sample in the posterior:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="bayesian-estimation-and-inference.html#cb261-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb261-2"><a href="bayesian-estimation-and-inference.html#cb261-2" tabindex="-1"></a></span>
<span id="cb261-3"><a href="bayesian-estimation-and-inference.html#cb261-3" tabindex="-1"></a><span class="co"># Simulate one individual heart rate per posterior sample</span></span>
<span id="cb261-4"><a href="bayesian-estimation-and-inference.html#cb261-4" tabindex="-1"></a>post_r <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(m1.post), <span class="at">mean =</span> m1.post<span class="sc">$</span>b_Intercept, <span class="at">sd =</span> m1.post<span class="sc">$</span>sigma)</span>
<span id="cb261-5"><a href="bayesian-estimation-and-inference.html#cb261-5" tabindex="-1"></a></span>
<span id="cb261-6"><a href="bayesian-estimation-and-inference.html#cb261-6" tabindex="-1"></a><span class="co"># Create data frame for plotting</span></span>
<span id="cb261-7"><a href="bayesian-estimation-and-inference.html#cb261-7" tabindex="-1"></a>df_post <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pulse =</span> post_r)</span>
<span id="cb261-8"><a href="bayesian-estimation-and-inference.html#cb261-8" tabindex="-1"></a></span>
<span id="cb261-9"><a href="bayesian-estimation-and-inference.html#cb261-9" tabindex="-1"></a><span class="fu">ggplot</span>(df_post, <span class="fu">aes</span>(<span class="at">x =</span> pulse)) <span class="sc">+</span></span>
<span id="cb261-10"><a href="bayesian-estimation-and-inference.html#cb261-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;slategray3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb261-11"><a href="bayesian-estimation-and-inference.html#cb261-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Joint posterior distribution&quot;</span>,</span>
<span id="cb261-12"><a href="bayesian-estimation-and-inference.html#cb261-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Individual resting heart rate (bpm)&quot;</span>,</span>
<span id="cb261-13"><a href="bayesian-estimation-and-inference.html#cb261-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb261-14"><a href="bayesian-estimation-and-inference.html#cb261-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ch07_estimation_files/figure-html/c07_chunk47-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>The resulting distribution is called a <strong>joint posterior distribution</strong>, and we could summarize it just as we would one of the individual posterior distribution, the main difference being that here we are talking about individual heart rates. For example, we can use the joint posterior to compute the probability that an individual in this population has tachycardia:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="bayesian-estimation-and-inference.html#cb262-1" tabindex="-1"></a><span class="fu">mean</span>(df_post<span class="sc">$</span>pulse<span class="sc">&gt;</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>## [1] 0.0115</code></pre>
<p>We see that based on our statistical model, we expect 1.15% of the population has tachycardia. We could do the same thing for bradycardia, which is defined as a slow heart rate usually less than 60 bpm:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="bayesian-estimation-and-inference.html#cb264-1" tabindex="-1"></a><span class="fu">mean</span>(df_post<span class="sc">$</span>pulse<span class="sc">&lt;</span><span class="dv">60</span>)</span></code></pre></div>
<pre><code>## [1] 0.14475</code></pre>
<p>There’s a much greater portion of the population that likely has bradycardia than tachycardia. This isn’t too surprising, however, because bradycardia is common in people who exercise a lot, indicating high conditioning.</p>
</div>
<div id="next-steps-1" class="section level2 hasAnchor" number="7.10">
<h2><span class="header-section-number">7.10</span> Next steps<a href="bayesian-estimation-and-inference.html#next-steps-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter has introduced you to the basic steps of estimating unknown parameters from statistical models with Bayesian inference. In the next chapter, we elaborate the steps of a Bayesian analysis to help ensure that the statistical models we choose are appropriate for th goals of our analysis. Then we will ramp up the level of complexity of our statistical models as look more directly at research questions that are focused on explanation more than description.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability-as-the-language-of-uncertainty.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bayesian-workflow.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true,
    "toc_depth": 2
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
