<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Bayesian Workflow | Research Design and Statistics</title>
  <meta name="description" content="An introduction to research design and statistics" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Bayesian Workflow | Research Design and Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to research design and statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Bayesian Workflow | Research Design and Statistics" />
  
  <meta name="twitter:description" content="An introduction to research design and statistics" />
  

<meta name="author" content="Bradley J. Cosentino" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bayesian-estimation-and-inference.html"/>
<link rel="next" href="the-linear-model.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#work-in-progress"><i class="fa fa-check"></i>Work in progress</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html"><i class="fa fa-check"></i><b>1</b> Why Statistics? The Problem of Uncertainty</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#the-nature-of-science"><i class="fa fa-check"></i><b>1.1</b> The nature of science</a></li>
<li class="chapter" data-level="1.2" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#goals-of-scientific-research"><i class="fa fa-check"></i><b>1.2</b> Goals of scientific research</a></li>
<li class="chapter" data-level="1.3" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#three-general-goals-of-scientific-research"><i class="fa fa-check"></i><b>1.3</b> Three general goals of scientific research</a></li>
<li class="chapter" data-level="1.4" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#research-design-and-statistical-analysis-depend-on-your-goal"><i class="fa fa-check"></i><b>1.4</b> Research design and statistical analysis depend on your goal</a></li>
<li class="chapter" data-level="1.5" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#you-cant-escape-uncertainty-in-science"><i class="fa fa-check"></i><b>1.5</b> You can’t escape uncertainty in science</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html"><i class="fa fa-check"></i><b>2</b> Scientific workflow: Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-questions"><i class="fa fa-check"></i><b>2.1</b> Research questions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#clarify-your-primary-goal-description-prediction-or-explanation"><i class="fa fa-check"></i><b>2.1.1</b> Clarify your primary goal: description, prediction, or explanation?</a></li>
<li class="chapter" data-level="2.1.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#identify-the-scope-of-inference-the-who-what-when-and-where-of-your-study."><i class="fa fa-check"></i><b>2.1.2</b> Identify the scope of inference: The who, what, when, and where of your study.</a></li>
<li class="chapter" data-level="2.1.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-interesting"><i class="fa fa-check"></i><b>2.1.3</b> Make it interesting</a></li>
<li class="chapter" data-level="2.1.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-answerable-with-data"><i class="fa fa-check"></i><b>2.1.4</b> Make it answerable with data</a></li>
<li class="chapter" data-level="2.1.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#ground-it-in-theory"><i class="fa fa-check"></i><b>2.1.5</b> Ground it in theory</a></li>
<li class="chapter" data-level="2.1.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-sure-its-feasible"><i class="fa fa-check"></i><b>2.1.6</b> Make sure it’s feasible</a></li>
<li class="chapter" data-level="2.1.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#avoid-analyzing-the-data-before-stating-your-question"><i class="fa fa-check"></i><b>2.1.7</b> Avoid analyzing the data before stating your question</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#connecting-ideas-to-data"><i class="fa fa-check"></i><b>2.2</b> Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#theory"><i class="fa fa-check"></i><b>2.2.1</b> Theory</a></li>
<li class="chapter" data-level="2.2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-question"><i class="fa fa-check"></i><b>2.2.2</b> Research question</a></li>
<li class="chapter" data-level="2.2.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#generative-model"><i class="fa fa-check"></i><b>2.2.3</b> Generative model</a></li>
<li class="chapter" data-level="2.2.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#study-design"><i class="fa fa-check"></i><b>2.2.4</b> Study design</a></li>
<li class="chapter" data-level="2.2.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimand"><i class="fa fa-check"></i><b>2.2.5</b> Estimand</a></li>
<li class="chapter" data-level="2.2.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#target-population"><i class="fa fa-check"></i><b>2.2.6</b> Target population</a></li>
<li class="chapter" data-level="2.2.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#sample-data"><i class="fa fa-check"></i><b>2.2.7</b> Sample data</a></li>
<li class="chapter" data-level="2.2.8" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#statistical-model"><i class="fa fa-check"></i><b>2.2.8</b> Statistical model</a></li>
<li class="chapter" data-level="2.2.9" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimate"><i class="fa fa-check"></i><b>2.2.9</b> Estimate</a></li>
<li class="chapter" data-level="2.2.10" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#summary"><i class="fa fa-check"></i><b>2.2.10</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to Data and R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#an-introduction-to-data"><i class="fa fa-check"></i><b>3.1</b> An introduction to data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variables-and-observations"><i class="fa fa-check"></i><b>3.1.1</b> Variables and observations</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#types-of-variables"><i class="fa fa-check"></i><b>3.1.2</b> Types of variables</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#relationships-between-variables"><i class="fa fa-check"></i><b>3.1.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variable-naming-conventions-and-metadata"><i class="fa fa-check"></i><b>3.1.4</b> Variable naming conventions and metadata</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#introduction-to-r"><i class="fa fa-check"></i><b>3.2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>3.2.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#the-rstudio-interface"><i class="fa fa-check"></i><b>3.2.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#basic-data-manipulation-in-r"><i class="fa fa-check"></i><b>3.2.3</b> Basic data manipulation in R</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#scripting"><i class="fa fa-check"></i><b>3.2.4</b> Scripting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>4</b> Describing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="describing-data.html"><a href="describing-data.html#defining-the-population"><i class="fa fa-check"></i><b>4.1</b> Defining the population</a></li>
<li class="chapter" data-level="4.2" data-path="describing-data.html"><a href="describing-data.html#loading-data-into-r"><i class="fa fa-check"></i><b>4.2</b> Loading data into R</a></li>
<li class="chapter" data-level="4.3" data-path="describing-data.html"><a href="describing-data.html#inspecting-the-dataset"><i class="fa fa-check"></i><b>4.3</b> Inspecting the dataset</a></li>
<li class="chapter" data-level="4.4" data-path="describing-data.html"><a href="describing-data.html#describing-single-variables"><i class="fa fa-check"></i><b>4.4</b> Describing single variables</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="describing-data.html"><a href="describing-data.html#qualitative-variables"><i class="fa fa-check"></i><b>4.4.1</b> Qualitative variables</a></li>
<li class="chapter" data-level="4.4.2" data-path="describing-data.html"><a href="describing-data.html#quantitative-variables"><i class="fa fa-check"></i><b>4.4.2</b> Quantitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="describing-data.html"><a href="describing-data.html#describing-relationships-between-variables"><i class="fa fa-check"></i><b>4.5</b> Describing relationships between variables</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-variables"><i class="fa fa-check"></i><b>4.5.1</b> Associations between quantitative variables</a></li>
<li class="chapter" data-level="4.5.2" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-and-qualitative-variables"><i class="fa fa-check"></i><b>4.5.2</b> Associations between quantitative and qualitative variables</a></li>
<li class="chapter" data-level="4.5.3" data-path="describing-data.html"><a href="describing-data.html#associations-between-qualitative-variables"><i class="fa fa-check"></i><b>4.5.3</b> Associations between qualitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="describing-data.html"><a href="describing-data.html#next-steps"><i class="fa fa-check"></i><b>4.6</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html"><i class="fa fa-check"></i><b>5</b> Uncertainty from sampling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sampling-requires-estimation"><i class="fa fa-check"></i><b>5.1</b> Sampling requires estimation</a></li>
<li class="chapter" data-level="5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#parameters-estimates-estimands"><i class="fa fa-check"></i><b>5.2</b> Parameters, estimates, estimands</a></li>
<li class="chapter" data-level="5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sources-of-uncertainty-from-sampling"><i class="fa fa-check"></i><b>5.3</b> Sources of uncertainty from sampling</a></li>
<li class="chapter" data-level="5.4" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy-and-precision"><i class="fa fa-check"></i><b>5.4</b> Accuracy and precision</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy"><i class="fa fa-check"></i><b>5.4.1</b> Accuracy</a></li>
<li class="chapter" data-level="5.4.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#precision"><i class="fa fa-check"></i><b>5.4.2</b> Precision</a></li>
<li class="chapter" data-level="5.4.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#considering-accuracy-and-precision-together"><i class="fa fa-check"></i><b>5.4.3</b> Considering accuracy and precision together</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#maximizing-accuracy-and-precision-of-estimates"><i class="fa fa-check"></i><b>5.5</b> Maximizing accuracy and precision of estimates</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#random-sampling"><i class="fa fa-check"></i><b>5.5.1</b> Random sampling</a></li>
<li class="chapter" data-level="5.5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#replication"><i class="fa fa-check"></i><b>5.5.2</b> Replication</a></li>
<li class="chapter" data-level="5.5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#take-home-points"><i class="fa fa-check"></i><b>5.5.3</b> Take-home points</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html"><i class="fa fa-check"></i><b>6</b> Probability as the Language of Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#defining-probability"><i class="fa fa-check"></i><b>6.1</b> Defining probability</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#frequentist-definition"><i class="fa fa-check"></i><b>6.1.1</b> Frequentist definition</a></li>
<li class="chapter" data-level="6.1.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#bayesian-definition"><i class="fa fa-check"></i><b>6.1.2</b> Bayesian definition</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#probability-rules"><i class="fa fa-check"></i><b>6.2</b> Probability rules</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#individual-events"><i class="fa fa-check"></i><b>6.2.1</b> Individual events</a></li>
<li class="chapter" data-level="6.2.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#joint-events"><i class="fa fa-check"></i><b>6.2.2</b> Joint events</a></li>
<li class="chapter" data-level="6.2.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#general-addition-rule"><i class="fa fa-check"></i><b>6.2.3</b> General addition rule</a></li>
<li class="chapter" data-level="6.2.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#quantifying-marginal-probabilities"><i class="fa fa-check"></i><b>6.2.4</b> Quantifying marginal probabilities</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions"><i class="fa fa-check"></i><b>6.3</b> Sampling from probability distributions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-populations-is-probabalistic"><i class="fa fa-check"></i><b>6.3.1</b> Sampling from populations is probabalistic</a></li>
<li class="chapter" data-level="6.3.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#discrete-random-variables"><i class="fa fa-check"></i><b>6.3.2</b> Discrete random variables</a></li>
<li class="chapter" data-level="6.3.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#continuous-random-variables"><i class="fa fa-check"></i><b>6.3.3</b> Continuous random variables</a></li>
<li class="chapter" data-level="6.3.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions-1"><i class="fa fa-check"></i><b>6.3.4</b> Sampling from probability distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html"><i class="fa fa-check"></i><b>7</b> Bayesian estimation and inference</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#scientific-workflow-for-the-problem"><i class="fa fa-check"></i><b>7.1</b> Scientific workflow for the problem</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#theory-and-the-research-question"><i class="fa fa-check"></i><b>7.1.1</b> Theory and the research question</a></li>
<li class="chapter" data-level="7.1.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#generative-model-and-estimand"><i class="fa fa-check"></i><b>7.1.2</b> Generative model and estimand</a></li>
<li class="chapter" data-level="7.1.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-and-estimate"><i class="fa fa-check"></i><b>7.1.3</b> Statistical model and estimate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#bayes-theorem"><i class="fa fa-check"></i><b>7.2</b> Bayes Theorem</a></li>
<li class="chapter" data-level="7.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#applying-bayes-theorem-to-statistical-analysis"><i class="fa fa-check"></i><b>7.3</b> Applying Bayes Theorem to statistical analysis</a></li>
<li class="chapter" data-level="7.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#steps-of-estimation-with-bayesian-inference"><i class="fa fa-check"></i><b>7.4</b> Steps of estimation with Bayesian inference</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specify-the-prior-distribution"><i class="fa fa-check"></i><b>7.4.1</b> Specify the prior distribution</a></li>
<li class="chapter" data-level="7.4.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-likelihood-of-the-data"><i class="fa fa-check"></i><b>7.4.2</b> Quantify the likelihood of the data</a></li>
<li class="chapter" data-level="7.4.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-total-probability-of-the-data-marginal-likelihood"><i class="fa fa-check"></i><b>7.4.3</b> Quantify the total probability of the data (marginal likelihood)</a></li>
<li class="chapter" data-level="7.4.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-posterior-distribution"><i class="fa fa-check"></i><b>7.4.4</b> Quantify the posterior distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#summarizing-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5</b> Summarizing the posterior distribution</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#sampling-from-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5.1</b> Sampling from the posterior distribution</a></li>
<li class="chapter" data-level="7.5.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#central-tendency-and-variance"><i class="fa fa-check"></i><b>7.5.2</b> Central tendency and variance</a></li>
<li class="chapter" data-level="7.5.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#intervals"><i class="fa fa-check"></i><b>7.5.3</b> Intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-priors"><i class="fa fa-check"></i><b>7.6</b> Specifying priors</a></li>
<li class="chapter" data-level="7.7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#decision-making"><i class="fa fa-check"></i><b>7.7</b> Decision making</a></li>
<li class="chapter" data-level="7.8" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-and-fitting-statistical-models-with-bayes"><i class="fa fa-check"></i><b>7.8</b> Specifying and fitting statistical models with Bayes</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-specification"><i class="fa fa-check"></i><b>7.8.1</b> Statistical model specification</a></li>
<li class="chapter" data-level="7.8.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#fitting-models-with-brms"><i class="fa fa-check"></i><b>7.8.2</b> Fitting models with <em>brms</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html"><i class="fa fa-check"></i><b>8</b> Bayesian Workflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#step-1-choose-an-appropriate-model-for-the-likelihood"><i class="fa fa-check"></i><b>8.1</b> Step 1: Choose an appropriate model for the likelihood</a></li>
<li class="chapter" data-level="8.2" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#step-2-decide-on-prior-distributions-for-each-parameter-in-the-likelihood"><i class="fa fa-check"></i><b>8.2</b> Step 2: Decide on prior distributions for each parameter in the likelihood</a></li>
<li class="chapter" data-level="8.3" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#step-3-prior-predictive-check"><i class="fa fa-check"></i><b>8.3</b> Step 3: Prior predictive check</a></li>
<li class="chapter" data-level="8.4" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#step-4-fit-the-statistical-model-with-the-observed-data"><i class="fa fa-check"></i><b>8.4</b> Step 4: Fit the statistical model with the observed data</a></li>
<li class="chapter" data-level="8.5" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#step-5-evaluating-and-applying-a-fitted-model"><i class="fa fa-check"></i><b>8.5</b> Step 5: Evaluating and applying a fitted model</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#a-quick-glance-at-the-estimates"><i class="fa fa-check"></i><b>8.5.1</b> A quick glance at the estimates</a></li>
<li class="chapter" data-level="8.5.2" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#checking-for-convergence"><i class="fa fa-check"></i><b>8.5.2</b> Checking for convergence</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#checking-the-shape-of-the-posterior-distribution"><i class="fa fa-check"></i><b>8.6</b> Checking the shape of the posterior distribution</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#inference-and-posterior-predictive-check"><i class="fa fa-check"></i><b>8.6.1</b> Inference and posterior predictive check</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#summary-1"><i class="fa fa-check"></i><b>8.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-linear-model.html"><a href="the-linear-model.html"><i class="fa fa-check"></i><b>9</b> The linear model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-linear-model.html"><a href="the-linear-model.html#statistical-models"><i class="fa fa-check"></i><b>9.1</b> Statistical models</a></li>
<li class="chapter" data-level="9.2" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-model"><i class="fa fa-check"></i><b>9.2</b> Linear model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="the-linear-model.html"><a href="the-linear-model.html#basic-structure-of-the-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> Basic structure of the linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="the-linear-model.html"><a href="the-linear-model.html#fitting-the-linear-model-in-brms"><i class="fa fa-check"></i><b>9.2.2</b> Fitting the linear model in brms</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-models-with-categorical-predictors"><i class="fa fa-check"></i><b>9.3</b> Linear models with categorical predictors</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="the-linear-model.html"><a href="the-linear-model.html#binary-explanatory-variables"><i class="fa fa-check"></i><b>9.3.1</b> Binary explanatory variables</a></li>
<li class="chapter" data-level="9.3.2" data-path="the-linear-model.html"><a href="the-linear-model.html#categorical-predictors-with-more-than-two-categories"><i class="fa fa-check"></i><b>9.3.2</b> Categorical predictors with more than two categories</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html"><i class="fa fa-check"></i><b>10</b> Graphical Causal Models</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>10.1</b> Directed acyclic graphs (DAGs)</a></li>
<li class="chapter" data-level="10.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#three-causal-structures-in-dags"><i class="fa fa-check"></i><b>10.2</b> Three causal structures in DAGs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-fork-confounders"><i class="fa fa-check"></i><b>10.2.1</b> The fork: confounders</a></li>
<li class="chapter" data-level="10.2.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-pipe-mediators"><i class="fa fa-check"></i><b>10.2.2</b> The pipe: mediators</a></li>
<li class="chapter" data-level="10.2.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-inverted-fork-colliders"><i class="fa fa-check"></i><b>10.2.3</b> The inverted fork: colliders</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#closing-backdoor-paths"><i class="fa fa-check"></i><b>10.3</b> Closing backdoor paths</a></li>
<li class="chapter" data-level="10.4" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#like-all-models-dags-require-assumptions"><i class="fa fa-check"></i><b>10.4</b> Like all models, DAGs require assumptions</a></li>
<li class="chapter" data-level="10.5" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#types-of-study-designs"><i class="fa fa-check"></i><b>10.5</b> Types of Study Designs</a></li>
<li class="chapter" data-level="10.6" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#experimental-studies"><i class="fa fa-check"></i><b>10.6</b> Experimental studies</a></li>
<li class="chapter" data-level="10.7" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#observational-studies"><i class="fa fa-check"></i><b>10.7</b> Observational studies</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#pros-and-cons-of-prospective-vs.-retrospective-studies-planned"><i class="fa fa-check"></i><b>10.7.1</b> Pros and cons of prospective vs. retrospective studies (planned)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html"><i class="fa fa-check"></i><b>11</b> Causal inference with linear models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#linear-models-with-multiple-predictor-variables"><i class="fa fa-check"></i><b>11.1</b> Linear models with multiple predictor variables</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#generic-linear-model-with-two-predictors"><i class="fa fa-check"></i><b>11.1.1</b> Generic linear model with two predictors</a></li>
<li class="chapter" data-level="11.1.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#multiple-regression-model-for-the-ice-cream-and-drownings-example"><i class="fa fa-check"></i><b>11.1.2</b> Multiple regression model for the ice cream and drownings example</a></li>
<li class="chapter" data-level="11.1.3" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prior-predictive-check"><i class="fa fa-check"></i><b>11.1.3</b> Prior predictive check</a></li>
<li class="chapter" data-level="11.1.4" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#fitting-the-multiple-regression-model"><i class="fa fa-check"></i><b>11.1.4</b> Fitting the multiple regression model</a></li>
<li class="chapter" data-level="11.1.5" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prediction-plots-for-multiple-regression-models"><i class="fa fa-check"></i><b>11.1.5</b> Prediction plots for multiple regression models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#dag-informed-predictors-categorical-variables-what-multiple-regression-is-doing-with-predictor-residual-plot"><i class="fa fa-check"></i><b>11.2</b> DAG-informed predictors, categorical variables, what multiple regression is doing with predictor residual plot</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="interaction-effects.html"><a href="interaction-effects.html"><i class="fa fa-check"></i><b>12</b> Interaction effects</a></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized linear models</a></li>
<li class="chapter" data-level="14" data-path="multilevel-models.html"><a href="multilevel-models.html"><i class="fa fa-check"></i><b>14</b> Multilevel models</a></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html"><i class="fa fa-check"></i><b>A</b> Estimation with frequentist inference</a>
<ul>
<li class="chapter" data-level="A.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#frequentist-estimates-are-point-estimates"><i class="fa fa-check"></i><b>A.1</b> Frequentist estimates are point estimates</a></li>
<li class="chapter" data-level="A.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions"><i class="fa fa-check"></i><b>A.2</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-are-centered-on-the-true-parameter-value"><i class="fa fa-check"></i><b>A.2.1</b> Sampling distributions are centered on the true parameter value</a></li>
<li class="chapter" data-level="A.2.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-allow-us-to-estimate-precision"><i class="fa fa-check"></i><b>A.2.2</b> Sampling distributions allow us to estimate precision</a></li>
<li class="chapter" data-level="A.2.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sample-size-affects-the-shape-of-sampling-distributions"><i class="fa fa-check"></i><b>A.2.3</b> Sample size affects the shape of sampling distributions</a></li>
<li class="chapter" data-level="A.2.4" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#summary-points-on-sampling-distributions"><i class="fa fa-check"></i><b>A.2.4</b> Summary points on sampling distributions</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#quantifying-uncertainty-standard-error-and-confidence-intervals"><i class="fa fa-check"></i><b>A.3</b> Quantifying uncertainty: standard error and confidence intervals</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#standard-error"><i class="fa fa-check"></i><b>A.3.1</b> Standard error</a></li>
<li class="chapter" data-level="A.3.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#confidence-intervals"><i class="fa fa-check"></i><b>A.3.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="A.3.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#the-standard-normal-approximation-does-not-work-well-under-low-sample-size"><i class="fa fa-check"></i><b>A.3.3</b> The standard normal approximation does not work well under low sample size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html"><i class="fa fa-check"></i><b>B</b> Decision-making with frequentist estimates</a>
<ul>
<li class="chapter" data-level="B.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#framework-of-classical-hypothesis-testing"><i class="fa fa-check"></i><b>B.1</b> Framework of classical hypothesis testing</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#state-null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>B.1.1</b> State null and alternative hypotheses</a></li>
<li class="chapter" data-level="B.1.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#assume-the-null-hypothesis-is-true"><i class="fa fa-check"></i><b>B.1.2</b> Assume the null hypothesis is true</a></li>
<li class="chapter" data-level="B.1.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#quantify-the-likelihood-of-the-data-under-the-null-hypothesis-p-values"><i class="fa fa-check"></i><b>B.1.3</b> Quantify the likelihood of the data under the null hypothesis: P-values</a></li>
<li class="chapter" data-level="B.1.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-a-decision-based-on-the-p-value-and-significance-value"><i class="fa fa-check"></i><b>B.1.4</b> Making a decision based on the P-value and significance value</a></li>
<li class="chapter" data-level="B.1.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#decision-errors-happen"><i class="fa fa-check"></i><b>B.1.5</b> Decision errors happen</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-decisions-with-confidence-intervals"><i class="fa fa-check"></i><b>B.2</b> Making decisions with confidence intervals</a></li>
<li class="chapter" data-level="B.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#issues-with-the-null-hypothesis-framework"><i class="fa fa-check"></i><b>B.3</b> Issues with the null hypothesis framework</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#significance-testing-reinforces-binary-thinking"><i class="fa fa-check"></i><b>B.3.1</b> Significance testing reinforces binary thinking</a></li>
<li class="chapter" data-level="B.3.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-testing-reinforces-gamification-in-science"><i class="fa fa-check"></i><b>B.3.2</b> Statistical testing reinforces gamification in science</a></li>
<li class="chapter" data-level="B.3.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-significance-is-not-the-same-thing-as-practical-significance"><i class="fa fa-check"></i><b>B.3.3</b> Statistical significance is not the same thing as practical significance</a></li>
<li class="chapter" data-level="B.3.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#type-i-errors-become-more-likely-with-multiple-tests"><i class="fa fa-check"></i><b>B.3.4</b> Type I errors become more likely with multiple tests</a></li>
<li class="chapter" data-level="B.3.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-is-almost-certainly-wrong"><i class="fa fa-check"></i><b>B.3.5</b> The null hypothesis is almost certainly wrong</a></li>
<li class="chapter" data-level="B.3.6" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-focuses-on-data-you-did-not-observe"><i class="fa fa-check"></i><b>B.3.6</b> The null hypothesis focuses on data you did not observe</a></li>
<li class="chapter" data-level="B.3.7" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#a-single-null-and-alternative-hypothesis-is-too-constraining"><i class="fa fa-check"></i><b>B.3.7</b> A single null and alternative hypothesis is too constraining</a></li>
<li class="chapter" data-level="B.3.8" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-p-value-is-not-the-probability-we-want"><i class="fa fa-check"></i><b>B.3.8</b> The P-value is not the probability we want</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Research Design and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bayesian-workflow" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Bayesian Workflow<a href="bayesian-workflow.html#bayesian-workflow" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter we extend the process Bayesian estimation in two ways. First, we will look at estimation of a model with parameters for a continuous random variable. Second, we will begin practicing a consistent approach to estimating parameters that includes explicit steps of picking an appropriate statistical model, checking the performance of the model with chosen prior distributions, fitting the model, and checking the performance of the fitted model. This kind of systematic approach to model selection and checking is called <strong>Bayesian workflow</strong>. To explore the components of Bayesian workflow in this chapter, we will consider the following question: What is the average resting heart rate for adults in the United States?</p>
<p>The data we’ll this chapter use are included in an R packages called <em>NHANES</em>, which stands for the U.S. National Health and Nutrition Examination study. NHANES is a survey of a variety of health parameters for people in the U.S. Let’s start by loading the data:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="bayesian-workflow.html#cb238-1" tabindex="-1"></a><span class="co">#install.packages(&quot;NHANES&quot;) #install the package if necessary</span></span>
<span id="cb238-2"><a href="bayesian-workflow.html#cb238-2" tabindex="-1"></a><span class="fu">library</span>(NHANES) <span class="co">#load the package</span></span>
<span id="cb238-3"><a href="bayesian-workflow.html#cb238-3" tabindex="-1"></a><span class="fu">data</span>(NHANES) <span class="co">#load the dataframe NHANES</span></span>
<span id="cb238-4"><a href="bayesian-workflow.html#cb238-4" tabindex="-1"></a>d <span class="ot">&lt;-</span> NHANES <span class="co">#simplify the name of the data frame</span></span></code></pre></div>
<p>Running the code above produces a data frame called <code>d</code>. I encourage you to look at the structure of the full dataframe (<code>str(d)</code>), which includes dozens of variables, but for now let’s turn our attention to a summary of two variabiles of interest: <code>Age</code> (years) and <code>Pulse</code> (resting heart rate in beats per minute, bpm).</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="bayesian-workflow.html#cb239-1" tabindex="-1"></a><span class="fu">summary</span>(d[, <span class="fu">c</span>(<span class="st">&quot;Age&quot;</span>,<span class="st">&quot;Pulse&quot;</span>)])</span></code></pre></div>
<pre><code>##       Age            Pulse       
##  Min.   : 0.00   Min.   : 40.00  
##  1st Qu.:17.00   1st Qu.: 64.00  
##  Median :36.00   Median : 72.00  
##  Mean   :36.74   Mean   : 73.56  
##  3rd Qu.:54.00   3rd Qu.: 82.00  
##  Max.   :80.00   Max.   :136.00  
##                  NA&#39;s   :1437</code></pre>
<p>You can see based on the summary distribution of each variable that the
sample includes individuals of any age. For our research question, we
will focus on estimating the average resting heart rate of <em>adults</em> in
the U.S. We can subset the data to remove individuals under 18 years
old, leaving observations for 7216 adults (excluding missing observations):</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="bayesian-workflow.html#cb241-1" tabindex="-1"></a>d <span class="ot">&lt;-</span> d[d<span class="sc">$</span>Age <span class="sc">&gt;=</span><span class="dv">18</span>, ]</span>
<span id="cb241-2"><a href="bayesian-workflow.html#cb241-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(d<span class="sc">$</span>Pulse)) <span class="co">#sample size</span></span></code></pre></div>
<pre><code>## [1] 7216</code></pre>
<div id="step-1-choose-an-appropriate-model-for-the-likelihood" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Step 1: Choose an appropriate model for the likelihood<a href="bayesian-workflow.html#step-1-choose-an-appropriate-model-for-the-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How are the observed data of resting heart rates <em>generated</em>? That’s the question we have to address first. We need a model that characterizes how our sample data are created. In the broader context of scientific workflow introduced in Chapter 2, this process represents the arrow from the generative model to the statistical model. We need a statistical model that adequately represents the assumptions made in the generative model.</p>
<p>In the last chapter, our main example focused on estimating the prevalence of a respiratory infection in a population. The observed data consisted of <em>X</em> people who tested positive for the infection out of a sample of <em>N</em> people tested. When we do statistical analysis, we have to make a decision about how best to characterize how the observed data were generated. This part of our statistical model is called the <strong>likelihood model</strong>. For infection prevalence, we recognized that the observed data was a discrete random variable that could be described by the binomial distribution. The binomial distribution simply functioned as a model we thought was appropriate to describe how the observed number of infections was generated given the true probability of infection (the parameter we wanted to learn) and the number of people sampled.</p>
<p>We’re going to need a different kind of likelihood model for estimating the mean resting heart rate. Resting heart rate is a continuous random variable, so the binomial distribution isn’t an appropriate description of how heart rates are generated and observed. As we learned in Chapter 6, one probability distribution that can be useful for describing a continuous random variable is the normal (Gaussian) distribution. The normal distribution isn’t the only probability distribution that describes continuous random variables, and for some continuous variables we need something else, but it’s a good starting point.</p>
<p>So the first step in Bayesian workflow is selecting an appropriate likelihood model, and for resting heart rate we’ll use the normal distribution for this purpose. By using the normal distribution, we assume resting heart rates are observed at random with variation around a population mean (<span class="math inline">\(\mu\)</span>) and with among-individual variation described by a standard deviation (<span class="math inline">\(\sigma\)</span>). We also assume that heart rate is measured without error.</p>
<p>Unlike the binomial distribution - which has just a single parameter - the normal distribution has two parameters - mean and standard deviation. Because we are assuming heart rates come from a normal distribution, we have to include both the mean and the standard deviation in our likelihood model. Indeed, when we assume a variable is drawn from a particular probability distribution, we have to estimate (or assume values for) all the parameters for that probability distribution whether we want them or not. That’s why it’s useful to differentiate between types of parameters, the estimands being the parameters that we are most interested in.</p>
<p>Here’s how we can communicate our choice of the normal distribution for the likelihood with statistical notation:</p>
<p><span class="math display">\[
r_i \sim \mathrm{Normal}(\mu, \sigma)
\]</span></p>
<p>What does the likelihood model say? Here we are defining the observed values of heart rate <em>r</em> for each individual <em>i</em> as a random variable following a normal distribution with parameters mean = <span class="math inline">\(\mu\)</span> and standard deviation = <span class="math inline">\(\sigma\)</span>. Remember the tilde symbol (~) defines a relationship as stochastic, meaning the observed values <span class="math inline">\(r_i\)</span> are probabilistic. The normal distribution with its parameters defines the probability of drawing particular values of heart rate. We don’t know what those parameter values are, so we will have to estimate them.</p>
</div>
<div id="step-2-decide-on-prior-distributions-for-each-parameter-in-the-likelihood" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Step 2: Decide on prior distributions for each parameter in the likelihood<a href="bayesian-workflow.html#step-2-decide-on-prior-distributions-for-each-parameter-in-the-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Once your likelihood model is defined, it is necessary to define prior distributions for <em>every</em> parameter in the likelihood model. How should we go about doing this? At this point in the book I want to introduce two considerations for choosing priors. Prior distributions should be selected in a way that a) respects the mathematical constraints of the parameter of interest and b) allows us to adequately specify our beliefs about values of the parameters that are more or less likely based on our prior knowledge.</p>
<p>First, consider the mathematical constraints of a parameter. Remember our example in the last chapter about estimating the prevalence of an infection? Our model for infection prevalence had just a single parameter, the probability of infection. Probability is bounded between the values of 0 and 1, so it is wise to choose a prior distribution that respects those boundaries. That’s why we eventually landed on using the beta distribution as an appropriate probability distribution for the prior, as the beta distribution is bounded between 0 and 1. It makes values outside of the bounds of 0 and 1 impossible, and that makes good mathematical sense.</p>
<p>Let’s apply this principle to the question before us this chapter of estimating the mean resting heart rate. Our likelihood model has two parameters, the mean and standard deviation, so we need a prior for both. Let’s consider the mean first. Are there any mathematical constraints on the mean resting heart rate? The only constraint that comes to mind is that the mean resting heart rate can’t be negative. It could be any real positive value, but it can’t be less than 0.</p>
<p>Which probability distribution might be appropriate for the mean heart rate? At this point in the book we’ve encountered four probability distributions: binomial, uniform, beta, and normal. The binomial and beta distributions are clearly not appropriate in this case. What about the uniform distribution? Suppose we’re 100% confident that the mean resting heart rate of our target population is not less than 50 or greater than 100. We could specify a uniform prior for the mean that rules out values below 50 and above 100: <span class="math inline">\(\mu \sim \mathrm{Uniform}(50, 100)\)</span>, which meets our goal of respecting the mathematical constraints of the parameter, namely that the mean heart rate can’t be negative.</p>
<p>But now let’s consider our other goal of selecting a prior that adequately reflects our prior beliefts about the parameter. The downside of the uniform distribution is that it doesn’t give us any wiggle room to make some values within the range of 50 to 100 more likely than others. We might think the most plausible values for the mean resting heart rate are around 75 bpm, but the uniform distribution we defined says all the values between 50 and 100 are equally plausible. So let’s consider another possibility.</p>
<p>What about the normal distribution? Could we use the normal distribution to define a prior for the mean heart rate? It certainly addresses the problem we just faced with the uniform distribution in that we could specify a normal prior that makes values of the mean around 75 bpm more likely than other values. For example, suppose based on prior knowledge that you are 95% confident that the true mean resting heart rate is between 55 and 95 bpm, but it’s more likely to be around 75 than values at the margins. We could define the prior distribution for the mean with a normal distribution having a mean of 75 bpm and a standard deviation of 10 bpm: <span class="math inline">\(\mu \sim \mathrm{Normal}(75, 10)\)</span>. That’s a nice application of the empirical rule, which says that 95% of the values of a normal distribution are within two standard deviations of the mean. This could work!</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="bayesian-workflow.html#cb243-1" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">75</span></span>
<span id="cb243-2"><a href="bayesian-workflow.html#cb243-2" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb243-3"><a href="bayesian-workflow.html#cb243-3" tabindex="-1"></a></span>
<span id="cb243-4"><a href="bayesian-workflow.html#cb243-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(mu <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>sigma, mu <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span>sigma, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb243-5"><a href="bayesian-workflow.html#cb243-5" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">dens =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma))</span>
<span id="cb243-6"><a href="bayesian-workflow.html#cb243-6" tabindex="-1"></a></span>
<span id="cb243-7"><a href="bayesian-workflow.html#cb243-7" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> dens)) <span class="sc">+</span></span>
<span id="cb243-8"><a href="bayesian-workflow.html#cb243-8" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb243-9"><a href="bayesian-workflow.html#cb243-9" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb243-10"><a href="bayesian-workflow.html#cb243-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Mean resting heart rate (bpm)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb243-11"><a href="bayesian-workflow.html#cb243-11" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Prior distribution: &quot;</span>, mu, <span class="st">&quot; ~ Normal(75, 10)&quot;</span>))) <span class="sc">+</span></span>
<span id="cb243-12"><a href="bayesian-workflow.html#cb243-12" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c04-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>How did I know to use those particular values for the normal prior (mean = 75, standard deviation = 10). This is where domain knowledge is helpful. Based on prior knowledge from the medical literature and my own experience on track and cross country teams where we often measured our heart rates, I have a general sense about the most plausible values for average heart rate. I don’t know it for sure, but I think it’s around 75 bpm. It could be more or less, but I think it’s <em>very</em> unlikely that the <em>typical</em> heart rate is less than 50 bpm or over 100 bpm. I also don’t think it’s equally plausible that the mean heart rate is anywhere between 50 and 100 bpm. I think it’s most likely around 75, with decreasing probability moving away from 75. The normal distribution captures that prior knowledge nicely (albeit imperfectly, as every model is imperfect).</p>
<p>One potential problem with the normal distribution is that it it allows for values that are positive or negative. So here we face a trade-off. We’ve landed on a probability distribution that allows us to specify our prior belief about values near 70 bpm being most likely for the mean, but it allows negative values (as well as extremely high positive values, like one 10,000 bpm). What do we do? We have a few options. We could ditch the normal distribution and look around for another probability distribution that has a similar shape as the normal distribution (high probability density at the mean and lower elsewhere), but only allows for real values above zero. There are options, such as the gamma distribution. On the other hand, we could proceed with the normal distribution and be comfortable with the fact that the probability density of negative values and extreme positive values are minuscule. Remember that a Bayesian analysis uses both the prior <em>and</em> the observed data to quantify the posterior distribution that we make inferences with. Extremely unlikely values based on the prior probability alone will not have high posterior probability unless the observed data and likelihood model are very consistent with those values. So for now, let’s proceed with the normal distribution as our prior for the mean resting heart rate.</p>
<p>Wow, that was a lot of effort to select a prior distribution for just a single parameter in our likelihood model. And we still have another parameter to deal with! What should we select as a prior for the standard deviation? First, let’s just remember what the standard deviation represents. It represents the typical variation in resting heart rate among individuals in the target population. Admittedly, I feel like I know less about the variation among people in their heart rates than I do about the average heart rate. I wish I could just ignore the standard deviation, but because it’s a parameter in my likelihood model, it needs a prior.</p>
<p>Now although I don’t know much about variation in heart rates, I do know there’s a mathematical constraint we can respect. The standard deviation cannot be less than 0. Variation either exists, in which case the standard deviation is positive, or it doesn’t, in which case the standard deviation is 0. So I want to use a prior distribution that says the standard deviation is zero or positive values only, is possible.</p>
<p>How large could the standard deviation be? That’s where things are murky for me, although if I push myself, I do think there are some obvious limits that come to mind. For example, it seems absurd the the standard deviation could be something like 30 bpm. How do I know that? Well let’s suppose I’m right that the mean resting heart rate is 75 bpm. A normal distribution with a mean of 75 bpm and standard deviation of 30 bpm would allow a not insignificant portion of the population to have absurd resting heart rates, like less than 30 bpm (just 1.5 standard deviations below the mean) or greater than 110 bpm (just 1.5 standard deviations above the mean). A standard deviation of 30 bpm seems too high. What about 20 bpm? If I’m right that the mean resting heart rate is 75 bpm, a standard deviation of 20 bpm would imply that 95% of the population has a resting heart rate between 35 bpm and 115 bpm. Honestly that still seems too high, but I’m not sure where exactly to draw the line, so I’m going to draw it a tad higher than I think is believable.</p>
<p>Now you probably think that some values within the range of 0 to 20 bpm are more plausible for the standard deviation than others. I do too, and we could consider a normal distribution as our prior here. But I’m going to caution against that. Unlike the mean resting heart rate, the range of values for the standard deviation are much closer to 0, and I’m concerned about giving too much credence to negative values for the standard deviation. So for now, let’s choose a uniform distribution between 0 and 20 as our prior for the standard deviation: <span class="math inline">\(\mu \sim \mathrm{Uniform}(50, 100)\)</span>. This simply says that, before seeing the data, we consider any value of the standard deviation between 0 and 20 bpm to be equally plausible. The lower bound of 0 makes good sense because standard deviations cannot be negative (there can’t be negative variation). The upper bound of 20 bpm is also conservative. Uniform distributions can work well as prior distribution for paramter that are only positive and when we only know enough to define hard limits on possible values. Yet the uniform distribution isn’t completely uninformative. Indeed, it makes a rather strong assumption that values anywhere in the range of 0 and 20 are equally plausible, and other values are impossible.</p>
<p>So there we have it. We’ve selected a likelihood model, and we’ve selected prior distributions for each parameter in our likelihood model. This is our full statistical model that we’ve defined:</p>
<p><span class="math display">\[
\begin{array}{l}
r_i \sim \mathrm{Normal}(\mu, \sigma) \\
\mu \sim \mathrm{Normal}(75, 10) \\
\sigma \sim \mathrm{Uniform}(0, 20)
\end{array}
\]</span></p>
</div>
<div id="step-3-prior-predictive-check" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Step 3: Prior predictive check<a href="bayesian-workflow.html#step-3-prior-predictive-check" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Are the prior distributions we selected reasonable? We can - and indeed we should - interrogate this question before we fit the model. This is the goal of a <strong>prior predictive check</strong>. We want to formally look at what the prior distributions we selected imply about the data, independently of the observed data. For simple models like ours, this is a straightforward task that we can accomplish by simulating data. Our prior distributions allow for an infinite number of combinations of mean and stadnard deviation for the resting heart rate, but they make some combinations more likely than others. The goal here is to evaluate the <em>joint distribution</em> of the mean and standard deviation bsaed on the priors and ensure that we’re not implying values that make no sense.</p>
<p>Let’s simulate some data so you can see what I mean:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="bayesian-workflow.html#cb244-1" tabindex="-1"></a><span class="co">#from https://bookdown.org/content/4857/geocentric-models.html#a-language-for-describing-models</span></span>
<span id="cb244-2"><a href="bayesian-workflow.html#cb244-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb244-3"><a href="bayesian-workflow.html#cb244-3" tabindex="-1"></a></span>
<span id="cb244-4"><a href="bayesian-workflow.html#cb244-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb244-5"><a href="bayesian-workflow.html#cb244-5" tabindex="-1"></a></span>
<span id="cb244-6"><a href="bayesian-workflow.html#cb244-6" tabindex="-1"></a><span class="co">#randomly draw means from the prior</span></span>
<span id="cb244-7"><a href="bayesian-workflow.html#cb244-7" tabindex="-1"></a>mu.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">75</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb244-8"><a href="bayesian-workflow.html#cb244-8" tabindex="-1"></a></span>
<span id="cb244-9"><a href="bayesian-workflow.html#cb244-9" tabindex="-1"></a><span class="co">#randomly draw SDs from the prior</span></span>
<span id="cb244-10"><a href="bayesian-workflow.html#cb244-10" tabindex="-1"></a>sigma.sim <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">20</span>)</span>
<span id="cb244-11"><a href="bayesian-workflow.html#cb244-11" tabindex="-1"></a></span>
<span id="cb244-12"><a href="bayesian-workflow.html#cb244-12" tabindex="-1"></a><span class="co">#randomly draw values of resting heart rate from the combined means and SDs</span></span>
<span id="cb244-13"><a href="bayesian-workflow.html#cb244-13" tabindex="-1"></a>r.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu.sim, <span class="at">sd =</span> sigma.sim)</span>
<span id="cb244-14"><a href="bayesian-workflow.html#cb244-14" tabindex="-1"></a></span>
<span id="cb244-15"><a href="bayesian-workflow.html#cb244-15" tabindex="-1"></a><span class="co">#plot the simulated distribution of heart rates</span></span>
<span id="cb244-16"><a href="bayesian-workflow.html#cb244-16" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">r.sim =</span> r.sim)</span>
<span id="cb244-17"><a href="bayesian-workflow.html#cb244-17" tabindex="-1"></a></span>
<span id="cb244-18"><a href="bayesian-workflow.html#cb244-18" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> r.sim)) <span class="sc">+</span></span>
<span id="cb244-19"><a href="bayesian-workflow.html#cb244-19" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb244-20"><a href="bayesian-workflow.html#cb244-20" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Implied distribution of resting heart rate from priors&quot;</span>,</span>
<span id="cb244-21"><a href="bayesian-workflow.html#cb244-21" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Resting heart rate (bpm)&quot;</span>,</span>
<span id="cb244-22"><a href="bayesian-workflow.html#cb244-22" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb244-23"><a href="bayesian-workflow.html#cb244-23" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:c08c06"></span>
<img src="ch08_bayesianWorkflow_files/figure-html/c08c06-1.png" alt="TODO: caption." width="672" />
<p class="caption">
Figure 8.1: TODO: caption.
</p>
</div>
<p>What is this code doing? First, we randomly draw 10,000 values of the mean resting heart rate from the prior distribution that we defined for the mean (a normal distribution with mean = 75 and SD = 10). Next, we randomly draw 10,000 values for the standard deviation from the prior distribution we defined for that parameter (a uniform distribution between 0 and 20). Finally, we randomly draw 10,000 values of individual resting heart rates from the normal distributions implied by the simualted means and standard deviations from our priors. Then we plot the implied distribution of resting heart rates.</p>
<p>What do we learn here? We can see the distribution of heart rate implied by the priors has a mean right around 75 bpm as expected, so that’s good. But what’s not good is that the variation around that mean looks a bit unrealistic. The priors are implying that people (albeit only a few) can have a resting heart rate of 0 or even negative values, or resting heart rates approaching 150 bpm. Good thing we did this prior predictive simulation. This is exactly why you’d do such a thing; to see if the priors you assumed are realistic. Clearly the priors we’re using can be improved.</p>
<p>How should we improve the priors? We have two choices here, we could tighten the normal distribution for the mean, and we could reduce the maximum value for the standard deviation. Either of those alone should tighten the distribution of resting heart rates implied by the priors. I’m going to suggest we do both. Let’s tighten the normal prior for the mean to have a mean of 75 and standard deviation of 7.5 (implying a 95% probability that the mean resting heart rate is between 60 and 90; still probabily a bit wide). Let’s also trim the upper bound of the standard deviation to 15 bpm. Here’s our revised statistical model:</p>
<p><span class="math display">\[
\begin{array}{l}
r_i \sim \mathrm{Normal}(\mu, \sigma) \\
\mu \sim \mathrm{Normal}(75, 7.5) \\
\sigma \sim \mathrm{Uniform}(0, 15)
\end{array}
\]</span>
Now let’s see if that implies a more realistic distribution of resting heart rates:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="bayesian-workflow.html#cb245-1" tabindex="-1"></a><span class="co">#from https://bookdown.org/content/4857/geocentric-models.html#a-language-for-describing-models</span></span>
<span id="cb245-2"><a href="bayesian-workflow.html#cb245-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb245-3"><a href="bayesian-workflow.html#cb245-3" tabindex="-1"></a></span>
<span id="cb245-4"><a href="bayesian-workflow.html#cb245-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb245-5"><a href="bayesian-workflow.html#cb245-5" tabindex="-1"></a></span>
<span id="cb245-6"><a href="bayesian-workflow.html#cb245-6" tabindex="-1"></a><span class="co">#randomly draw means from the prior</span></span>
<span id="cb245-7"><a href="bayesian-workflow.html#cb245-7" tabindex="-1"></a>mu.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">75</span>, <span class="at">sd =</span> <span class="fl">7.5</span>)</span>
<span id="cb245-8"><a href="bayesian-workflow.html#cb245-8" tabindex="-1"></a></span>
<span id="cb245-9"><a href="bayesian-workflow.html#cb245-9" tabindex="-1"></a><span class="co">#randomly draw SDs from the prior</span></span>
<span id="cb245-10"><a href="bayesian-workflow.html#cb245-10" tabindex="-1"></a>sigma.sim <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">15</span>)</span>
<span id="cb245-11"><a href="bayesian-workflow.html#cb245-11" tabindex="-1"></a></span>
<span id="cb245-12"><a href="bayesian-workflow.html#cb245-12" tabindex="-1"></a><span class="co">#randomly draw values of resting heart rate from the combined means and SDs</span></span>
<span id="cb245-13"><a href="bayesian-workflow.html#cb245-13" tabindex="-1"></a>r.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu.sim, <span class="at">sd =</span> sigma.sim)</span>
<span id="cb245-14"><a href="bayesian-workflow.html#cb245-14" tabindex="-1"></a></span>
<span id="cb245-15"><a href="bayesian-workflow.html#cb245-15" tabindex="-1"></a><span class="co">#plot the simulated distribution of heart rates</span></span>
<span id="cb245-16"><a href="bayesian-workflow.html#cb245-16" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">r.sim =</span> r.sim)</span>
<span id="cb245-17"><a href="bayesian-workflow.html#cb245-17" tabindex="-1"></a></span>
<span id="cb245-18"><a href="bayesian-workflow.html#cb245-18" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> r.sim)) <span class="sc">+</span></span>
<span id="cb245-19"><a href="bayesian-workflow.html#cb245-19" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb245-20"><a href="bayesian-workflow.html#cb245-20" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Implied distribution of resting heart rate from priors&quot;</span>,</span>
<span id="cb245-21"><a href="bayesian-workflow.html#cb245-21" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Resting heart rate (bpm)&quot;</span>,</span>
<span id="cb245-22"><a href="bayesian-workflow.html#cb245-22" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb245-23"><a href="bayesian-workflow.html#cb245-23" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:c08c07"></span>
<img src="ch08_bayesianWorkflow_files/figure-html/c08c07-1.png" alt="TODO: caption." width="672" />
<p class="caption">
Figure 8.2: TODO: caption.
</p>
</div>
<p>Now we see no negative values implied by the priors, and the upper extreme values have been reduced to a maximum of around 125 bpm. Honestly these prior may still be a bit too wide, but those extreme values are very rare, and the data will have a lot to say about where the posterior distributions end up. Let’s proceed!</p>
</div>
<div id="step-4-fit-the-statistical-model-with-the-observed-data" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Step 4: Fit the statistical model with the observed data<a href="bayesian-workflow.html#step-4-fit-the-statistical-model-with-the-observed-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With our statistical model in defined, let’s proceed to estimate the parameters in <code>brms</code>:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="bayesian-workflow.html#cb246-1" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb246-2"><a href="bayesian-workflow.html#cb246-2" tabindex="-1"></a></span>
<span id="cb246-3"><a href="bayesian-workflow.html#cb246-3" tabindex="-1"></a><span class="co">#Likelihood model: heart rates normally distributed</span></span>
<span id="cb246-4"><a href="bayesian-workflow.html#cb246-4" tabindex="-1"></a>m1.formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(Pulse <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="fu">gaussian</span>())</span>
<span id="cb246-5"><a href="bayesian-workflow.html#cb246-5" tabindex="-1"></a></span>
<span id="cb246-6"><a href="bayesian-workflow.html#cb246-6" tabindex="-1"></a><span class="co"># Priors:</span></span>
<span id="cb246-7"><a href="bayesian-workflow.html#cb246-7" tabindex="-1"></a><span class="co">#   Intercept (mu) ~ Normal(75, 10)</span></span>
<span id="cb246-8"><a href="bayesian-workflow.html#cb246-8" tabindex="-1"></a><span class="co">#   sigma ~ Uniform(0, 20)</span></span>
<span id="cb246-9"><a href="bayesian-workflow.html#cb246-9" tabindex="-1"></a>m1.prior <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb246-10"><a href="bayesian-workflow.html#cb246-10" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">75</span>, <span class="fl">7.5</span>), <span class="at">class =</span> <span class="st">&quot;Intercept&quot;</span>),</span>
<span id="cb246-11"><a href="bayesian-workflow.html#cb246-11" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">uniform</span>(<span class="dv">0</span>, <span class="dv">15</span>), <span class="at">class =</span> <span class="st">&quot;sigma&quot;</span>, <span class="at">lb =</span> <span class="dv">0</span>, <span class="at">ub =</span> <span class="dv">15</span>)</span>
<span id="cb246-12"><a href="bayesian-workflow.html#cb246-12" tabindex="-1"></a>)</span>
<span id="cb246-13"><a href="bayesian-workflow.html#cb246-13" tabindex="-1"></a></span>
<span id="cb246-14"><a href="bayesian-workflow.html#cb246-14" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb246-15"><a href="bayesian-workflow.html#cb246-15" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb246-16"><a href="bayesian-workflow.html#cb246-16" tabindex="-1"></a>  <span class="at">data =</span> d,</span>
<span id="cb246-17"><a href="bayesian-workflow.html#cb246-17" tabindex="-1"></a>  <span class="at">formula =</span> m1.formula,</span>
<span id="cb246-18"><a href="bayesian-workflow.html#cb246-18" tabindex="-1"></a>  <span class="at">prior =</span> m1.prior,</span>
<span id="cb246-19"><a href="bayesian-workflow.html#cb246-19" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">123</span>,</span>
<span id="cb246-20"><a href="bayesian-workflow.html#cb246-20" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb246-21"><a href="bayesian-workflow.html#cb246-21" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb246-22"><a href="bayesian-workflow.html#cb246-22" tabindex="-1"></a>)</span></code></pre></div>
<p>Let’s walk through this. We’ve defined the likelihood with the <code>bf</code> function, where the formula <code>Pulse ~ 1</code> tells <code>brms</code> that we want to fit a model with only an intercept, which is just a fancy way of saying we want the mean of the normal distribution that we specified with <code>family = gaussian</code> (recall “Gaussian” is another name for the normal distribution). We then define our priors. In <code>brms</code>, each parameter getting a prior needs a distribution for the prior. You can see we specify <code>normal(75, 7.5)</code> for the mean and <code>uniform(0, 15)</code> for the standard deviation in this case. The <code>class</code> argument is required to indicate the type of variable, here being an <code>Intercept</code> for the mean and <code>sigma</code> for the standard deviation. Note that when defining a uniform prio, you not only need to define the limits within the <code>uniform</code> call, but also with the <code>lb</code> and <code>ub</code> arguments. Any inconsistencies here will lead to an error.</p>
<p>I’ll just note right here that the process of fitting model can be much more complex than I’m suggesting in this section. For example, there are decisions to make about the particular MCMC engine to use, the number of chains to run, the length to run each chain (iterations), whether or not to thin the iterations, and how to fit the model efficiently using CPU’s in parallel. For the purpose of an introductory statistics book, I’ve chosen to leave many of these details out and using relatively consistent model fitting decisions, especially for the relatively simple models addressed in a beginner’s class. Thus you will almost always see that we fit models with four chains, 2000 iterations for each chain, 1000 iterations of warmup (more on that below), and with the chains fitted in parallel across four CPU’s (<code>cores</code>) for efficiency. I’ve set the <code>seed</code> value so that the particular output in this book is reproducable, and I’ve set the <code>refresh</code> argument to 0 to minimize the amount of messages you get from <code>brms</code> during model fitting. All of these decisions can and should be open for discussion when fitting a particular model, and often these settings will need to be adjusted. But I consider these more advanced topics better approached when you have a basic handle on the general steps of Bayesian analysis, and other books cover these topics in detail and much more effectively than I could here.</p>
</div>
<div id="step-5-evaluating-and-applying-a-fitted-model" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Step 5: Evaluating and applying a fitted model<a href="bayesian-workflow.html#step-5-evaluating-and-applying-a-fitted-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="a-quick-glance-at-the-estimates" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> A quick glance at the estimates<a href="bayesian-workflow.html#a-quick-glance-at-the-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After fitting the model, we print the model output (<code>print(m1)</code>) to see same basic numerical summaries of the posterior distributions for the parameters we estimated. Our estimate for the mean heart rate is listed under “Regression Coefficients” as the “Intercept”. Remember that our estimate is an entire probability distribution, and <code>brms</code> defaults to showing you the mean of the posterior as the “Estimate”. Thus we see that the mean of the posterior distribution for resting heart rate is 72.57 bpm. The “Est.Error” represents the standard deviation of the posterior distribution, and we also see limits of a 95% credible interval (CI). Based on the analysis, we can say there’s a 95% probability that the mean resting heart rate is between 72.30 bpm and 72.85 bpm.</p>
<p>In addition to the mean heart rate, we also get a posterior distribution for the standard deviation, here denoted “sigma” under “Further Distributional Parameters”. There we see the posterior mean is 11.96 bpm, and there’s a 95% probability that the standard deviation is between 11.77 and 12.15 bpm. Note that the credible intervals for the mean and standard deviation of resting heart rates are both quite narrow, indicating that we’ve estimated these parameters with a high degree of precision.</p>
</div>
<div id="checking-for-convergence" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Checking for convergence<a href="bayesian-workflow.html#checking-for-convergence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before you dive into applying the posterior distributions for inferences, one thing you need to do is see if the sampling algorithm (the MCMC process) reached a stable set of posterior distributions. Remember the MCMC process is basically using a sampling process to estimate the posterior distributions, starting with some initial values that are supplied by the user or internally by the algorithm. Early in the sampling process the sampled values are biased by the initial values and can vary widely from iteration to iteration. This is called a <strong>burn-in</strong> or <strong>warmup</strong> period, and we generally do not want to use samples from this period for estimation. Indeed, the samples from the defined warmup period are entirely discarded. If the estimation process goes well, the values in each iteration stabilize and remain consistent, and it is these consistent values that we want to use for inference. We use the term <strong>convergence</strong> to describe a sampler that has reached the point of stability for a parameter. tIndeed, the samples from the defined warmup period are entirely discarded.</p>
<p>In our models, we run the sampling process for 2000 iterations with a warmup period of 1000 iterations. This means the first 1000 iterations are dropped entirely, and only the final 1000 iterations are retained. This is done in parallel across four chains, so we end up with a total of 4000 sampled values for each parameter.</p>
<p>Although we are discarding the first 1000 iterations entirely, we still need to check that the sampling process reached convergence in the final 1000 iterations we’re retaining for inference. There are two ways we’ll evaluate convergence in this book. First, you can execute the <code>plot</code> function on the object for your fitted model, which will produce a plot fo the posterior distributions for each parameter, as well as <strong>trace plots</strong> that can be used to evaluate convergence qualitatively:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="bayesian-workflow.html#cb247-1" tabindex="-1"></a><span class="fu">plot</span>(m1)</span></code></pre></div>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c09-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>The left panel shows the posterior distributions for the mean (<code>b_Intercept</code>) and standard deviation (<code>sigma</code>) parameters, and the right side of the panel shows trace plots for each panel. Trace plots allow you to view the value of each parameter for each iteration of the model in each chain. What we’re looking for here is relative consistency in the parameter values <em>within and among</em> the chains, that is convergence of the parameter values. Notice that for both of these parameters, the sampled values in sequence are relatively consistent, and sampled values across the chains converged around the same values (i.e., the chains are <strong>well-mixed</strong>). These trace plots indicate solid convergence because the values for each chain overlap extensively and hover around a common value.</p>
<p>In addition to evaluating convergence qualitatively, we can also evaluate it numerically in the printed model output above. Note that for each parameter an <code>Rhat</code> value is reported. This is known as the **Gelman-Rubin statistic (<span class="math inline">\(\hat{R}\)</span>), and it reflects the degree of convergence of each parameter. Values close to 1 imply convergence, and we genearlly want to see <code>Rhat</code> values less than 1.01. The <code>Rhat</code> values for our two parameters are reported as 1.00, implying convergence of our model.</p>
</div>
</div>
<div id="checking-the-shape-of-the-posterior-distribution" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Checking the shape of the posterior distribution<a href="bayesian-workflow.html#checking-the-shape-of-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One other visual check you should make is of the posterior distributions, which can point to problems with the prior distributions (among other issues). For example, imagine that instead of using a uniform prior for the standard deviation between 0 and 15, I used a uniform prior between 0 and 12, which says the standard deviation can <em>only</em> take on values between 0 and 12. Values below 0 and above 12 are impossible.</p>
<p>Below is the output from the <code>plot</code> function for the fitted model using this new prior. Look closely at the posterior distribution for the standard deviation. Notice how the posterior distribution is strongly skewed to the left, with most of the values around 12 and a hard cut-off at 12? This is good evidence that the prior I used was too constraining, and that it’s very possible that the standard deviation takes on values greater than 12. Basically the observed data via the likelihood are saying the standard deviation may well be above 12, but my prior distribution doesn’t allow it. You can also see in the trace plot for the standard deviation that there’s a hard limit at 12. These are good signs that my priors need to be relaxed and the model refit.</p>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c10-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<div id="inference-and-posterior-predictive-check" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> Inference and posterior predictive check<a href="bayesian-workflow.html#inference-and-posterior-predictive-check" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we should make a detailed inspection and summary of the posterior distributions and draw conclusions if all looks good. We start this process by using the <code>as_draws_df</code> function to retrieve the samples.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="bayesian-workflow.html#cb248-1" tabindex="-1"></a><span class="co">#posterior samples</span></span>
<span id="cb248-2"><a href="bayesian-workflow.html#cb248-2" tabindex="-1"></a>m1.post <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as_draws_df</span>(m1))</span>
<span id="cb248-3"><a href="bayesian-workflow.html#cb248-3" tabindex="-1"></a><span class="fu">head</span>(m1.post)</span></code></pre></div>
<pre><code>##   b_Intercept    sigma Intercept    lprior      lp__ .chain .iteration .draw
## 1    72.60770 11.96995  72.60770 -5.692764 -28148.35      1          1     1
## 2    72.52242 11.87165  72.52242 -5.696455 -28148.70      1          2     2
## 3    72.48102 11.93042  72.48102 -5.698294 -28148.54      1          3     3
## 4    72.56183 11.83219  72.56183 -5.694733 -28149.06      1          4     4
## 5    72.62127 11.90600  72.62127 -5.692188 -28148.48      1          5     5
## 6    72.75178 11.89091  72.75178 -5.686821 -28149.33      1          6     6</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="bayesian-workflow.html#cb250-1" tabindex="-1"></a><span class="fu">nrow</span>(m1.post)</span></code></pre></div>
<pre><code>## [1] 4000</code></pre>
<p>We’ve printed the first six rows, where we see values for the mean (<code>b_intercept</code>) and standard deviation (<code>sigma</code>). We also see that we have 4000 samples in total, exactly what we expect when we fit the model with 2000 iterations with 1000 warmup iterations discarded across four chains.</p>
<p>Now we can use the samples to plot the full posterior distribution for both parameters.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="bayesian-workflow.html#cb252-1" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#allows us to combine plots in one output</span></span>
<span id="cb252-2"><a href="bayesian-workflow.html#cb252-2" tabindex="-1"></a></span>
<span id="cb252-3"><a href="bayesian-workflow.html#cb252-3" tabindex="-1"></a>p_mu <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(m1.post, <span class="fu">aes</span>(<span class="at">x =</span> b_Intercept)) <span class="sc">+</span></span>
<span id="cb252-4"><a href="bayesian-workflow.html#cb252-4" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb252-5"><a href="bayesian-workflow.html#cb252-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu<span class="sc">~</span><span class="st">&quot;(Mean heart rate)&quot;</span>),</span>
<span id="cb252-6"><a href="bayesian-workflow.html#cb252-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb252-7"><a href="bayesian-workflow.html#cb252-7" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Posterior for the mean&quot;</span>) <span class="sc">+</span></span>
<span id="cb252-8"><a href="bayesian-workflow.html#cb252-8" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb252-9"><a href="bayesian-workflow.html#cb252-9" tabindex="-1"></a></span>
<span id="cb252-10"><a href="bayesian-workflow.html#cb252-10" tabindex="-1"></a>p_sigma <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(m1.post, <span class="fu">aes</span>(<span class="at">x =</span> sigma)) <span class="sc">+</span></span>
<span id="cb252-11"><a href="bayesian-workflow.html#cb252-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb252-12"><a href="bayesian-workflow.html#cb252-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(sigma<span class="sc">~</span><span class="st">&quot;(SD of heart rate)&quot;</span>),</span>
<span id="cb252-13"><a href="bayesian-workflow.html#cb252-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Probability Density&quot;</span>,</span>
<span id="cb252-14"><a href="bayesian-workflow.html#cb252-14" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Posterior for the standard deviation&quot;</span>) <span class="sc">+</span></span>
<span id="cb252-15"><a href="bayesian-workflow.html#cb252-15" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb252-16"><a href="bayesian-workflow.html#cb252-16" tabindex="-1"></a></span>
<span id="cb252-17"><a href="bayesian-workflow.html#cb252-17" tabindex="-1"></a>p_mu <span class="sc">+</span> p_sigma</span></code></pre></div>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c12-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>To answer our initial question, our posterior dsitribution for the mean implies that the mean resting heart rate for adults in the U.S. is very likely around 72.5 bpm. We could of course compute some summary statistics:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="bayesian-workflow.html#cb253-1" tabindex="-1"></a><span class="co">#posterior mean</span></span>
<span id="cb253-2"><a href="bayesian-workflow.html#cb253-2" tabindex="-1"></a><span class="fu">mean</span>(m1.post<span class="sc">$</span>b_Intercept)</span></code></pre></div>
<pre><code>## [1] 72.57146</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="bayesian-workflow.html#cb255-1" tabindex="-1"></a><span class="co">#posterior median </span></span>
<span id="cb255-2"><a href="bayesian-workflow.html#cb255-2" tabindex="-1"></a><span class="fu">median</span>(m1.post<span class="sc">$</span>b_Intercept)</span></code></pre></div>
<pre><code>## [1] 72.56715</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="bayesian-workflow.html#cb257-1" tabindex="-1"></a><span class="co">#interquartile range</span></span>
<span id="cb257-2"><a href="bayesian-workflow.html#cb257-2" tabindex="-1"></a><span class="fu">IQR</span>(m1.post<span class="sc">$</span>b_Intercept)</span></code></pre></div>
<pre><code>## [1] 0.1888912</code></pre>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="bayesian-workflow.html#cb259-1" tabindex="-1"></a><span class="co">#90% credible interval</span></span>
<span id="cb259-2"><a href="bayesian-workflow.html#cb259-2" tabindex="-1"></a><span class="fu">quantile</span>(m1.post<span class="sc">$</span>b_Intercept, <span class="at">probs=</span>(<span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.95</span>)))</span></code></pre></div>
<pre><code>##       5%      95% 
## 72.34078 72.80674</code></pre>
<p>Here we can be more specific and say that the mean of the posterior distribution for resting heart rate is 72.57 bpm, and the 90% credible interval says there’s a 90% chance that the mean heart rate is between 72.34 and 72.81 bpm. That’s a very high degree of precision, due in part to our large sample size of 7481 individuals.</p>
<p>We can also compute other probabilities of interest. For example, maybe you want to know the probability that the mean resting heart rate is greater than 73. That’s easy to compute with the samples:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="bayesian-workflow.html#cb261-1" tabindex="-1"></a><span class="co">#probability that the mean resting rate is &gt;73 bpm</span></span>
<span id="cb261-2"><a href="bayesian-workflow.html#cb261-2" tabindex="-1"></a><span class="fu">mean</span>(m1.post<span class="sc">$</span>b_Intercept<span class="sc">&gt;</span><span class="dv">73</span>)</span></code></pre></div>
<pre><code>## [1] 0.00225</code></pre>
<p>There’s only a 0.2% chance that the mean resting heart rate is greater than 73 bpm.</p>
<p>Before reporting our conclusions, one final thing we should do is to check what the posterior distribution implies about the data (i.e., the individual heart rates). This is analogous to the prior predictive check, except now instead of using only the prior distribution to simulate the data, we use the posterior distribution. Let’s go ahead and do this, drawing samples from the posterior distributions for the mean and standard deviation, and then randomly simulating observations of resting heart rate from the normal distributions of heart rate implied by the posterior.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="bayesian-workflow.html#cb263-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb263-2"><a href="bayesian-workflow.html#cb263-2" tabindex="-1"></a></span>
<span id="cb263-3"><a href="bayesian-workflow.html#cb263-3" tabindex="-1"></a><span class="co"># Simulate one individual heart rate per posterior sample</span></span>
<span id="cb263-4"><a href="bayesian-workflow.html#cb263-4" tabindex="-1"></a>post_r <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(m1.post), <span class="at">mean =</span> m1.post<span class="sc">$</span>b_Intercept, <span class="at">sd =</span> m1.post<span class="sc">$</span>sigma)</span>
<span id="cb263-5"><a href="bayesian-workflow.html#cb263-5" tabindex="-1"></a></span>
<span id="cb263-6"><a href="bayesian-workflow.html#cb263-6" tabindex="-1"></a><span class="co"># Create data frame for plotting</span></span>
<span id="cb263-7"><a href="bayesian-workflow.html#cb263-7" tabindex="-1"></a>df_post <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pulse =</span> post_r)</span>
<span id="cb263-8"><a href="bayesian-workflow.html#cb263-8" tabindex="-1"></a>df_obs  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pulse =</span> d<span class="sc">$</span>Pulse)</span>
<span id="cb263-9"><a href="bayesian-workflow.html#cb263-9" tabindex="-1"></a></span>
<span id="cb263-10"><a href="bayesian-workflow.html#cb263-10" tabindex="-1"></a><span class="fu">ggplot</span>(df_post, <span class="fu">aes</span>(<span class="at">x =</span> pulse)) <span class="sc">+</span></span>
<span id="cb263-11"><a href="bayesian-workflow.html#cb263-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;slategray3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb263-12"><a href="bayesian-workflow.html#cb263-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Joint posterior distribution&quot;</span>,</span>
<span id="cb263-13"><a href="bayesian-workflow.html#cb263-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Individual resting heart rate (bpm)&quot;</span>,</span>
<span id="cb263-14"><a href="bayesian-workflow.html#cb263-14" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb263-15"><a href="bayesian-workflow.html#cb263-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c15-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>The resulting distribution is called the <strong>joint posterior distribution</strong>, and it describes the distribution of the <em>individual</em> resting heart rates. One thing that would make us feel confident with our model is if the distribution of individual heart rates implied by the model reflects the data we actually observed. We can visually check that by overlaying a density plot of the observed data on top of the joint posterior distribution:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="bayesian-workflow.html#cb264-1" tabindex="-1"></a><span class="co"># Organize the two data sources</span></span>
<span id="cb264-2"><a href="bayesian-workflow.html#cb264-2" tabindex="-1"></a>df_pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pulse =</span> df_post<span class="sc">$</span>pulse, <span class="at">source =</span> <span class="st">&quot;Posterior predictive&quot;</span>)</span>
<span id="cb264-3"><a href="bayesian-workflow.html#cb264-3" tabindex="-1"></a>df_obs  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pulse =</span> d<span class="sc">$</span>Pulse, <span class="at">source =</span> <span class="st">&quot;Observed&quot;</span>)</span>
<span id="cb264-4"><a href="bayesian-workflow.html#cb264-4" tabindex="-1"></a></span>
<span id="cb264-5"><a href="bayesian-workflow.html#cb264-5" tabindex="-1"></a><span class="co"># Overlay densities</span></span>
<span id="cb264-6"><a href="bayesian-workflow.html#cb264-6" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb264-7"><a href="bayesian-workflow.html#cb264-7" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb264-8"><a href="bayesian-workflow.html#cb264-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> df_pred, <span class="fu">aes</span>(<span class="at">x =</span> pulse, <span class="at">fill =</span> source),</span>
<span id="cb264-9"><a href="bayesian-workflow.html#cb264-9" tabindex="-1"></a>               <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb264-10"><a href="bayesian-workflow.html#cb264-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> df_obs, <span class="fu">aes</span>(<span class="at">x =</span> pulse, <span class="at">color =</span> source),</span>
<span id="cb264-11"><a href="bayesian-workflow.html#cb264-11" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb264-12"><a href="bayesian-workflow.html#cb264-12" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Posterior predictive&quot;</span> <span class="ot">=</span> <span class="st">&quot;slategray3&quot;</span>)) <span class="sc">+</span></span>
<span id="cb264-13"><a href="bayesian-workflow.html#cb264-13" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Observed&quot;</span> <span class="ot">=</span> <span class="st">&quot;firebrick&quot;</span>, <span class="st">&quot;Posterior predictive&quot;</span> <span class="ot">=</span> <span class="st">&quot;black&quot;</span>)) <span class="sc">+</span></span>
<span id="cb264-14"><a href="bayesian-workflow.html#cb264-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Posterior predictive vs observed resting heart rates&quot;</span>,</span>
<span id="cb264-15"><a href="bayesian-workflow.html#cb264-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Individual resting heart rate (bpm)&quot;</span>,</span>
<span id="cb264-16"><a href="bayesian-workflow.html#cb264-16" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb264-17"><a href="bayesian-workflow.html#cb264-17" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="ch08_bayesianWorkflow_files/figure-html/c08c16-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>Here we can see that the posterior predictive and observed distributions have a close fit! That means the resting heart rates implied by the posterior distribution do a good job at describing the observed data. We can be reasonably confident in the model output for inference. Visually that would be the area under the posterior predictive distribution that’s greater than 100, but we can easily compute that probability with the observations of heart rate randomly drawn from our model:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="bayesian-workflow.html#cb265-1" tabindex="-1"></a><span class="fu">mean</span>(df_post<span class="sc">$</span>pulse<span class="sc">&gt;</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>## [1] 0.01175</code></pre>
<p>We see that based on our statistical model, we expect 1.15% of the population has tachycardia. We could do the same thing for bradycardia, which is defined as a slow heart rate usually less than 60 bpm:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="bayesian-workflow.html#cb267-1" tabindex="-1"></a><span class="fu">mean</span>(df_post<span class="sc">$</span>pulse<span class="sc">&lt;</span><span class="dv">60</span>)</span></code></pre></div>
<pre><code>## [1] 0.14575</code></pre>
<p>There’s a much greater portion of the population that likely has bradycardia than tachycardia. This isn’t too surprising, however, because bradycardia is common in people who exercise a lot, indicating high conditioning.</p>
</div>
</div>
<div id="summary-1" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Summary<a href="bayesian-workflow.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>That’s it! There are five basic components to Bayesian workflow, and we will try to make a habit of working through each of these components as we wrestle with new questions and models in the remainder of the book. Because the primary goal of this book is to teach the basic elements of statistic elements, we may not always cover each of these steps in the exact order or with the same degree of detail with every new example and model. But I do believe the workflow outlined here should be a starting point for anyone just starting out with statistical analysis, taking basic steps to ensure the model specification is adequate before drawing conclusions.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bayesian-estimation-and-inference.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-linear-model.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["research-design-and-statistics.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true,
    "toc_depth": 2
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
