<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Causal inference with linear models | Research Design and Statistics</title>
  <meta name="description" content="An introduction to research design and statistics" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Causal inference with linear models | Research Design and Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to research design and statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Causal inference with linear models | Research Design and Statistics" />
  
  <meta name="twitter:description" content="An introduction to research design and statistics" />
  

<meta name="author" content="Bradley J. Cosentino" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="graphical-causal-models.html"/>
<link rel="next" href="interaction-effects.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#work-in-progress"><i class="fa fa-check"></i>Work in progress</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html"><i class="fa fa-check"></i><b>1</b> Why Statistics? The Problem of Uncertainty</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#the-nature-of-science"><i class="fa fa-check"></i><b>1.1</b> The nature of science</a></li>
<li class="chapter" data-level="1.2" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#goals-of-scientific-research"><i class="fa fa-check"></i><b>1.2</b> Goals of scientific research</a></li>
<li class="chapter" data-level="1.3" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#three-general-goals-of-scientific-research"><i class="fa fa-check"></i><b>1.3</b> Three general goals of scientific research</a></li>
<li class="chapter" data-level="1.4" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#research-design-and-statistical-analysis-depend-on-your-goal"><i class="fa fa-check"></i><b>1.4</b> Research design and statistical analysis depend on your goal</a></li>
<li class="chapter" data-level="1.5" data-path="why-statistics-the-problem-of-uncertainty.html"><a href="why-statistics-the-problem-of-uncertainty.html#you-cant-escape-uncertainty-in-science"><i class="fa fa-check"></i><b>1.5</b> You can’t escape uncertainty in science</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html"><i class="fa fa-check"></i><b>2</b> Scientific workflow: Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-questions"><i class="fa fa-check"></i><b>2.1</b> Research questions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#clarify-your-primary-goal-description-prediction-or-explanation"><i class="fa fa-check"></i><b>2.1.1</b> Clarify your primary goal: description, prediction, or explanation?</a></li>
<li class="chapter" data-level="2.1.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#identify-the-scope-of-inference-the-who-what-when-and-where-of-your-study."><i class="fa fa-check"></i><b>2.1.2</b> Identify the scope of inference: The who, what, when, and where of your study.</a></li>
<li class="chapter" data-level="2.1.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-interesting"><i class="fa fa-check"></i><b>2.1.3</b> Make it interesting</a></li>
<li class="chapter" data-level="2.1.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-it-answerable-with-data"><i class="fa fa-check"></i><b>2.1.4</b> Make it answerable with data</a></li>
<li class="chapter" data-level="2.1.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#ground-it-in-theory"><i class="fa fa-check"></i><b>2.1.5</b> Ground it in theory</a></li>
<li class="chapter" data-level="2.1.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#make-sure-its-feasible"><i class="fa fa-check"></i><b>2.1.6</b> Make sure it’s feasible</a></li>
<li class="chapter" data-level="2.1.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#avoid-analyzing-the-data-before-stating-your-question"><i class="fa fa-check"></i><b>2.1.7</b> Avoid analyzing the data before stating your question</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#connecting-ideas-to-data"><i class="fa fa-check"></i><b>2.2</b> Connecting ideas to data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#theory"><i class="fa fa-check"></i><b>2.2.1</b> Theory</a></li>
<li class="chapter" data-level="2.2.2" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#research-question"><i class="fa fa-check"></i><b>2.2.2</b> Research question</a></li>
<li class="chapter" data-level="2.2.3" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#generative-model"><i class="fa fa-check"></i><b>2.2.3</b> Generative model</a></li>
<li class="chapter" data-level="2.2.4" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#study-design"><i class="fa fa-check"></i><b>2.2.4</b> Study design</a></li>
<li class="chapter" data-level="2.2.5" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimand"><i class="fa fa-check"></i><b>2.2.5</b> Estimand</a></li>
<li class="chapter" data-level="2.2.6" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#target-population"><i class="fa fa-check"></i><b>2.2.6</b> Target population</a></li>
<li class="chapter" data-level="2.2.7" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#sample-data"><i class="fa fa-check"></i><b>2.2.7</b> Sample data</a></li>
<li class="chapter" data-level="2.2.8" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#statistical-model"><i class="fa fa-check"></i><b>2.2.8</b> Statistical model</a></li>
<li class="chapter" data-level="2.2.9" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#estimate"><i class="fa fa-check"></i><b>2.2.9</b> Estimate</a></li>
<li class="chapter" data-level="2.2.10" data-path="scientific-workflow-connecting-ideas-to-data.html"><a href="scientific-workflow-connecting-ideas-to-data.html#summary"><i class="fa fa-check"></i><b>2.2.10</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to Data and R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#an-introduction-to-data"><i class="fa fa-check"></i><b>3.1</b> An introduction to data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variables-and-observations"><i class="fa fa-check"></i><b>3.1.1</b> Variables and observations</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#types-of-variables"><i class="fa fa-check"></i><b>3.1.2</b> Types of variables</a></li>
<li class="chapter" data-level="3.1.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#relationships-between-variables"><i class="fa fa-check"></i><b>3.1.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#variable-naming-conventions-and-metadata"><i class="fa fa-check"></i><b>3.1.4</b> Variable naming conventions and metadata</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#introduction-to-r"><i class="fa fa-check"></i><b>3.2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>3.2.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#the-rstudio-interface"><i class="fa fa-check"></i><b>3.2.2</b> The RStudio Interface</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#basic-data-manipulation-in-r"><i class="fa fa-check"></i><b>3.2.3</b> Basic data manipulation in R</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduction-to-data-and-r.html"><a href="introduction-to-data-and-r.html#scripting"><i class="fa fa-check"></i><b>3.2.4</b> Scripting</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="describing-data.html"><a href="describing-data.html"><i class="fa fa-check"></i><b>4</b> Describing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="describing-data.html"><a href="describing-data.html#defining-the-population"><i class="fa fa-check"></i><b>4.1</b> Defining the population</a></li>
<li class="chapter" data-level="4.2" data-path="describing-data.html"><a href="describing-data.html#loading-data-into-r"><i class="fa fa-check"></i><b>4.2</b> Loading data into R</a></li>
<li class="chapter" data-level="4.3" data-path="describing-data.html"><a href="describing-data.html#inspecting-the-dataset"><i class="fa fa-check"></i><b>4.3</b> Inspecting the dataset</a></li>
<li class="chapter" data-level="4.4" data-path="describing-data.html"><a href="describing-data.html#describing-single-variables"><i class="fa fa-check"></i><b>4.4</b> Describing single variables</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="describing-data.html"><a href="describing-data.html#qualitative-variables"><i class="fa fa-check"></i><b>4.4.1</b> Qualitative variables</a></li>
<li class="chapter" data-level="4.4.2" data-path="describing-data.html"><a href="describing-data.html#quantitative-variables"><i class="fa fa-check"></i><b>4.4.2</b> Quantitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="describing-data.html"><a href="describing-data.html#describing-relationships-between-variables"><i class="fa fa-check"></i><b>4.5</b> Describing relationships between variables</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-variables"><i class="fa fa-check"></i><b>4.5.1</b> Associations between quantitative variables</a></li>
<li class="chapter" data-level="4.5.2" data-path="describing-data.html"><a href="describing-data.html#associations-between-quantitative-and-qualitative-variables"><i class="fa fa-check"></i><b>4.5.2</b> Associations between quantitative and qualitative variables</a></li>
<li class="chapter" data-level="4.5.3" data-path="describing-data.html"><a href="describing-data.html#associations-between-qualitative-variables"><i class="fa fa-check"></i><b>4.5.3</b> Associations between qualitative variables</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="describing-data.html"><a href="describing-data.html#next-steps"><i class="fa fa-check"></i><b>4.6</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html"><i class="fa fa-check"></i><b>5</b> Uncertainty from sampling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sampling-requires-estimation"><i class="fa fa-check"></i><b>5.1</b> Sampling requires estimation</a></li>
<li class="chapter" data-level="5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#parameters-estimates-estimands"><i class="fa fa-check"></i><b>5.2</b> Parameters, estimates, estimands</a></li>
<li class="chapter" data-level="5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#sources-of-uncertainty-from-sampling"><i class="fa fa-check"></i><b>5.3</b> Sources of uncertainty from sampling</a></li>
<li class="chapter" data-level="5.4" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy-and-precision"><i class="fa fa-check"></i><b>5.4</b> Accuracy and precision</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#accuracy"><i class="fa fa-check"></i><b>5.4.1</b> Accuracy</a></li>
<li class="chapter" data-level="5.4.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#precision"><i class="fa fa-check"></i><b>5.4.2</b> Precision</a></li>
<li class="chapter" data-level="5.4.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#considering-accuracy-and-precision-together"><i class="fa fa-check"></i><b>5.4.3</b> Considering accuracy and precision together</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#maximizing-accuracy-and-precision-of-estimates"><i class="fa fa-check"></i><b>5.5</b> Maximizing accuracy and precision of estimates</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#random-sampling"><i class="fa fa-check"></i><b>5.5.1</b> Random sampling</a></li>
<li class="chapter" data-level="5.5.2" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#replication"><i class="fa fa-check"></i><b>5.5.2</b> Replication</a></li>
<li class="chapter" data-level="5.5.3" data-path="uncertainty-from-sampling.html"><a href="uncertainty-from-sampling.html#take-home-points"><i class="fa fa-check"></i><b>5.5.3</b> Take-home points</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html"><i class="fa fa-check"></i><b>6</b> Probability as the Language of Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#defining-probability"><i class="fa fa-check"></i><b>6.1</b> Defining probability</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#frequentist-definition"><i class="fa fa-check"></i><b>6.1.1</b> Frequentist definition</a></li>
<li class="chapter" data-level="6.1.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#bayesian-definition"><i class="fa fa-check"></i><b>6.1.2</b> Bayesian definition</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#probability-rules"><i class="fa fa-check"></i><b>6.2</b> Probability rules</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#individual-events"><i class="fa fa-check"></i><b>6.2.1</b> Individual events</a></li>
<li class="chapter" data-level="6.2.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#joint-events"><i class="fa fa-check"></i><b>6.2.2</b> Joint events</a></li>
<li class="chapter" data-level="6.2.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#general-addition-rule"><i class="fa fa-check"></i><b>6.2.3</b> General addition rule</a></li>
<li class="chapter" data-level="6.2.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#quantifying-marginal-probabilities"><i class="fa fa-check"></i><b>6.2.4</b> Quantifying marginal probabilities</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions"><i class="fa fa-check"></i><b>6.3</b> Sampling from probability distributions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-populations-is-probabalistic"><i class="fa fa-check"></i><b>6.3.1</b> Sampling from populations is probabalistic</a></li>
<li class="chapter" data-level="6.3.2" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#discrete-random-variables"><i class="fa fa-check"></i><b>6.3.2</b> Discrete random variables</a></li>
<li class="chapter" data-level="6.3.3" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#continuous-random-variables"><i class="fa fa-check"></i><b>6.3.3</b> Continuous random variables</a></li>
<li class="chapter" data-level="6.3.4" data-path="probability-as-the-language-of-uncertainty.html"><a href="probability-as-the-language-of-uncertainty.html#sampling-from-probability-distributions-1"><i class="fa fa-check"></i><b>6.3.4</b> Sampling from probability distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html"><i class="fa fa-check"></i><b>7</b> Bayesian estimation and inference</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#scientific-workflow-for-the-problem"><i class="fa fa-check"></i><b>7.1</b> Scientific workflow for the problem</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#theory-and-the-research-question"><i class="fa fa-check"></i><b>7.1.1</b> Theory and the research question</a></li>
<li class="chapter" data-level="7.1.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#generative-model-and-estimand"><i class="fa fa-check"></i><b>7.1.2</b> Generative model and estimand</a></li>
<li class="chapter" data-level="7.1.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-and-estimate"><i class="fa fa-check"></i><b>7.1.3</b> Statistical model and estimate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#bayes-theorem"><i class="fa fa-check"></i><b>7.2</b> Bayes Theorem</a></li>
<li class="chapter" data-level="7.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#applying-bayes-theorem-to-statistical-analysis"><i class="fa fa-check"></i><b>7.3</b> Applying Bayes Theorem to statistical analysis</a></li>
<li class="chapter" data-level="7.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#steps-of-estimation-with-bayesian-inference"><i class="fa fa-check"></i><b>7.4</b> Steps of estimation with Bayesian inference</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specify-the-prior-distribution"><i class="fa fa-check"></i><b>7.4.1</b> Specify the prior distribution</a></li>
<li class="chapter" data-level="7.4.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-likelihood-of-the-data"><i class="fa fa-check"></i><b>7.4.2</b> Quantify the likelihood of the data</a></li>
<li class="chapter" data-level="7.4.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-total-probability-of-the-data-marginal-likelihood"><i class="fa fa-check"></i><b>7.4.3</b> Quantify the total probability of the data (marginal likelihood)</a></li>
<li class="chapter" data-level="7.4.4" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#quantify-the-posterior-distribution"><i class="fa fa-check"></i><b>7.4.4</b> Quantify the posterior distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#summarizing-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5</b> Summarizing the posterior distribution</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#sampling-from-the-posterior-distribution"><i class="fa fa-check"></i><b>7.5.1</b> Sampling from the posterior distribution</a></li>
<li class="chapter" data-level="7.5.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#central-tendency-and-variance"><i class="fa fa-check"></i><b>7.5.2</b> Central tendency and variance</a></li>
<li class="chapter" data-level="7.5.3" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#intervals"><i class="fa fa-check"></i><b>7.5.3</b> Intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-priors"><i class="fa fa-check"></i><b>7.6</b> Specifying priors</a></li>
<li class="chapter" data-level="7.7" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#decision-making"><i class="fa fa-check"></i><b>7.7</b> Decision making</a></li>
<li class="chapter" data-level="7.8" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#specifying-and-fitting-statistical-models-with-bayes"><i class="fa fa-check"></i><b>7.8</b> Specifying and fitting statistical models with Bayes</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#statistical-model-specification"><i class="fa fa-check"></i><b>7.8.1</b> Statistical model specification</a></li>
<li class="chapter" data-level="7.8.2" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#fitting-models-with-brms"><i class="fa fa-check"></i><b>7.8.2</b> Fitting models with <em>brms</em></a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i><b>7.9</b> Estimation for a continuous random variable</a></li>
<li class="chapter" data-level="7.10" data-path="bayesian-estimation-and-inference.html"><a href="bayesian-estimation-and-inference.html#next-steps-1"><i class="fa fa-check"></i><b>7.10</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html"><i class="fa fa-check"></i><b>8</b> Bayesian Workflow</a>
<ul>
<li class="chapter" data-level="8.1" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#prior-distribution-choices"><i class="fa fa-check"></i><b>8.1</b> Prior distribution choices</a></li>
<li class="chapter" data-level="8.2" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#prior-predictive-checks"><i class="fa fa-check"></i><b>8.2</b> Prior predictive checks</a></li>
<li class="chapter" data-level="8.3" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#posterior-predictive-checks"><i class="fa fa-check"></i><b>8.3</b> Posterior predictive checks</a></li>
<li class="chapter" data-level="8.4" data-path="bayesian-workflow.html"><a href="bayesian-workflow.html#next-steps-2"><i class="fa fa-check"></i><b>8.4</b> Next steps</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-linear-model.html"><a href="the-linear-model.html"><i class="fa fa-check"></i><b>9</b> The linear model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-linear-model.html"><a href="the-linear-model.html#statistical-models"><i class="fa fa-check"></i><b>9.1</b> Statistical models</a></li>
<li class="chapter" data-level="9.2" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-model"><i class="fa fa-check"></i><b>9.2</b> Linear model</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="the-linear-model.html"><a href="the-linear-model.html#basic-structure-of-the-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> Basic structure of the linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="the-linear-model.html"><a href="the-linear-model.html#fitting-the-linear-model-in-brms"><i class="fa fa-check"></i><b>9.2.2</b> Fitting the linear model in brms</a></li>
<li class="chapter" data-level="9.2.3" data-path="the-linear-model.html"><a href="the-linear-model.html#how-a-frequentist-might-do-it"><i class="fa fa-check"></i><b>9.2.3</b> How a frequentist might do it</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="the-linear-model.html"><a href="the-linear-model.html#linear-models-with-categorical-predictors"><i class="fa fa-check"></i><b>9.3</b> Linear models with categorical predictors</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="the-linear-model.html"><a href="the-linear-model.html#binary-explanatory-variables"><i class="fa fa-check"></i><b>9.3.1</b> Binary explanatory variables</a></li>
<li class="chapter" data-level="9.3.2" data-path="the-linear-model.html"><a href="the-linear-model.html#categorical-predictors-with-more-than-two-categories"><i class="fa fa-check"></i><b>9.3.2</b> Categorical predictors with more than two categories</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html"><i class="fa fa-check"></i><b>10</b> Graphical Causal Models</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>10.1</b> Directed acyclic graphs (DAGs)</a></li>
<li class="chapter" data-level="10.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#three-causal-structures-in-dags"><i class="fa fa-check"></i><b>10.2</b> Three causal structures in DAGs</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-fork-confounders"><i class="fa fa-check"></i><b>10.2.1</b> The fork: confounders</a></li>
<li class="chapter" data-level="10.2.2" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-pipe-mediators"><i class="fa fa-check"></i><b>10.2.2</b> The pipe: mediators</a></li>
<li class="chapter" data-level="10.2.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#the-inverted-fork-colliders"><i class="fa fa-check"></i><b>10.2.3</b> The inverted fork: colliders</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#closing-backdoor-paths"><i class="fa fa-check"></i><b>10.3</b> Closing backdoor paths</a></li>
<li class="chapter" data-level="10.4" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#like-all-models-dags-require-assumptions"><i class="fa fa-check"></i><b>10.4</b> Like all models, DAGs require assumptions</a></li>
<li class="chapter" data-level="10.5" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#types-of-study-designs"><i class="fa fa-check"></i><b>10.5</b> Types of Study Designs</a></li>
<li class="chapter" data-level="10.6" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#experimental-studies"><i class="fa fa-check"></i><b>10.6</b> Experimental studies</a></li>
<li class="chapter" data-level="10.7" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#observational-studies"><i class="fa fa-check"></i><b>10.7</b> Observational studies</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="graphical-causal-models.html"><a href="graphical-causal-models.html#pros-and-cons-of-prospective-vs.-retrospective-studies-planned"><i class="fa fa-check"></i><b>10.7.1</b> Pros and cons of prospective vs. retrospective studies (planned)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html"><i class="fa fa-check"></i><b>11</b> Causal inference with linear models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#linear-models-with-multiple-predictor-variables"><i class="fa fa-check"></i><b>11.1</b> Linear models with multiple predictor variables</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#generic-linear-model-with-two-predictors"><i class="fa fa-check"></i><b>11.1.1</b> Generic linear model with two predictors</a></li>
<li class="chapter" data-level="11.1.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#multiple-regression-model-for-the-ice-cream-and-drownings-example"><i class="fa fa-check"></i><b>11.1.2</b> Multiple regression model for the ice cream and drownings example</a></li>
<li class="chapter" data-level="11.1.3" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prior-predictive-check"><i class="fa fa-check"></i><b>11.1.3</b> Prior predictive check</a></li>
<li class="chapter" data-level="11.1.4" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#fitting-the-multiple-regression-model"><i class="fa fa-check"></i><b>11.1.4</b> Fitting the multiple regression model</a></li>
<li class="chapter" data-level="11.1.5" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#prediction-plots-for-multiple-regression-models"><i class="fa fa-check"></i><b>11.1.5</b> Prediction plots for multiple regression models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="causal-inference-with-linear-models.html"><a href="causal-inference-with-linear-models.html#dag-informed-predictors-categorical-variables-what-multiple-regression-is-doing-with-predictor-residual-plot"><i class="fa fa-check"></i><b>11.2</b> DAG-informed predictors, categorical variables, what multiple regression is doing with predictor residual plot</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="interaction-effects.html"><a href="interaction-effects.html"><i class="fa fa-check"></i><b>12</b> Interaction effects</a></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized linear models</a></li>
<li class="chapter" data-level="14" data-path="multilevel-models.html"><a href="multilevel-models.html"><i class="fa fa-check"></i><b>14</b> Multilevel models</a></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html"><i class="fa fa-check"></i><b>A</b> Estimation with frequentist inference</a>
<ul>
<li class="chapter" data-level="A.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#frequentist-estimates-are-point-estimates"><i class="fa fa-check"></i><b>A.1</b> Frequentist estimates are point estimates</a></li>
<li class="chapter" data-level="A.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions"><i class="fa fa-check"></i><b>A.2</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-are-centered-on-the-true-parameter-value"><i class="fa fa-check"></i><b>A.2.1</b> Sampling distributions are centered on the true parameter value</a></li>
<li class="chapter" data-level="A.2.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sampling-distributions-allow-us-to-estimate-precision"><i class="fa fa-check"></i><b>A.2.2</b> Sampling distributions allow us to estimate precision</a></li>
<li class="chapter" data-level="A.2.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#sample-size-affects-the-shape-of-sampling-distributions"><i class="fa fa-check"></i><b>A.2.3</b> Sample size affects the shape of sampling distributions</a></li>
<li class="chapter" data-level="A.2.4" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#summary-points-on-sampling-distributions"><i class="fa fa-check"></i><b>A.2.4</b> Summary points on sampling distributions</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#quantifying-uncertainty-standard-error-and-confidence-intervals"><i class="fa fa-check"></i><b>A.3</b> Quantifying uncertainty: standard error and confidence intervals</a>
<ul>
<li class="chapter" data-level="A.3.1" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#standard-error"><i class="fa fa-check"></i><b>A.3.1</b> Standard error</a></li>
<li class="chapter" data-level="A.3.2" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#confidence-intervals"><i class="fa fa-check"></i><b>A.3.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="A.3.3" data-path="estimation-with-frequentist-inference.html"><a href="estimation-with-frequentist-inference.html#the-standard-normal-approximation-does-not-work-well-under-low-sample-size"><i class="fa fa-check"></i><b>A.3.3</b> The standard normal approximation does not work well under low sample size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html"><i class="fa fa-check"></i><b>B</b> Decision-making with frequentist estimates</a>
<ul>
<li class="chapter" data-level="B.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#framework-of-classical-hypothesis-testing"><i class="fa fa-check"></i><b>B.1</b> Framework of classical hypothesis testing</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#state-null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>B.1.1</b> State null and alternative hypotheses</a></li>
<li class="chapter" data-level="B.1.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#assume-the-null-hypothesis-is-true"><i class="fa fa-check"></i><b>B.1.2</b> Assume the null hypothesis is true</a></li>
<li class="chapter" data-level="B.1.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#quantify-the-likelihood-of-the-data-under-the-null-hypothesis-p-values"><i class="fa fa-check"></i><b>B.1.3</b> Quantify the likelihood of the data under the null hypothesis: P-values</a></li>
<li class="chapter" data-level="B.1.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-a-decision-based-on-the-p-value-and-significance-value"><i class="fa fa-check"></i><b>B.1.4</b> Making a decision based on the P-value and significance value</a></li>
<li class="chapter" data-level="B.1.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#decision-errors-happen"><i class="fa fa-check"></i><b>B.1.5</b> Decision errors happen</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#making-decisions-with-confidence-intervals"><i class="fa fa-check"></i><b>B.2</b> Making decisions with confidence intervals</a></li>
<li class="chapter" data-level="B.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#issues-with-the-null-hypothesis-framework"><i class="fa fa-check"></i><b>B.3</b> Issues with the null hypothesis framework</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#significance-testing-reinforces-binary-thinking"><i class="fa fa-check"></i><b>B.3.1</b> Significance testing reinforces binary thinking</a></li>
<li class="chapter" data-level="B.3.2" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-testing-reinforces-gamification-in-science"><i class="fa fa-check"></i><b>B.3.2</b> Statistical testing reinforces gamification in science</a></li>
<li class="chapter" data-level="B.3.3" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#statistical-significance-is-not-the-same-thing-as-practical-significance"><i class="fa fa-check"></i><b>B.3.3</b> Statistical significance is not the same thing as practical significance</a></li>
<li class="chapter" data-level="B.3.4" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#type-i-errors-become-more-likely-with-multiple-tests"><i class="fa fa-check"></i><b>B.3.4</b> Type I errors become more likely with multiple tests</a></li>
<li class="chapter" data-level="B.3.5" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-is-almost-certainly-wrong"><i class="fa fa-check"></i><b>B.3.5</b> The null hypothesis is almost certainly wrong</a></li>
<li class="chapter" data-level="B.3.6" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-null-hypothesis-focuses-on-data-you-did-not-observe"><i class="fa fa-check"></i><b>B.3.6</b> The null hypothesis focuses on data you did not observe</a></li>
<li class="chapter" data-level="B.3.7" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#a-single-null-and-alternative-hypothesis-is-too-constraining"><i class="fa fa-check"></i><b>B.3.7</b> A single null and alternative hypothesis is too constraining</a></li>
<li class="chapter" data-level="B.3.8" data-path="decision-making-with-frequentist-estimates.html"><a href="decision-making-with-frequentist-estimates.html#the-p-value-is-not-the-probability-we-want"><i class="fa fa-check"></i><b>B.3.8</b> The P-value is not the probability we want</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Research Design and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="causal-inference-with-linear-models" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Causal inference with linear models<a href="causal-inference-with-linear-models.html#causal-inference-with-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>I like ice cream. A lot. So I became alarmed when I saw the graph below, suggesting that the number of drownings in the United States is positively related to ice cream sales.</p>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk01,%20-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk01, )TODO: caption.
</p>
</div>
<p>Why would the number of drownings be related to ice cream sales? Well, one hypothesis is that ice cream consumption causally increases risk of drowning. Perhaps eating a lot of ice cream compromises one’s ability to swim. The DAG below represents this hypothesis.</p>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk02,%20-1.png" alt="Initial DAG for the causal effect of greenspace on mental health." width="288" />
<p class="caption">
(#fig:c11_chunk02, )Initial DAG for the causal effect of greenspace on mental health.
</p>
</div>
<p>The DAG here shows that the number of drownings (D) is indirectly affected by ice cream sales (IC) via the mediators ice cream consumption (C) and swimming performance (SP), which are unobserved. If this DAG was correct, we would expect that the number drownings is related to ice cream sales. We have monthly data available on those measurements as seen in the graph above, but we should build a linear model to more rigorously examine the relationship than by simply eye balling it. Here’s our statistical model. Note we’re mean-centering the monthly ice-cream sales:</p>
<p><span class="math display">\[
\begin{array}{l}
d_i \sim \mathrm{Normal}(\mu_i, \sigma) \\
\mu_i = \alpha + \beta (x_i-\bar{x} ) \\
\alpha \sim \mathrm{Normal}(13, 2) \\
\beta \sim \mathrm{Normal}(0, 2) \\
\sigma \sim \mathrm{Uniform}(0, 5)
\end{array}
\]</span> For the sake of brevity, I’ll skip the presentation of a prior predictive check and move right onto fitting the model. W</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="causal-inference-with-linear-models.html#cb383-1" tabindex="-1"></a><span class="co">#mean center ice cream sales</span></span>
<span id="cb383-2"><a href="causal-inference-with-linear-models.html#cb383-2" tabindex="-1"></a>d<span class="sc">$</span>sales.c <span class="ot">&lt;-</span> d<span class="sc">$</span>ice_cream_sales_millions <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions)</span>
<span id="cb383-3"><a href="causal-inference-with-linear-models.html#cb383-3" tabindex="-1"></a></span>
<span id="cb383-4"><a href="causal-inference-with-linear-models.html#cb383-4" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb383-5"><a href="causal-inference-with-linear-models.html#cb383-5" tabindex="-1"></a><span class="co">#specify model formula</span></span>
<span id="cb383-6"><a href="causal-inference-with-linear-models.html#cb383-6" tabindex="-1"></a>m1.formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(drownings <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sales.c,</span>
<span id="cb383-7"><a href="causal-inference-with-linear-models.html#cb383-7" tabindex="-1"></a>                <span class="at">family =</span> gaussian) </span>
<span id="cb383-8"><a href="causal-inference-with-linear-models.html#cb383-8" tabindex="-1"></a></span>
<span id="cb383-9"><a href="causal-inference-with-linear-models.html#cb383-9" tabindex="-1"></a><span class="co">#specify priors</span></span>
<span id="cb383-10"><a href="causal-inference-with-linear-models.html#cb383-10" tabindex="-1"></a>m1.prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">13</span>, <span class="dv">2</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb383-11"><a href="causal-inference-with-linear-models.html#cb383-11" tabindex="-1"></a>              <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.25</span>), <span class="at">class =</span> b),</span>
<span id="cb383-12"><a href="causal-inference-with-linear-models.html#cb383-12" tabindex="-1"></a>              <span class="fu">prior</span>(<span class="fu">uniform</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">class =</span> sigma, <span class="at">lb=</span><span class="dv">0</span>, <span class="at">ub=</span><span class="dv">5</span>))</span>
<span id="cb383-13"><a href="causal-inference-with-linear-models.html#cb383-13" tabindex="-1"></a>              </span>
<span id="cb383-14"><a href="causal-inference-with-linear-models.html#cb383-14" tabindex="-1"></a><span class="co">#compute the posterior</span></span>
<span id="cb383-15"><a href="causal-inference-with-linear-models.html#cb383-15" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d,</span>
<span id="cb383-16"><a href="causal-inference-with-linear-models.html#cb383-16" tabindex="-1"></a>         <span class="at">formula =</span> m1.formula,</span>
<span id="cb383-17"><a href="causal-inference-with-linear-models.html#cb383-17" tabindex="-1"></a>         <span class="at">prior =</span> m1.prior,</span>
<span id="cb383-18"><a href="causal-inference-with-linear-models.html#cb383-18" tabindex="-1"></a>         <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb383-19"><a href="causal-inference-with-linear-models.html#cb383-19" tabindex="-1"></a>         <span class="at">seed=</span><span class="dv">123</span>)</span>
<span id="cb383-20"><a href="causal-inference-with-linear-models.html#cb383-20" tabindex="-1"></a></span>
<span id="cb383-21"><a href="causal-inference-with-linear-models.html#cb383-21" tabindex="-1"></a><span class="co">#values </span></span>
<span id="cb383-22"><a href="causal-inference-with-linear-models.html#cb383-22" tabindex="-1"></a>x_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(d<span class="sc">$</span>sales.c), <span class="fu">max</span>(d<span class="sc">$</span>sales.c), <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb383-23"><a href="causal-inference-with-linear-models.html#cb383-23" tabindex="-1"></a></span>
<span id="cb383-24"><a href="causal-inference-with-linear-models.html#cb383-24" tabindex="-1"></a><span class="co">#mean prediction</span></span>
<span id="cb383-25"><a href="causal-inference-with-linear-models.html#cb383-25" tabindex="-1"></a>y.mu <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m1, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">sales.c =</span> x_vals))</span>
<span id="cb383-26"><a href="causal-inference-with-linear-models.html#cb383-26" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="at">sales.c =</span> x_vals, y.mu)</span>
<span id="cb383-27"><a href="causal-inference-with-linear-models.html#cb383-27" tabindex="-1"></a>fit<span class="sc">$</span>ice_cream_sales_millions <span class="ot">&lt;-</span> fit<span class="sc">$</span>sales.c <span class="sc">+</span> <span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions)</span>
<span id="cb383-28"><a href="causal-inference-with-linear-models.html#cb383-28" tabindex="-1"></a></span>
<span id="cb383-29"><a href="causal-inference-with-linear-models.html#cb383-29" tabindex="-1"></a><span class="co">#individual prediction</span></span>
<span id="cb383-30"><a href="causal-inference-with-linear-models.html#cb383-30" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">sales.c =</span> x_vals))</span>
<span id="cb383-31"><a href="causal-inference-with-linear-models.html#cb383-31" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="at">sales.c =</span> x_vals, y)</span>
<span id="cb383-32"><a href="causal-inference-with-linear-models.html#cb383-32" tabindex="-1"></a>pred<span class="sc">$</span>ice_cream_sales_millions <span class="ot">&lt;-</span> pred<span class="sc">$</span>sales.c <span class="sc">+</span> <span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions)</span>
<span id="cb383-33"><a href="causal-inference-with-linear-models.html#cb383-33" tabindex="-1"></a></span>
<span id="cb383-34"><a href="causal-inference-with-linear-models.html#cb383-34" tabindex="-1"></a><span class="co">#now plot; geom_line adds the posterior mean line</span></span>
<span id="cb383-35"><a href="causal-inference-with-linear-models.html#cb383-35" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> ice_cream_sales_millions, <span class="at">y =</span> drownings)) <span class="sc">+</span></span>
<span id="cb383-36"><a href="causal-inference-with-linear-models.html#cb383-36" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> pred, <span class="at">fill =</span> <span class="st">&quot;grey83&quot;</span>,</span>
<span id="cb383-37"><a href="causal-inference-with-linear-models.html#cb383-37" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> ice_cream_sales_millions, <span class="at">y =</span> Estimate, <span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>)) <span class="sc">+</span></span>
<span id="cb383-38"><a href="causal-inference-with-linear-models.html#cb383-38" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">data =</span> fit, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>,</span>
<span id="cb383-39"><a href="causal-inference-with-linear-models.html#cb383-39" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;slategray3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb383-40"><a href="causal-inference-with-linear-models.html#cb383-40" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> ice_cream_sales_millions, <span class="at">y =</span> Estimate, <span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>)) <span class="sc">+</span></span>
<span id="cb383-41"><a href="causal-inference-with-linear-models.html#cb383-41" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">&quot;firebrick&quot;</span>) <span class="sc">+</span></span>
<span id="cb383-42"><a href="causal-inference-with-linear-models.html#cb383-42" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Ice cream sales (millions)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Drownings&quot;</span>) <span class="sc">+</span></span>
<span id="cb383-43"><a href="causal-inference-with-linear-models.html#cb383-43" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk03-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk03)TODO: caption.
</p>
</div>
<p>From the model we see the expected increase in drownings per every one million more ice cream sales is 0.28 with a 95% credible interval of 0.26 to 0.30. In other words, we confirmed what we saw with our eyes. The average number of drownings per month is positively related to ice cream sales. This means ice cream causes drownings, right?</p>
<p>Well, no. Good for you if you’ve remained skeptical to this point. We’ve confirmed here that there is indeed a positive association between drownings per month and ice cream sales. But that doesn’t mean the association is causal. Just because we have a DAG doesn’t make the association we find causal. The scientific hypothesis represented by our DAG might be wrong. And in this case, it’s almost certainly wrong. Here’s a DAG representing an alternative hypothesis:</p>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk04,%20-1.png" alt="Initial DAG for the causal effect of greenspace on mental health." width="288" />
<p class="caption">
(#fig:c11_chunk04, )Initial DAG for the causal effect of greenspace on mental health.
</p>
</div>
<p>What does this DAG say? First, we see the same causal pathway that we saw before from ice cream sales to drowning via consumption and swimming performance. But now we’ve added another pathway by which drownings is linked to ice cream sales. The new causal pathway shows that air temperature (T) affects ice cream sales, which makes sense as people tend to eat more ice cream when it’s warm. Air temperature also affects the number of swimmers (S), which is an unobserved variable. People are more likely to swim when it’s warm! Numerically we expect more drownings when there’s more swimmers, so there’s a direct effect of swimmers on drownings.</p>
<p>Do you see the issue here? There are two pathways linking ice cream sales to drownings. One is a causal pathway via ice cream consumption and swimming performance, and the other is a backdoor path via temperature and number of swimmers. Temperature here is a confounder! If we want to test the causal effect of ice cream sales on drownings, we would need to adjust for temperature. Recall from Chapter 4 that we can identify adjustment sets necessary when testing the causal effect of one variable on another:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="causal-inference-with-linear-models.html#cb384-1" tabindex="-1"></a><span class="co">#testing the total effect of ice cream sales on drownings</span></span>
<span id="cb384-2"><a href="causal-inference-with-linear-models.html#cb384-2" tabindex="-1"></a><span class="fu">adjustmentSets</span>(dag2, <span class="at">exposure=</span><span class="st">&quot;IC&quot;</span>, <span class="at">outcome=</span><span class="st">&quot;D&quot;</span>, <span class="at">effect =</span> <span class="st">&quot;total&quot;</span>)</span></code></pre></div>
<pre><code>## { S }
## { T }</code></pre>
<p>Here we see we can adjust for temperature or the number of swimmers, but as the number of swimmers is unobserved, we would have to adjust for temperature.</p>
<p>But what does it mean to adjust for a variable? When we do an experiment, we know that randomization breaks the kind of confounding observed in our second DAG. But in an observational design we can’t do that. Instead, we approach the process of adjustment with our statistical models. This chapter shows you how to do that.</p>
<div id="linear-models-with-multiple-predictor-variables" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Linear models with multiple predictor variables<a href="causal-inference-with-linear-models.html#linear-models-with-multiple-predictor-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So we have two DAGs that link ice cream sales to drownings. In the first DAG, there’s only one causal pathway between ice cream sales and drownings. Based on that DAG, any relationship we observe between drownings and ice cream sales must be due to that causal pathway. The second DAG adds a backdoor path and suggests that at least part of the association between drownings and ice cream sales may be due to confounding with temperature. If the second DAG is correct, we should still find a relationship bewteen drownings and ice cream sales when we adjust for temperature. Fortunately we can adjust for temperature by including it in a linear model along with ice cream sales to predict drownings.</p>
<div id="generic-linear-model-with-two-predictors" class="section level3 hasAnchor" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> Generic linear model with two predictors<a href="causal-inference-with-linear-models.html#generic-linear-model-with-two-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Remember that the simple linear model has two parameters: an intercept and a slope representing the association between the response and explanatory variables of interest. But we can expand the linear model to include <em>multiple</em> explanatory variables. A linear model with multiple predictors is commonly called a <strong>multiple regression</strong> model. For example, here’s a multiple regression model with two explanatory variables:</p>
<p><span class="math inline">\(\mu_i = \alpha + \beta_1 x1_{i} + \beta_2 x2_{i}\)</span></p>
<p>Let’s walk through what each of these terms represents:</p>
<ul>
<li><p><span class="math inline">\(\mu_i\)</span>: This is the expected mean value of the response variable for any individual with a values of <span class="math inline">\(x1_{i}\)</span> and <span class="math inline">\(x2_{i}\)</span>.</p></li>
<li><p><span class="math inline">\(\alpha\)</span>: This is still the intercept term. In our linear model it represents the expected value of the response variable when the values of both <span class="math inline">\(x1\)</span> and <span class="math inline">\(x2\)</span> are 0.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span>: This is the slope for the relationship of Y to <span class="math inline">\(x1_{i}\)</span> <em>when holding</em> <span class="math inline">\(x2_{i}\)</span> (and any other predictor we might add to the model) constant.</p></li>
<li><p><span class="math inline">\(\beta_2\)</span>: This is the slope for the relationship of Y to <span class="math inline">\(x2_{i}\)</span> <em>when holding</em> <span class="math inline">\(x1_{i}\)</span> (and any other predictor we might add to the model) constant.</p></li>
<li><p><span class="math inline">\(x1_{i}\)</span>: This is the observed value of variable <span class="math inline">\(x1\)</span> for observation <em>i</em></p></li>
<li><p><span class="math inline">\(x2_{i}\)</span>: This is the observed value of variable <span class="math inline">\(x2\)</span> for observation <em>i</em></p></li>
</ul>
<p>The model can be expanded to incorporate any number of additional predictor variables, each with a slope <span class="math inline">\(\beta\)</span> while holding other predictors constant.</p>
</div>
<div id="multiple-regression-model-for-the-ice-cream-and-drownings-example" class="section level3 hasAnchor" number="11.1.2">
<h3><span class="header-section-number">11.1.2</span> Multiple regression model for the ice cream and drownings example<a href="causal-inference-with-linear-models.html#multiple-regression-model-for-the-ice-cream-and-drownings-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s apply this model to our question about the causal effect of ice cream sales on drownings. We want to know if drownings is related to ice cream sales when controlling for the confounder, air temperature. Here’s our statistical model:</p>
<p><span class="math display">\[
\begin{array}{l}
d_i \sim \mathrm{Normal}(\mu_i, \sigma) \\
\mu_i = \alpha + \beta_{c} (c_i-\bar{c}) + \beta_t (t_i-\bar{t})\\
\alpha \sim \mathrm{Normal}(13, 2) \\
\beta_c \sim \mathrm{Normal}(0, 0.25) \\
\beta_t \sim \mathrm{Normal}(0, 0.25) \\
\sigma \sim \mathrm{Uniform}(0, 5)
\end{array}
\]</span></p>
<p>Let’s walk through each line of the model to ensure we know what everything means!</p>
<ul>
<li><p><span class="math inline">\(\hat{d}_i\)</span>: This is the expected mean number of drownings for each observation <em>i</em> with values <span class="math inline">\(c_i\)</span> ice cream sales and <span class="math inline">\(t_i\)</span> for temperature. In other words, given specific values of ice cream sales and temperature, this is the predicted mean number of drownings. We could look at the expected number of drownings for any combination of the values of ice cream sales and temperature.</p></li>
<li><p><span class="math inline">\(\alpha\)</span>: This is the intercept term. Note that we are mean-centering ice cream sales and temperature, so the intercept represents the expected number of drownings when ice cream sales and air temperature are both at their means.</p></li>
<li><p><span class="math inline">\(\beta_c\)</span>: This is the slope for the relationship of drownings to ice cream sales <em>when temperature is held constant</em>.</p></li>
<li><p><span class="math inline">\(\beta_A\)</span>: This is the slope for the relationship of drownings to temperature <em>when ice cream sales are held constant</em>.</p></li>
<li><p><span class="math inline">\(c_i\)</span>: This is the observed value of ice cream sales for each observation <em>i</em></p></li>
<li><p><span class="math inline">\(t_i\)</span>: This is the observed value of temperature for each observation <em>i</em></p></li>
</ul>
<p>The only thing that’s really new about this model is the interpretation of the slopes. No longer are the slopes simply the expected change in the response variable for each one unit change in the explanatory variable. Rather, the slopes represent the expected change in the response variable per unit change in the explanatory variable <em>while holding other explanatory variables constant</em>.</p>
<p>Holding a variable constant is exactly what we mean by <em>adjusting</em> for a variable. If we want to test the causal effect of ice cream sales on drownings, we have to adjust for temperature, which means to hold it constant. You can think of temperature being held constant at <em>any</em> value. For example, if temperature was held constant at 70 degrees F, how much would drownings change with each unit increase in ice cream sales. <em>That</em> is the interpretation of <span class="math inline">\(\beta_c\)</span>. It’s basically allowing us to look at the association between drownings and ice cream sales while shutting down the back-door path through temperature. The model asks, if I know the value of temperature, is there any relationship between drowning and ice cream sales? It doesn’t’ matter what value temperature is being held constant at. It could be 70 degrees, or 80 degrees, or 30.5 degrees. In this model, the estimated slope for ice cream sales would be the same at any value of temperature. What matters most is that the association between drownings and ice cream - as measured by the slope - is being estimated while holding temperature constant. The slope for temperature is interpreted in the same way. If I know the value of ice cream sales, is there any relationship between drownings and temperature?</p>
</div>
<div id="prior-predictive-check" class="section level3 hasAnchor" number="11.1.3">
<h3><span class="header-section-number">11.1.3</span> Prior predictive check<a href="causal-inference-with-linear-models.html#prior-predictive-check" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As usual we should conduct a prior predictive check of our model.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="causal-inference-with-linear-models.html#cb386-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb386-2"><a href="causal-inference-with-linear-models.html#cb386-2" tabindex="-1"></a></span>
<span id="cb386-3"><a href="causal-inference-with-linear-models.html#cb386-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb386-4"><a href="causal-inference-with-linear-models.html#cb386-4" tabindex="-1"></a></span>
<span id="cb386-5"><a href="causal-inference-with-linear-models.html#cb386-5" tabindex="-1"></a><span class="co">#intercept</span></span>
<span id="cb386-6"><a href="causal-inference-with-linear-models.html#cb386-6" tabindex="-1"></a>alpha.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">13</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb386-7"><a href="causal-inference-with-linear-models.html#cb386-7" tabindex="-1"></a></span>
<span id="cb386-8"><a href="causal-inference-with-linear-models.html#cb386-8" tabindex="-1"></a><span class="co">#slopes</span></span>
<span id="cb386-9"><a href="causal-inference-with-linear-models.html#cb386-9" tabindex="-1"></a>beta.c.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">0.25</span>)</span>
<span id="cb386-10"><a href="causal-inference-with-linear-models.html#cb386-10" tabindex="-1"></a>beta.t.sim <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">0.25</span>)</span>
<span id="cb386-11"><a href="causal-inference-with-linear-models.html#cb386-11" tabindex="-1"></a></span>
<span id="cb386-12"><a href="causal-inference-with-linear-models.html#cb386-12" tabindex="-1"></a><span class="co">#values of c (ice cream sales)</span></span>
<span id="cb386-13"><a href="causal-inference-with-linear-models.html#cb386-13" tabindex="-1"></a>c_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(d<span class="sc">$</span>sales.c), <span class="fu">max</span>(d<span class="sc">$</span>sales.c), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb386-14"><a href="causal-inference-with-linear-models.html#cb386-14" tabindex="-1"></a></span>
<span id="cb386-15"><a href="causal-inference-with-linear-models.html#cb386-15" tabindex="-1"></a><span class="co"># Create a data frame with all lines</span></span>
<span id="cb386-16"><a href="causal-inference-with-linear-models.html#cb386-16" tabindex="-1"></a>lines_df <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">c_vals =</span> c_vals, <span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span>n)</span>
<span id="cb386-17"><a href="causal-inference-with-linear-models.html#cb386-17" tabindex="-1"></a>lines_df<span class="sc">$</span>y <span class="ot">&lt;-</span> alpha.sim[lines_df<span class="sc">$</span>sim] <span class="sc">+</span> </span>
<span id="cb386-18"><a href="causal-inference-with-linear-models.html#cb386-18" tabindex="-1"></a>              beta.c.sim[lines_df<span class="sc">$</span>sim] <span class="sc">*</span> lines_df<span class="sc">$</span>c_vals <span class="sc">+</span> </span>
<span id="cb386-19"><a href="causal-inference-with-linear-models.html#cb386-19" tabindex="-1"></a>              beta.t.sim[lines_df<span class="sc">$</span>sim] <span class="sc">*</span> <span class="dv">0</span></span>
<span id="cb386-20"><a href="causal-inference-with-linear-models.html#cb386-20" tabindex="-1"></a></span>
<span id="cb386-21"><a href="causal-inference-with-linear-models.html#cb386-21" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb386-22"><a href="causal-inference-with-linear-models.html#cb386-22" tabindex="-1"></a><span class="fu">ggplot</span>(lines_df, <span class="fu">aes</span>(<span class="at">x =</span> c_vals<span class="sc">+</span><span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions), <span class="at">y =</span> y, <span class="at">group =</span> sim)) <span class="sc">+</span></span>
<span id="cb386-23"><a href="causal-inference-with-linear-models.html#cb386-23" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb386-24"><a href="causal-inference-with-linear-models.html#cb386-24" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Ice cream sales (millions)&quot;</span>,</span>
<span id="cb386-25"><a href="causal-inference-with-linear-models.html#cb386-25" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Drownings&quot;</span>) <span class="sc">+</span> </span>
<span id="cb386-26"><a href="causal-inference-with-linear-models.html#cb386-26" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk06-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk06)TODO: caption.
</p>
</div>
<p>Compared to the last chapter, note that we now have to include a term in our model for the additional predictor variable. Just as we specify values for the predictor of interest, we have to specify values for the other predictor variables. One common approach is to hold other predictor variables constant at their mean while examining what the priors imply about other model terms. And that’s what I’ve done here. Notice that I’m plotting what the priors imply about the relationship between drownings and ice cream sales (<code>c_vals</code>) while setting the value of temperature to 0, which is the mean on the mean-centered scale. Our priors aren’t perfect, as we can see some negative values of drownings implied. We could consider tightening up the priors for the slopes, but my sense (without having much domain knowledge here) is that these priors are already pretty conservative, in that they say there’s a 95% probability that the change in drownings per unit change in ice cream sales (or temperature) is no more than 0.5 while holding the other predictor variable constant. We’ll proceed with these priors.</p>
</div>
<div id="fitting-the-multiple-regression-model" class="section level3 hasAnchor" number="11.1.4">
<h3><span class="header-section-number">11.1.4</span> Fitting the multiple regression model<a href="causal-inference-with-linear-models.html#fitting-the-multiple-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s go ahead and estimate the parameters in the multiple regression model, and then we will focus on interpretation. Specifying a multiple regression model in brms is simple. All we need to do is specify all the predictors in the model, separated by the <code>+</code> operator.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="causal-inference-with-linear-models.html#cb387-1" tabindex="-1"></a><span class="co">#mean center temp</span></span>
<span id="cb387-2"><a href="causal-inference-with-linear-models.html#cb387-2" tabindex="-1"></a>d<span class="sc">$</span>temp.c <span class="ot">&lt;-</span> d<span class="sc">$</span>temperature_F <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>temperature_F)</span>
<span id="cb387-3"><a href="causal-inference-with-linear-models.html#cb387-3" tabindex="-1"></a></span>
<span id="cb387-4"><a href="causal-inference-with-linear-models.html#cb387-4" tabindex="-1"></a><span class="co">#specify model formula</span></span>
<span id="cb387-5"><a href="causal-inference-with-linear-models.html#cb387-5" tabindex="-1"></a>m2.formula <span class="ot">&lt;-</span> <span class="fu">bf</span>(drownings <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sales.c <span class="sc">+</span> temp.c,</span>
<span id="cb387-6"><a href="causal-inference-with-linear-models.html#cb387-6" tabindex="-1"></a>                <span class="at">family =</span> gaussian) </span>
<span id="cb387-7"><a href="causal-inference-with-linear-models.html#cb387-7" tabindex="-1"></a></span>
<span id="cb387-8"><a href="causal-inference-with-linear-models.html#cb387-8" tabindex="-1"></a><span class="co">#specify priors</span></span>
<span id="cb387-9"><a href="causal-inference-with-linear-models.html#cb387-9" tabindex="-1"></a>m2.prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">13</span>, <span class="dv">2</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb387-10"><a href="causal-inference-with-linear-models.html#cb387-10" tabindex="-1"></a>              <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.25</span>), <span class="at">class =</span> b), <span class="co">#applies to all slopes</span></span>
<span id="cb387-11"><a href="causal-inference-with-linear-models.html#cb387-11" tabindex="-1"></a>              <span class="fu">prior</span>(<span class="fu">uniform</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">class =</span> sigma, <span class="at">lb=</span><span class="dv">0</span>, <span class="at">ub=</span><span class="dv">5</span>))</span>
<span id="cb387-12"><a href="causal-inference-with-linear-models.html#cb387-12" tabindex="-1"></a>              </span>
<span id="cb387-13"><a href="causal-inference-with-linear-models.html#cb387-13" tabindex="-1"></a><span class="co">#compute the posterior</span></span>
<span id="cb387-14"><a href="causal-inference-with-linear-models.html#cb387-14" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d,</span>
<span id="cb387-15"><a href="causal-inference-with-linear-models.html#cb387-15" tabindex="-1"></a>         <span class="at">formula =</span> m2.formula,</span>
<span id="cb387-16"><a href="causal-inference-with-linear-models.html#cb387-16" tabindex="-1"></a>         <span class="at">prior =</span> m2.prior,</span>
<span id="cb387-17"><a href="causal-inference-with-linear-models.html#cb387-17" tabindex="-1"></a>         <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb387-18"><a href="causal-inference-with-linear-models.html#cb387-18" tabindex="-1"></a>         <span class="at">seed=</span><span class="dv">123</span>)</span>
<span id="cb387-19"><a href="causal-inference-with-linear-models.html#cb387-19" tabindex="-1"></a></span>
<span id="cb387-20"><a href="causal-inference-with-linear-models.html#cb387-20" tabindex="-1"></a><span class="fu">plot</span>(m2)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk07-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk07)TODO: caption.
</p>
</div>
<p>Our initial plot of the posteriors and the traceplots look good. It looks like each of the four parameters has converged. Let’s take a look at the model summary:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="causal-inference-with-linear-models.html#cb388-1" tabindex="-1"></a><span class="fu">print</span>(m2)</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity 
## Formula: drownings ~ 1 + sales.c + temp.c 
##    Data: d (Number of observations: 120) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept    13.45      0.10    13.26    13.64 1.00     3122     2018
## sales.c      -0.07      0.05    -0.16     0.03 1.00     2086     1836
## temp.c        0.19      0.03     0.13     0.24 1.00     2095     1763
## 
## Further Distributional Parameters:
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma     1.04      0.07     0.91     1.18 1.00     2631     2070
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>Thus looks like the output of a linear model with a single predictor, except now we have a row for the intercept and each predictor in the regression coefficients section. The posterior mean slope for ice cream sales is now -0.07, with the 95% credible interval overlapping 0 (-0.16, 0.03). Conversely, the posterior mean slope for temperature is 0.19, with a 95% credible interval from 0.13 to 0.24, notably all in positive territory.</p>
<p>So what does this mean? The estimated slope for ice cream sales is <em>very</em> different than it was when we fit a simple linear model with ice cream sales being the only predictor. In this model, our interpretation is that when we hold temperature constant, there’s not a consistent change in drownings when we change ice cream sales. The posterior mean is actually negative, which would imply that when we hold temperature constant, drownings actually <em>declines</em> for every unit increase in ice cream sales. But because the posterior distribution broadly overlaps 0, there’s a lot of uncertainty about this association when we hold temperature constant. This tells us that although ice cream sales are predictive of drownings (when not accounting for temperature), ice cream sales don’t seem to have a <em>causal</em> effect on drownings. Phew! I’m ready for some Ben and Jerry’s.</p>
<p>What about the coefficient for temperature. Our interpretation there is that when we hold ice cream sales constant, there <em>is</em> value in knowing what tmeperature it is. Drowings appear to increase as temperature increases while holding ice cream sales constant. That’s of course no surprise. A pistachio gelato on the Italian Riviera in July is sounding pretty good right now.</p>
</div>
<div id="prediction-plots-for-multiple-regression-models" class="section level3 hasAnchor" number="11.1.5">
<h3><span class="header-section-number">11.1.5</span> Prediction plots for multiple regression models<a href="causal-inference-with-linear-models.html#prediction-plots-for-multiple-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider our multiple regression model, which has drownings as the response variable and both ice cream sales and air temperature as the predictor variables. We want to know what the predictive power of ice cream sales is once we condition on air temperature. Of course the regression model output says there’s no additional predictive power of ice cream scales when holding temperature constant, but how do we visualize that?</p>
<p>The idea here is that we can use our model to predict values of the response variable given particular values of the explanatory variables. In other words, what would we predict the number of drownings to be given particular values of ice cream sales and air temperature. Because we have a multiple regression model, we can make predictions of drownings for <em>any</em> combination of predictor values, even ones we haven’t seen.</p>
<p>As an example, consider that the average July temperature is 76 F in the United States. July is also National Ice Cream Month, and let’s say it’s a banner month for ice cream sales with 60 million ice cream sales. What would the predicted number of drownings be under these circumstances? We can easily compute the predicted drownings when the temperature is 76 F and the number of ice cream sales is 60 for each sample of the posterior, and then summarize the outcome:</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="causal-inference-with-linear-models.html#cb390-1" tabindex="-1"></a><span class="co">#extract the posterior samples</span></span>
<span id="cb390-2"><a href="causal-inference-with-linear-models.html#cb390-2" tabindex="-1"></a>m.post <span class="ot">&lt;-</span> <span class="fu">as_draws_df</span>(m2)</span>
<span id="cb390-3"><a href="causal-inference-with-linear-models.html#cb390-3" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> m.post<span class="sc">$</span>b_Intercept <span class="sc">+</span> </span>
<span id="cb390-4"><a href="causal-inference-with-linear-models.html#cb390-4" tabindex="-1"></a>          m.post<span class="sc">$</span>b_sales.c<span class="sc">*</span>(<span class="dv">60</span><span class="sc">-</span><span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions)) <span class="sc">+</span></span>
<span id="cb390-5"><a href="causal-inference-with-linear-models.html#cb390-5" tabindex="-1"></a>          m.post<span class="sc">$</span>b_temp.c<span class="sc">*</span>(<span class="dv">76</span><span class="sc">-</span><span class="fu">mean</span>(d<span class="sc">$</span>temperature_F))</span>
<span id="cb390-6"><a href="causal-inference-with-linear-models.html#cb390-6" tabindex="-1"></a></span>
<span id="cb390-7"><a href="causal-inference-with-linear-models.html#cb390-7" tabindex="-1"></a><span class="co">#summarize</span></span>
<span id="cb390-8"><a href="causal-inference-with-linear-models.html#cb390-8" tabindex="-1"></a><span class="fu">mean</span>(y.pred)</span></code></pre></div>
<pre><code>## [1] 15.74188</code></pre>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="causal-inference-with-linear-models.html#cb392-1" tabindex="-1"></a><span class="fu">quantile</span>(y.pred, <span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 14.56280 16.94698</code></pre>
<p>Here we see the mean of the posterior prediction is 15.74 drownings, with a 95% credible interval of 14.56 to 16.95. I wanted to walk through that example to show you that making predictions of a response variable is as simple as plugging in values of the explanatory variable. We could use the <code>fitted</code> function to make a prediction like that much more efficiently:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="causal-inference-with-linear-models.html#cb394-1" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m2, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">sales.c =</span> <span class="dv">60</span> <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions),</span>
<span id="cb394-2"><a href="causal-inference-with-linear-models.html#cb394-2" tabindex="-1"></a>                                        <span class="at">temp.c =</span> <span class="dv">76</span> <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>temperature_F)))</span>
<span id="cb394-3"><a href="causal-inference-with-linear-models.html#cb394-3" tabindex="-1"></a>y.pred</span></code></pre></div>
<pre><code>##      Estimate Est.Error    Q2.5    Q97.5
## [1,] 15.74188 0.5928937 14.5628 16.94698</code></pre>
<p>The most common way of graphically displaying the output of a multiple regression is to predict what would happen to the response variable as we change the value of one predictor while holding other predictors constant. This is essentially what a true experiment attempts to do, but of course not all research questions can be analyzed with an experiment (certainly not this one).</p>
<p>Let’s look at an example. What would happen to the number of drownings if we change ice cream sales but hold air temperature constant at its average?</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="causal-inference-with-linear-models.html#cb396-1" tabindex="-1"></a><span class="co">#values of mean-centered ice cream sales to predict on</span></span>
<span id="cb396-2"><a href="causal-inference-with-linear-models.html#cb396-2" tabindex="-1"></a>x.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fu">min</span>(d<span class="sc">$</span>sales.c), <span class="at">to=</span><span class="fu">max</span>(d<span class="sc">$</span>sales.c), <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb396-3"><a href="causal-inference-with-linear-models.html#cb396-3" tabindex="-1"></a></span>
<span id="cb396-4"><a href="causal-inference-with-linear-models.html#cb396-4" tabindex="-1"></a><span class="co">#make the predictions</span></span>
<span id="cb396-5"><a href="causal-inference-with-linear-models.html#cb396-5" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m2, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">sales.c =</span> x.pred,</span>
<span id="cb396-6"><a href="causal-inference-with-linear-models.html#cb396-6" tabindex="-1"></a>                                        <span class="at">temp.c =</span> <span class="dv">0</span>))</span>
<span id="cb396-7"><a href="causal-inference-with-linear-models.html#cb396-7" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="at">sales.c =</span> x.pred, y.pred)</span>
<span id="cb396-8"><a href="causal-inference-with-linear-models.html#cb396-8" tabindex="-1"></a></span>
<span id="cb396-9"><a href="causal-inference-with-linear-models.html#cb396-9" tabindex="-1"></a><span class="co">#put ice cream sales back on actual scale</span></span>
<span id="cb396-10"><a href="causal-inference-with-linear-models.html#cb396-10" tabindex="-1"></a>y.pred<span class="sc">$</span>sales <span class="ot">&lt;-</span> y.pred<span class="sc">$</span>sales.c <span class="sc">+</span> <span class="fu">mean</span>(d<span class="sc">$</span>ice_cream_sales_millions)</span>
<span id="cb396-11"><a href="causal-inference-with-linear-models.html#cb396-11" tabindex="-1"></a></span>
<span id="cb396-12"><a href="causal-inference-with-linear-models.html#cb396-12" tabindex="-1"></a><span class="co">#now plot the relationship</span></span>
<span id="cb396-13"><a href="causal-inference-with-linear-models.html#cb396-13" tabindex="-1"></a><span class="fu">ggplot</span>(y.pred) <span class="sc">+</span></span>
<span id="cb396-14"><a href="causal-inference-with-linear-models.html#cb396-14" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> y.pred, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>,</span>
<span id="cb396-15"><a href="causal-inference-with-linear-models.html#cb396-15" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;slategray3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb396-16"><a href="causal-inference-with-linear-models.html#cb396-16" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> sales, <span class="at">y =</span> Estimate, <span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>)) <span class="sc">+</span></span>
<span id="cb396-17"><a href="causal-inference-with-linear-models.html#cb396-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Ice cream sales (millions)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted number of drownings&quot;</span>) <span class="sc">+</span></span>
<span id="cb396-18"><a href="causal-inference-with-linear-models.html#cb396-18" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb396-19"><a href="causal-inference-with-linear-models.html#cb396-19" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk11-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk11)TODO: caption.
</p>
</div>
<p>Here we see that if we hold the air temperature constant at its mean, there appears to be a mild decrease in the number of drownings. But note there’s a lot of uncertainty around the posterior mean estimate as indicated by the 95% credible interval in blue. You could fit some pretty flat or even weakly positive slopes in that credible interval.</p>
<p>What if we did the opposite, holding the number of ice cream sales constant at its mean while varying air temperature? Let’s see:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="causal-inference-with-linear-models.html#cb397-1" tabindex="-1"></a><span class="co">#values of mean-centered temperature to predict on</span></span>
<span id="cb397-2"><a href="causal-inference-with-linear-models.html#cb397-2" tabindex="-1"></a>x.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fu">min</span>(d<span class="sc">$</span>temp.c), <span class="at">to=</span><span class="fu">max</span>(d<span class="sc">$</span>temp.c), <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb397-3"><a href="causal-inference-with-linear-models.html#cb397-3" tabindex="-1"></a></span>
<span id="cb397-4"><a href="causal-inference-with-linear-models.html#cb397-4" tabindex="-1"></a><span class="co">#make the predictions</span></span>
<span id="cb397-5"><a href="causal-inference-with-linear-models.html#cb397-5" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">fitted</span>(m2, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">temp.c =</span> x.pred,</span>
<span id="cb397-6"><a href="causal-inference-with-linear-models.html#cb397-6" tabindex="-1"></a>                                        <span class="at">sales.c =</span> <span class="dv">0</span>))</span>
<span id="cb397-7"><a href="causal-inference-with-linear-models.html#cb397-7" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="at">temp.c =</span> x.pred, y.pred)</span>
<span id="cb397-8"><a href="causal-inference-with-linear-models.html#cb397-8" tabindex="-1"></a></span>
<span id="cb397-9"><a href="causal-inference-with-linear-models.html#cb397-9" tabindex="-1"></a><span class="co">#put ice cream sales back on actual scale</span></span>
<span id="cb397-10"><a href="causal-inference-with-linear-models.html#cb397-10" tabindex="-1"></a>y.pred<span class="sc">$</span>temp <span class="ot">&lt;-</span> y.pred<span class="sc">$</span>temp.c <span class="sc">+</span> <span class="fu">mean</span>(d<span class="sc">$</span>temperature_F)</span>
<span id="cb397-11"><a href="causal-inference-with-linear-models.html#cb397-11" tabindex="-1"></a></span>
<span id="cb397-12"><a href="causal-inference-with-linear-models.html#cb397-12" tabindex="-1"></a><span class="co">#now plot the relationship</span></span>
<span id="cb397-13"><a href="causal-inference-with-linear-models.html#cb397-13" tabindex="-1"></a><span class="fu">ggplot</span>(y.pred) <span class="sc">+</span></span>
<span id="cb397-14"><a href="causal-inference-with-linear-models.html#cb397-14" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> y.pred, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>,</span>
<span id="cb397-15"><a href="causal-inference-with-linear-models.html#cb397-15" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">&quot;slategray3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> <span class="dv">1</span>,</span>
<span id="cb397-16"><a href="causal-inference-with-linear-models.html#cb397-16" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> Estimate, <span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>)) <span class="sc">+</span></span>
<span id="cb397-17"><a href="causal-inference-with-linear-models.html#cb397-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Air temperature (F)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted number of drownings&quot;</span>) <span class="sc">+</span></span>
<span id="cb397-18"><a href="causal-inference-with-linear-models.html#cb397-18" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb397-19"><a href="causal-inference-with-linear-models.html#cb397-19" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="ch11_causalInferenceWithLinearModels_files/figure-html/c11_chunk12-1.png" alt="TODO: caption." width="672" />
<p class="caption">
(#fig:c11_chunk12)TODO: caption.
</p>
</div>
<p>Here we shoudl expect drownings to strongly increase with air temperature while holding ice cream sales constant. Remember that in our DAG we assumed temperature affects drownings by mediating the number of swimmers or along the ice cream sales pathway. Because we are holding ice cream sales constant, the prediction plot repesents the causal effect of air temperature on drownings via the indirect pathway involving the number of swimmers. We could generate another plot that represents the total effect of air temperature on predicted number of drownings, but we would need a different linear model that estimates the total effect. In the current linear model, the effect of temperature is estimated while holding ice cream sales constant.</p>
</div>
</div>
<div id="dag-informed-predictors-categorical-variables-what-multiple-regression-is-doing-with-predictor-residual-plot" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> DAG-informed predictors, categorical variables, what multiple regression is doing with predictor residual plot<a href="causal-inference-with-linear-models.html#dag-informed-predictors-categorical-variables-what-multiple-regression-is-doing-with-predictor-residual-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="graphical-causal-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="interaction-effects.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true,
    "toc_depth": 2
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
